### ISSUE TITLE
evidence: pool crashes with block pruning enabled

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5179] opened 2020-07-30 15:54 UTC
**Tendermint version:** 0.34.0-rc1

Oasis Labs reports the following:

>a strange thing happens in one of our tests where block pruning is enabled. a non-validator node is at block 71, keeping only the last 50 blocks. the node gets terminated and when it restarts, the logs indicate both app and tendermint state are at block 71, but then tendermint node startup fails with block meta for height 19 not found (the height is not found because it has been pruned, but it is not clear why it would need to be looked up). the error seems to originate from the evidence pool constructor, but not sure why it gets that old height. 

Sounds like the evidence pool doesn't handle block pruning properly. We should also check that it behaves properly on e.g. state synced nodes.

**Comment by cmwaters** [comment] 2020-07-30 15:59
I will need to look at this more closely but at first glance I believe this stems from having the phantom validator evidence. What happens at restart is that it goes through the stateDB to try create a map of all the validators and the last time they were in the validator set i.e. a list of validators that are still staked and could be possible phantom validators.

**Comment by erikgrinaker** [comment] 2020-07-30 16:00
Ah, in that case I suppose #5168 would "fix" it. Would be nice to check that nothing else relies on a complete history being present either.

**Comment by cmwaters** [comment] 2020-07-30 16:01
https://github.com/tendermint/tendermint/blob/4a06dc99160df4003afa783e59e22af16796d7a0/evidence/pool.go#L757

**Comment by kostko** [comment] 2020-07-30 16:04
Thanks for looking into this! It seems to be fairly easy to reproduce, so let me know if you need to test a potential fix.

**Comment by melekes** [comment] 2020-07-31 05:37
> What happens at restart is that it goes through the stateDB to try create a map of all the validators and the last time they were in the validator set i.e. a list of validators that are still staked and could be possible phantom validators.

we can remove this part now, right?

**Comment by cmwaters** [comment] 2020-07-31 05:38
Yeah I'm going to remove it today (alongside with the rest of phantom evidence)

**Comment by melekes** [comment] 2020-07-31 05:40
created https://github.com/tendermint/tendermint/issues/5180

**Comment by cmwaters** [comment] 2020-07-31 10:43
@kostko we've just removed the phantom validator code (#5168) now, so this might have fixed the problem if you would like to try test it again. I'm just checking the rest of the evidence module to make sure nothing else relies on a complete history

**Comment by kostko** [comment] 2020-07-31 11:12
Yeah I can confirm that initial tests now pass without any issues!

**Comment by cmwaters** [comment] 2020-07-31 13:32
That's good to hear. I'm going to close this issue now, but please let us know if you notice anything else throughout your testing.

**Closed by cmwaters** 2020-07-31 13:32 UTC
Labels: P:High, T:bug
