### ISSUE TITLE
Support for DNS names in config

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1131] opened 2018-01-21 12:39 UTC
It would be great to support domain names in the configs.

So instead of entering an IP address, we could enter `validator.block.finance`.

@mdyring 

Partial discussion here: #865

**Comment by melekes** [comment] 2018-01-22 12:40
Duplicate of https://github.com/tendermint/tendermint/issues/869

**Closed** 2018-01-22 13:59 UTC
