### ISSUE TITLE
panic during panic

### ISSUE THREAD

**Issue by Vgk88** [tendermint/tendermint#5469] opened 2020-10-06 02:24 UTC
I am taking part in testing a Sentinel Turing-3a and get this error during a network stress test.

I got this error:

> [signal SIGBUS: bus error code=0x2 addr=0x1c0ef1d pc=0x40709e]
> 
> runtime stack:
> fatal error: unexpected signal during runtime execution
> panic during panic
> [signal SIGBUS: bus error code=0x2 addr=0x1c10994 pc=0x40709e]
> 
> runtime stack:
> fatal error: unexpected signal during runtime execution
> stack trace unavalable
> 

You can find screenshot here [https://cyber.page/ipfs/QmREE2vewcQFskRdPzydbCmbFvSBjvQt83TFPJN2RTbv5E](https://cyber.page/ipfs/QmREE2vewcQFskRdPzydbCmbFvSBjvQt83TFPJN2RTbv5E)

After reboot, I synchronized my node and unjail validator.

**Comment by melekes** [comment] 2020-10-06 06:11
Hi! Could you paste the entire stack trace of the panic? You can use https://gist.github.com/ or https://pastebin.com/. Otherwise it's not clear what the error is. Also, the screenshot link seems to be broken.

**Comment by melekes** [comment] 2020-10-06 06:12
What Tendermint version were you running?

**Comment by melekes** [comment] 2020-10-06 06:13
Next time please use our [template](https://github.com/tendermint/tendermint/issues/new/choose) for new issues. It will help us identify the issue quicker.

**Comment by Vgk88** [comment] 2020-10-08 10:45
I use Tendermint v0.32.13.
Fix me screenshot. Please check.
Also i have logs of this error but it is scan from screenshot
[https://pastebin.com/jM7wCQGX](https://pastebin.com/jM7wCQGX)

**Comment by erikgrinaker** [comment] 2020-10-08 10:53
Tendermint isn't able to write to disk, this looks like either a hardware or filesystem failure.

**Comment by melekes** [comment] 2020-10-08 14:41
"read-only file system" you need to make sure disk is mounted in read-write mode (NOT read-only mode).

**Comment by erikgrinaker** [comment] 2020-10-08 14:45
>"read-only file system" you need to make sure disk is mounted in read-write mode (NOT read-only mode).

This is usually caused by the kernel detecting unrecoverable filesystem corruption and switching the file system to read-only mode for safety.

**Comment by Vgk88** [comment] 2020-10-08 18:38
I would also like to say that I run 2 different Tendermint networks running at this moment. After reboot, this network started without problems. But  other network didn't start syncing. DBUS enable meditation.

I moved these networks to VPS and reinstalled Linux on my computer.

**Comment by melekes** [comment] 2020-10-09 09:33
As this is not the software error, I am going to close this. Feel free to ask us or community any other questions on [Discord](https://discord.gg/AzefAFd).

**Closed by melekes** 2020-10-09 09:33 UTC
