### ISSUE TITLE
Support 32-bit architectures

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#72] opened 2015-05-21 17:06 UTC
Support a field tag like

```
type MyStruct struct {
    MyField uint32 `binary:”uvarint"`
}
```

instead of

```
type MyStruct struct {
    "MyField uint"
}
```

and replace usage of (u)int, make it explicitly (u)int64/32/16.

**Comment by jtremback** [comment] 2015-05-21 17:21
:+1:

**Comment by jaekwon** [comment] 2015-05-23 21:45
We now support uint64 `binary:"varint"` as well as uint (automatically varint).
I've thought about changing all the block heights to uint64s, but decided against it because uint32 is sufficient for centuries.

**Comment by paulrd** [comment] 2015-06-21 01:18
I'm getting the following on the Arm6 raspberry pi (32-bit):

```bash
go install ./cmd/epm-binary-generator
epm-binary-generator ./cmd/epm ./commands thelonious tendermint ethereum
# github.com/eris-ltd/epm-go/Godeps/_workspace/src/github.com/tendermint/tendermint/binary
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:171: constant 4294967296 overflows uint
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:174: constant 1099511627776 overflows uint
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:177: constant 281474976710656 overflows uint
Godeps/_workspace/src/github.com/tendermint/tendermint/binary/int.go:180: constant 72057594037927936 overflows uint
Error on chain install: Error building tendermint exit status 2
```

**Comment by jaekwon** [comment] 2015-06-21 13:06
Thanks @paulrd.  Is this blocking you, or can it wait a week?

**Comment by jaekwon** [comment] 2015-06-21 13:14
What happens when you try this?

```diff
--- a/binary/int.go
+++ b/binary/int.go
@@ -158,8 +158,7 @@ func ReadUint64(r io.Reader, n *int64, err *error) uint64 {
 
 // Varint
 
-func uvarintSize(i_ uint) int {
-       i := uint64(i_)
+func uvarintSize(i uint64) int {
        if i == 0 {
                return 0
        }
@@ -193,7 +192,7 @@ func WriteVarint(i int, w io.Writer, n *int64, err *error) {
                negate = true
                i = -i
        }
-       var size = uvarintSize(uint(i))
+       var size = uvarintSize(uint64(i))
        if negate {
                // e.g. 0xF1 for a single negative byte
                WriteUint8(uint8(size+0xF0), w, n, err)
@@ -236,7 +235,7 @@ func ReadVarint(r io.Reader, n *int64, err *error) int {
 // Uvarint
 
 func WriteUvarint(i uint, w io.Writer, n *int64, err *error) {
-       var size = uvarintSize(i)
+       var size = uvarintSize(uint64(i))
        WriteUint8(uint8(size), w, n, err)
        if size > 0 {
                buf := make([]byte, 8)
```

This isn't the best solution but it should work (e.g. for centuries).  The best solution might be to convert all uints to uint64 `binary:"varint"`.

**Comment by paulrd** [comment] 2015-06-21 14:20
Thanks! I'm might try that patch except now I realize that eris-ltd/epm-go is using go-dep on an older version of int.go. I should try the updated version first maybe. I'm new to go and Godeps so this might take a bit to figure out. I'll keep you posted.

**Comment by paulrd** [comment] 2015-06-21 14:52
It looks like updating to the current version of int.go fixed the problem but now I get a similar error caused by line 176 of state/priv_validator.go. It looks like some privVal.LastRound is too small to accept math.MaxUint64.

```bash
Godeps/_workspace/src/github.com/tendermint/tendermint/state/priv_validator.go:176: constant 18446744073709551615 overflows uint
```

**Comment by compleatang** [comment] 2015-06-26 10:19
@paulrd godeps can be a bit of a beast, but essentially once you've applied the patch to tendermint, then go into epm-go and `godep update github.com/tendermint/tendermint` and then `make` it should work fine.

**Comment by ebuchman** [comment] 2015-06-26 15:48
I'm afraid running godep update on epm with a recent version of tendermint will break alot of things. if you apply this patch, you should only do so on the commit of tendermint that epm is currently using

**Comment by paulrd** [comment] 2015-06-26 17:33
Yeah, I was just planning on manually changing whatever was needed to fix the bug then do a pull request with epm-go. I think priv_validator.go:176 is the same in both versions so it would be a bug in this project that's why I'm posting here instead of epm-go. But I could be wrong as ultimately there may be other related files causing this bug (I haven't even diff'd the file in question, just glanced at both versions). Do you have tenderment currently compiling on 32-bit ARM6 (raspberry pi rev1)?

**Comment by jaekwon** [comment] 2015-07-02 05:04
Looks like a little change fixes it for linux/386.  I'll try ARM6 soon.
The vm/secp256k1 cgo dependency is the only reason why we can't cross-compile.  I wonder if there's a good Go version.

**Comment by ebuchman** [comment] 2015-07-02 05:40
https://github.com/btcsuite/btcd/tree/master/btcec but I haven't played with it yet

**Comment by adrianbrink** [comment] 2017-05-08 07:05
@jaekwon Are we still striving for 32bit support?

Ethan mentioned this article on slack: https://www.raspberrypi.org/products/raspberry-pi-3-model-b/

**Comment by adrianbrink** [comment] 2017-06-16 12:23
Closing it in favour of #483

**Closed** 2017-06-16 12:23 UTC
Labels: Type: Enhancement
