### ISSUE TITLE
Flag DeliverTx invalid txs in block header

### ISSUE THREAD

**Issue by t-bast** [tendermint/tendermint#922] opened 2017-12-04 17:57 UTC
FEATURE REQUEST

Hey guys,

In the documentation, the DeliverTx section says:
"The block header will be updated (TODO) to include some commitment to the results of DeliverTx, be it a bitarray of non-OK transactions, or a merkle root of the data returned by the DeliverTx requests, or both."

I'd be really interested in that feature :)
Do you know if you're still considering this?
Otherwise I'll store this on my side, but I think it makes sense to have in the block's header (for people directly querying the blockchain for verification for example).

Thanks!

**Comment by ebuchman** [comment] 2017-12-05 04:35
Yes, we still plan to support this - specifically both :)

**Comment by t-bast** [comment] 2017-12-05 07:58
Awesome thanks !

**Comment by ethanfrey** [comment] 2017-12-07 21:03
Interestingly enough, this info is calculated and passed quite close to the where it can be read by the next block: 
https://github.com/tendermint/tendermint/blob/develop/state/state.go#L222-L224

The issue is just adding the ABCIResults to the header? Similar to how AppHash is added, right?

So block header H+1 would contain the `AppHash` after executing all transactions up to and including block H, and the `ResultHash` for all ABCIResults in block H. And then we persist that info (we do already for /tx don't we?) and expose an rpc endpoint to get all results from a given block?

Is this understanding correct? Can you help spec out a bit more how it would be exposed?

**Comment by ethanfrey** [comment] 2017-12-07 21:07
Ah, mentioned in another issue #338 

So we just need to add the `LastResultHash` and `/block_extra` for this issue?

**Comment by t-bast** [comment] 2017-12-08 08:11
Thanks for all the comments Ethan, this is really helpful.
From my use case's point of view, I'm getting a whole block and I would simply like a way to flag which Tx in that block were in fact invalid when delivered.
My ABCI app doesn't include invalid delivered Tx in its app hash, so when there is an invalid Tx in a block and I don't know which one it is, I'm screwed and can't re-create my app hash (unless I try all combinations of Txs in that block until the app hash matches).
Getting the H+1 block and looking at a bitmap in its header would be a good solution for my use case.

**Comment by ebuchman** [comment] 2017-12-11 17:20
Can you take a look at the TxResults section of https://github.com/tendermint/tendermint/issues/952 and let us know if that is sufficient? 

Note that in contradicts my statement above of `specifically both`. We will include the merkle root of the results, but not the results themselves, or a list of which ones were invalid. That can be provable queried from the node.

Hope that's fine. Will close this issue in favor of https://github.com/tendermint/tendermint/issues/952

**Closed by ebuchman** 2017-12-11 17:20 UTC

**Comment by t-bast** [comment] 2017-12-12 08:22
Thanks, it looks good!
