### ISSUE TITLE
Problems related to ProposerPriority

### ISSUE THREAD

**Issue by Slamper** [tendermint/tendermint#2960] opened 2018-12-02 10:21 UTC
The new ProposerPriority mechanism caused problems in the latest Gaia-9002 network.

Since the default priority is -totalPrio * C I assume that in the block in which a validator is added the shifting effectively adds `AvgProposerPriority` (subtraction of negative prio) to everyone. So the ones bonding earlier will experience more of these "bumps"

We have some strange developments of proposer_priority.

![image](https://user-images.githubusercontent.com/1405758/49338613-b4a80a80-f623-11e8-83cd-1b2e73f7724b.png)

Table of nuevax priority data: https://docs.google.com/spreadsheets/d/1_GC_HRO4iDTLDfH7OBkPw83p5oFHFA_BQL68RoIBOVw/edit?usp=sharing

The small spikes happen every 10 blocks.
Every time the sudden spike up happened a new validator was added to the active set.
The delta of the sudden increases is `AvgProposerPriority` due to the shifting.

When then the genesis validators unbonded, some validators were left with close to MaxInt64 Priorities which in this case lead to one validator proposing the following 200 blocks after the unbonding of the high-weight validators.

That validator proposing the following 200 blocks was the one, which was the first to bond after the genesis validators. He had the highest proposer_priority because he experienced the most validator added events (n) and subsequently the most sudden spikes as seen in the graphs. 

After these 200 blocks the only ones to propose were the said validator and the validator that bonded after him as that one experienced (n-1) spikes.

Rel: #2942

cc: @ebuchman @Liamsi @melekes @ValarDragon

**Comment by cwgoes** [comment] 2018-12-02 10:56
Note: graph is of `ProposerPriority` of [nuevax](https://hubble.figment.network/chains/gaia-9002/validators/9D93AD02FE1BD7E76B9E58D7EB461088EAD011E5).

**Comment by cwgoes** [comment] 2018-12-02 11:01
Another interesting edge case caused by a very large validator suddenly unbonding: validators which had recently proposed were reset to `-total_power` accum (large and negative), while a validator who bonded just after was set to the new `-total_power` accum (small and negative), so ended up proposing hundreds of blocks in a row while the other validators' accums "caught up".

**Comment by cwgoes** [comment] 2018-12-03 10:13
Haven't though through too much, but what about, when a validator unbonds (or also decreases in power, I suppose), just increasing everyone's accum by the power difference? That seems like it would solve the imbalance between previously-bonded validators and ones which bond just after the large one unbonds.

**Comment by ebuchman** [comment] 2019-01-19 21:06
This should be fixed by #3049

**Closed by ebuchman** 2019-01-19 21:06 UTC
Labels: consensus, protocol
