### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ying2025** [tendermint/tendermint#1651] opened 2018-05-31 02:49 UTC
![image](https://user-images.githubusercontent.com/28092539/40758167-8eba33ee-64be-11e8-88c7-e37fca9307b2.png)
![image](https://user-images.githubusercontent.com/28092539/40758193-b5d3bc84-64be-11e8-8000-ff8a3af7f2c6.png)
This is the path “”/home/zhr/go/src/github.com/tendermint“”
![image](https://user-images.githubusercontent.com/28092539/40758229-e4c025d2-64be-11e8-82f9-4ae3ac9ec579.png)
![image](https://user-images.githubusercontent.com/28092539/40758354-7bbb7824-64bf-11e8-9a72-d068526ba3ff.png)
![image](https://user-images.githubusercontent.com/28092539/40758369-8f86a3e2-64bf-11e8-938a-3af2485b972d.png)
I have gometalinter.v2 but I cannot find how to set the path , whethe it's
export PATH=/home/zhr/go/src/gopkg.in/alecthomas/gometalinter.v2

![image](https://user-images.githubusercontent.com/28092539/40758496-358cdebe-64c0-11e8-85ed-110da476c305.png)
It's also failure

**Comment by ying2025** [comment] 2018-05-31 02:50
I donot konw why, is there anyone why konw how should I do

**Comment by ebuchman** [comment] 2018-05-31 03:40
Try doing `export PATH=$GOPATH/bin:$PATH`

**Comment by zramsay** [comment] 2018-05-31 11:53
duplicate of #1660. @ying2025 please comment in that issue if the script i linked does not work

**Closed by zramsay** 2018-05-31 11:53 UTC
