### ISSUE TITLE
Websocket RPC endpoint description is wrong

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#512] opened 2017-05-21 19:09 UTC
When you go to http://localhost:46657/ you see a list of RPC endpoints.
One of them is 'http://localhost:46657/subscribe?event=_'.

The problem is not that it doesn't work, but that the endpoint is incorrect.  It should really be 'http://localhost:46657/websocket'.  We should maybe just remove these from the RPC endpoints list, or at least show them separately.

**Comment by ValarDragon** [comment] 2018-08-25 19:05
This has been changed to `http://localhost:26657/subscribe?query=_". Is this resolved?

**Comment by jackzampolin** [comment] 2019-06-21 15:39
@marbar3778 @gamarin

**Comment by marbar3778** [comment] 2019-08-31 18:04
we can update this page to the swagger docs, if we would like. This will uniform with how the sdk represents `gaiacli rest`

**Comment by tessr** [comment] 2020-11-16 17:37
I think this is a duplicate of #3618? Or at least covers the same surface area?

**Closed by tessr** 2020-11-16 17:37 UTC
Labels: C:rpc, T:bug, good first issue
