### ISSUE TITLE
evidence: abci.Evidence.Time should be the time of the infringement not the time the evidence was committed

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5169] opened 2020-07-30 10:45 UTC
## Summary

Currently, when creating abci.Evidence the `Time` field is filled with the time that the evidence was committed to a block. However the sdk use the `Time` field as a way to calculate whether the evidence has expired or not, hence it should be the time (in regards to the block) that the infringement happened

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by erikgrinaker** [comment] 2020-07-30 11:00
Why don't we include both times?

**Comment by cmwaters** [comment] 2020-07-30 11:06
I think time is predominantly used by applications to see if the evidence has expired (at least on the side of the sdk). I don't know if there is any use in including the time that it was committed (would that also mean we want the height that it was committed as well?).

**Comment by erikgrinaker** [comment] 2020-07-30 11:20
Yeah, so the basic `Evidence` type takes height and time to mean when the misbehavior occurred, not when it was committed. However, in ABCI `BeginBlockRequest` the height is taken from the evidence but the time is taken from the current block. The time should be taken from the evidence.

**Comment by melekes** [comment] 2020-07-31 04:56
Duplicate of https://github.com/tendermint/tendermint/issues/4150

**Closed by melekes** 2020-07-31 04:56 UTC
Labels: C:evidence
