### ISSUE TITLE
Tx already exists in cache in Tendermint after some blocks created

### ISSUE THREAD

**Issue by skdjango001** [tendermint/tendermint#4927] opened 2020-05-31 08:26 UTC
Hi i am facing issue while creating blocks in tendermint and i am getting error 

```
E[2020-05-31|12:00:01.157] Error on broadcastTxCommit                   module=rpc err="Timed out waiting for tx to be included in a block"
E[2020-05-31|12:00:01.182] Error on broadcastTxCommit                   module=rpc err="Timed out waiting for tx to be included in a block"
E[2020-05-31|12:00:01.206] Error on broadcastTxCommit                   module=rpc err="Timed out waiting for tx to be included in a block"
E[2020-05-31|12:00:03.034] Error on broadcastTxCommit                   module=rpc err="Tx already exists in cache"
E[2020-05-31|12:00:03.184] Error on broadcastTxCommit                   module=rpc err="Tx already exists in cache"
E[2020-05-31|12:00:05.045] Error on broadcastTxCommit                   module=rpc err="Timed out waiting for tx to be included in a block"
E[2020-05-31|12:00:07.048] Error on broadcastTxCommit                   module=rpc err="Tx already exists in cache"
E[2020-05-31|12:00:07.419] Error on broadcastTxCommit                   module=rpc err="Tx already exists in cache"
E[2020-05-31|12:00:07.419] Error on broadcastTxCommit                   module=rpc err="Tx already exists in cache"
E[2020-05-31|12:00:07.421] Error on broadcastTxCommit                   module=rpc err="Tx already exists in cache"
```
```json
 "sync_info": {
      "latest_block_hash": "0C92AA725D204AEA3CE8077AD2314F67B32E082861E194CD72F0E8214FFC2D5E",
      "latest_app_hash": "4E6F205374617465",
      "latest_block_height": "214038",
      "latest_block_time": "2020-05-31T15:59:16.92127851Z",
      "catching_up": false
    },
```

 this is last commited block and then after no blocks created till now and this error occur. @ebuchman @melekes @erikgrinaker

**Comment by melekes** [comment] 2020-06-01 05:43
Tendermint implements first layer of replay protection https://docs.tendermint.com/master/app-dev/app-development.html#replay-protection

**Comment by melekes** [comment] 2020-06-01 06:00
Duplicate of https://github.com/tendermint/tendermint/issues/4928

**Closed by melekes** 2020-06-01 06:00 UTC
Labels: T:question
