### ISSUE TITLE
Optimize CheckTx (ABCI interface)

### ISSUE THREAD

**Issue by HaoyangLiu** [tendermint/tendermint#3158] opened 2019-01-19 03:11 UTC
```
	// Mempool Connection
	CheckTx(tx []byte) ResponseCheckTx // Validate a tx for the mempool
```
As we all know, in Mempool, if recheck is enabled, once a block is applied, all txs which are included in the block will be removed from mempool, and the rest txs will be rechecked for their validity. 

Suppose the mempool size is very large, then the quantity of txs which will be rechecked will be huge. As a result, the applying a block will cost a lot of time, which means TPS will be lowed significantly. 

I have a suggestion about this issue. Take cosmos for example, the CheckTx mainly check the msg validity and signature validity, as well as the signature sequence. As for tx recheck, it is not necessary to check msg validity and signature validity. Only signature sequence need to be verified. Without checking the msg validity and signature validity, the recheck will cost much less time. 

Althrough, turnning off recheck can improve the Blockchain TPS too and avoid this issue. But the proposed blocks may contains many invalid txs. As a result, we can't tell out if the block proposer is just turnning off recheck or deliberately spam invalid txs.

If the CheckTx (ABCI interface) can tell the application whether this is from recheck. The application will do some optimization to accelerate the recheck. And for block proposer, if it spam invalid tx deliberately , it will be slashed.

What do you think about this suggestion? @ebuchman @jaekwon

**Comment by melekes** [comment] 2019-01-19 13:13
Have you seen https://github.com/tendermint/tendermint/issues/2127? What you're describing sounds exactly like the proposed RecheckTx function.

--
Duplicate of https://github.com/tendermint/tendermint/issues/2127.

**Comment by melekes** [comment] 2019-01-19 13:14
Duplicate of #2127.

**Closed by melekes** 2019-01-19 13:14 UTC

**Comment by HaoyangLiu** [comment] 2019-01-19 13:20
I have not seen #2127. I just found the recheck cost too much time.

**Comment by HaoyangLiu** [comment] 2019-01-23 01:47
Good idea. By the way, which milestone will #2127 be in?

**Comment by ebuchman** [comment] 2019-01-23 02:39
Added it to the new v0.32.0. Please provide some thoughts on https://github.com/tendermint/tendermint/issues/2127#issuecomment-456643676. Potentially can be merged sooner if contributed. Thanks!
