### ISSUE TITLE
Break out PrivValidatorConfig

### ISSUE THREAD

**Issue by xla** [tendermint/tendermint#1231] opened 2018-02-20 11:59 UTC
As the amount of aspects grow we want to have configurable for the private validator it would make sense to break it out into it's own type.

**Comment by zramsay** [comment] 2018-02-20 15:24
see #1181

**Comment by greg-szabo** [comment] 2018-02-26 18:23
Duplicate of #1181

**Comment by ebuchman** [comment] 2018-02-28 20:37
This is not the same as #1181.

This is about the Config file and having a separate PrivValidatorConfig for configuration options related to the priv validator.

This is distinct from the content of the PrivValidator itself.

**Comment by ebuchman** [comment] 2019-01-11 02:12
I wonder if this should be in the config.toml or or the priv_validator.json? We don't have a coherent story for the priv_validator.json right now when we're using an external signer, it just becomes a meaningless thing. If we can sync it with the external process and have it be the config for it, that might make more sense.

**Comment by ebuchman** [comment] 2019-01-13 23:59
This issue should simultaneously address concerns from #3105, #3099, #3009, #2657 w.r.t configuration data. Seems to make sense that the priv_validator_key.json can manage this stuff?

**Comment by jackzampolin** [comment] 2019-06-21 23:46
Didn't we do a bunch of work on priv_validator? Closing this issue as I'm pretty sure its been addressed.

**Closed by jackzampolin** 2019-06-21 23:46 UTC
Labels: validator
