### ISSUE TITLE
Dialing failed

### ISSUE THREAD

**Issue by Anjana-Prabhakar** [tendermint/tendermint#5207] opened 2020-08-06 05:55 UTC
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.32.8-759ccebe
**ABCI app** (name for built-in, URL for self-written if it's publicly available):
kvstore
**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
I am running the 4 node tendermint network using docker image. The tendermint network seems to be working fine but i see the following error along with the output. 
`dialing failed (attempts: 1): self ID<1b2b5e5503cd087152adacb496435e3389c494b9> module=pex addr=1b2b5e5503cd087152adacb496435e3389c494b9@192.167.10.2:26656`
**What you expected to happen**:

I expected it to have no failure logs and so would like to understand the statement.
**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):
```
make localnet-start
pass transaction via kvstore
```
**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:
I have included a loop to execute the broadcast_tx_commit function multiple times.
**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**
http://192.167.10.2:26660/metrics page is available. There is no field dump_consensus_state in it. 
http://192.167.10.2:26656/ gives a connection to server was reset.

**Anything else we need to know**:

**Comment by marbar3778** [comment] 2020-08-06 07:06
based on the error log, it seems the node is trying to dial itself. Can you check if the node has itself as a persistent peer? This is a known issue, https://github.com/tendermint/tendermint/issues/3716. To fix it we need to rewrite some of the p2p stack and we are working on getting around to this.

**Comment by Anjana-Prabhakar** [comment] 2020-08-06 07:39
Thank you Marko.

**Comment by erikgrinaker** [comment] 2020-08-06 08:39
Yes, this is a dupe of #3716. The error is annoying but harmless, I believe.

**Closed by erikgrinaker** 2020-08-06 08:39 UTC
