### ISSUE TITLE
Per package log levels

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#358] opened 2017-01-11 15:57 UTC
Need to be able to eg. enable debug on the consensus without getting swamped by p2p debug messages

**Comment by ethanfrey** [comment] 2017-01-11 16:11
I agree very much, and the point that tendermint needs some work on how to configure the logging system has come up a few other times.  Maybe we could collect some desires here, so whenever this gets implemented, it makes everyone happy.

Some ideas to get started:
  * Ability to set log levels at runtime (not compile time).  Either through commandline flags or per config file (or both)
  * Setting log levels per module (this request)
  * Optionally sending log.Error to a error reporting service (eg. rollbar), again configured at runtime

I have done points 1 and 3 before using logrus.  And really liked the error reporting service for running in production (you only read logs AFTER users complain).  I don't think it has any concept of per-module levels though.

I found this module that does per module logging levels at runtime: https://godoc.org/github.com/juju/loggo#ConfigureLoggers

But I have zero experience with it. An observation not a suggestion.

And of course, no conversation is complete without Dave Cheney's view: https://dave.cheney.net/2015/11/05/lets-talk-about-logging  I don't agree 100% but it does raise some good points.

**Comment by ethanfrey** [comment] 2017-01-11 16:15
I personally also have come to like structured logging (as parsable json or key-value pairs).  You can output to stdout, and then other system tools can feed it an elk stack or similar.  This is great for insights on a production system.  Maybe one day tendermint will be a self-maintaining, self-healing, self-debugging system. But we are still far from there.

I don't know if anyone else has experience and likes/dislikes structured logging.

**Comment by jaekwon** [comment] 2017-01-11 17:09
I don't mind structured logging, but I also suspect that our logs could be more visually appealing, using ANSII colors & spacing to create non-structured but more human-friendly output.  I think it would help us w/ consensus bugs and so on.  But TBH I have no idea how to get started with it.

Maybe what we need is more structured structured-logging, where we use sub-loggers more often (i.e. inheriting a parent's properties, rather than setting them by hand each time as we do currently), and sticking to conventions, such that we can parse and construct a more visually appealing log.

On a separate note, I also think we ought to get away from our <subdir>/log.go static log system and allow dynamic log setting, so that we can create multiple consensus instances in the same process and have the log go to separate places.  Hmm, or maybe we should be solving this w/ a log property & structured-log filtering (e.g. filter logs by consensus instance).

All ears.

**Comment by akalyaev** [comment] 2017-01-12 16:22
I'll add my 2 coins here too. It may be a good idea to think about contexts https://www.cockroachlabs.com/blog/enriching-log-messages-using-go-contexts/, which will help us to group log messages (useful for `grep`) and trace operations spanning multiple nodes. Right now I believe we only have `module=M`.

**Comment by ebuchman** [comment] 2017-01-12 16:32
> so that we can create multiple consensus instances in the same process and have the log go to separate places

This is becoming essential. Debugging reactor_tests.go is very difficult without it.

**Comment by ethanfrey** [comment] 2017-01-12 16:45
This is quite cool as well: https://github.com/spacemonkeygo/monkit

Pass context.Context as the first argument to all calls... and you get free call graphs and timings of the live system.

And this is a nice point:
https://github.com/spacemonkeygo/monkit#aside-about-contexts

This is mainly for monitoring. But once you have this info, you could also use that same Context to fill out the log messages.

**Comment by ethanfrey** [comment] 2017-01-12 16:48
The reason I like dumping logs into something like ELK, is it lets you add eg. RequestID to the logger and then quickly search for all log messages on one requestID (with optionally other filters).  Kinda like grep but easier on the eyes. But in any case, you need to attach those requestIDs as well as modulename to the logs to filter them well.

**Comment by akalyaev** [comment] 2017-01-12 16:50
Yeah, but adding `ctx Context` everywhere requires a huge effort

**Comment by ethanfrey** [comment] 2017-01-12 17:02
PITA - yes 
necessary to trace requests in distributed systems - yes

From the cockroachdb article...

"""
To address these shortcomings, we decided to pass the information that we want to associate with log messages through a context.Context. Note that plumbing Contexts throughout our code is necessary regardless in order to be able to correlate operations spanning multiple nodes (distributed tracing). So the solution is to embed a chain of logging tags into Contexts (via an API that appends a log tag to a context) and to always pass a context when logging a message; the logging library inspects the tags embedded in the context and includes them in the message.
"""

I think it is a lot of plumbing and must be done post-0.8, but come good contextual plumbing, logging, and monitoring will increase stability and transparency and help debugging and development enormously in the long-run.

**Comment by melekes** [comment] 2017-03-14 16:08
cockroachdb is moving to structured logging.

## Step 1 - Define an interface

We could start by **agreeing on the common interface for any logger**, which all our existing and future libraries should obey.

Current interface:
```go
type Logger interface {
	Debug(msg string, ctx ...interface{})
	Info(msg string, ctx ...interface{})
	Warn(msg string, ctx ...interface{})
	Error(msg string, ctx ...interface{})
	Crit(msg string, ctx ...interface{})
}
```

I very much agree with Dave Cheney on the point that we really need only `Info` and `Debug`. On the other hand, I don't want to sacrifice visual side of warning (yellow), error (red) errors (for terminals).

`go-kit` https://github.com/go-kit/kit/tree/master/log goes even further and defines an interface with one method:
```go
type Logger interface {
    Log(keyvals ...interface{}) error
}
```
See [The Hunt for a Logger Interface](https://go-talks.appspot.com/github.com/ChrisHines/talks/structured-logging/structured-logging.slide)

In our case, I think it is better to stick with the current interface. The only thing to do is to **add it to the `go-logger` library**.

## Step 2 - move away from static configuration (`log.go`)

In `log.go` file we could define a method `SetLogger`, which could be called to change the default logger. For example, `node.go` could modify all the loggers it uses like that:

```go
# consensus/log.go
import (
  log "github.com/tendermint/go-logger"
)

var logger = log.NewLogfmtLogger(log.NewSyncWriter(os.Stderr))

func SetLogger(logger *log.Logger) {
  logger = logger
}

# node.go
logger = log.NewLogfmtLogger(log.NewSyncWriter(os.Stderr))
consensus.SetLogger(log.With(logger, "module", "consensus"))
```

## Embed logger into structs (only a few)

In cases where we have multiple instances of some struct running (e.g. consensus), it probably makes sense to have logger as a struct field.

```go
type ConsensusReactor struct {
  logger log.Logger
}

NewConsensusReactor(log.With(logger, "ID", "77"))
```

## Move away from log15

Because it is slow and has too many features.

Once we've done with 1 and 2, in `go-logger` we can simply define an adapter for say https://github.com/uber-go/zap (or https://github.com/go-kit/kit/tree/master/log)

```go
func NewZapLogger() ZapLogger {
  logger, _ := NewProduction()
  return logger.Sugar()
}

func (logger *ZapLogger) Info(msg string, ctx ...interface{}) Logger {
  logger.Infow(msg, ctx...)
}
```

Resources:
- [Structured Logging and You, in 5 minute](https://docs.google.com/presentation/d/1KciJt-groC22smVgCg4TfJXqCUAA6D4c6NRdKBIkIHM/edit#slide=id.p)

**Comment by ethanfrey** [comment] 2017-03-14 16:19
Embed logger into structs :+1: Yes. Logger is not a global.  I think it should tied to the processing struct, or the data being processed depending on the architecture.

Define an interface.  What about adding a WithField method for structured logging? It could be as simple as:

```Go
type Logger interface {
	Debug(msg string, ctx ...interface{})
	Info(msg string, ctx ...interface{})
	Error(msg string, ctx ...interface{})
	WithField(key string, value interface{}) Logger
}
```

I agree with info and debug levels.  However, error level is very nice *if* you have some integration to an error reporting service to capture the stack trace.  In the last two projects outside of tendermint I ended up using logrus, and adding github.com/heroku/rollrus as a handler, so all log.Error() calls would also end up storing the stack trace on rollbar and notifying me. There are also integrations with bugsnag and other error reporting services.  This can be set up in the main.go without changing anything else in the rest of the program.

Yes, "just read the log files".  Sure, but when you have production deploy with many instances, and want pro-active notifications.... Simple as:

```
	rollbar := rollrus.NewHook(*rollbarKey, *rollbarEnv)
	l := logrus.New()
	l.Hooks.Add(rollbar)
```

**Comment by silasdavis** [comment] 2017-03-14 18:22
You might be interested in the approach I ended up taking in eris-db. We want to capture all our dependency logs, and also the logging architecture may be used for more general event logging. I ended up centring the implementation around go-kit's logger interface (https://github.com/go-kit/kit/tree/master/log):

```go
type Logger interface {
    Log(keyvals ...interface{}) error
}
```

I was sold on this being a good blend of providing structured logging, being composable, and having a somewhat minimalistic approach. It is ultimately a very similar interface to `Handler` of log15. Sounds like you are considering something similar.

The system-wide logging interface for eris-db is defined at:

https://github.com/silasdavis/eris-db/blob/logging/logging/types/info_trace_logger.go

I almost wanted to avoid having logging levels, but in the end decided on a 'quiet' and a 'noisy' channel. They are both fed in order from a non-blocking ring buffered channel (so that log processing will not directly affect execution. The idea is that a lot of machine-consumable output might end up on the 'Trace' channel, wheras messages pertinent to a human go on 'Info'. It's pretty similar in essence to 'Info' and 'Debug'.

To be honest in the process of wiring up with other loggers I found log15 to be one of the best designed. You say:

>Because it is slow and has too many features.

Really? Is this based of a benchmark. If you really want speed you might consider: https://github.com/uber-go/zap. It looks like you are settling on an interface pretty similar to log15. It might be a nice fit for your needs. Perhaps you could just wrap log15 with your more minimal interface.

As for the features, I don't really see that you pay for what you don't use, and the more exotic features are packaged up as handlers.

Otherwise great to see removing of global loggers. A loggers is a dependency for various objects and should be treated as such. I hope it will be possible to pass in a logger instance to a node through the public constructor.

>I very much agree with Dave Cheney on the point that we really need only Info and Debug. On the other hand, I don't want to sacrifice visual side of warning (yellow), error (red) errors (for terminals).

I tend to agree too, though then saying that you still want to have warnings and errors rather contradicts this. What are the semantics that yellow and red are expressing? Perhaps warning (you should consider reconfiguring your node) and error are good enough or perhaps you could just tag a structured message with codings representing more specific types of note-worthy event. In either case you don't really need a separate method on your logging interface that everyone needs to implement, you could just establish conventions for keys that you can use for coding messages. I have some centralised conventions:

https://github.com/silasdavis/eris-db/blob/logging/logging/structure/structure.go#L6-L26

https://github.com/silasdavis/eris-db/blob/logging/logging/convention.go

That are provided statically alongside the schemaless `Logger` interface rather than on the interface itself.

If you define a Tendermint specific interface, and use something like go-kit/log underneath (as you propose convering go-logger to) I think it would be nicer to just ditch go-logger create you application specific interface and provide configurability/pluggability by accepting go-kit loggers.

>Maybe what we need is more structured structured-logging, where we use sub-loggers more often (i.e. inheriting a parent's properties, rather than setting them by hand each time as we do currently), and sticking to conventions, such that we can parse and construct a more visually appealing log.

I agree. go-kit/log 'context' provides a good way of doing this: https://github.com/go-kit/kit/blob/master/log/log.go#L95. It also provides lazy evaluation of some values.

**Comment by ethanfrey** [comment] 2017-03-14 19:37
@silasdavis Thank you for the very insightful input.

I have one question for you based on error reporting.  I really find such a service invaluable in production, self-hosted or SaaS (I used sentry for a long time in python world, tended SaaS with go).

This does not have to be tied to a logger, but since everyone seems to `log.Error`, it is a great place to catch them without adding that logic and explicit dependency to every object.

What is your approach for dealing with error reporting? I'd love to see another approach.

**Comment by silasdavis** [comment] 2017-03-15 09:38
Dave Cheney in his blog post referenced earlier wants to advance the view that if an error is handled it is by definition not an error. I think this is a little extreme. However I do think that once you have handled an error you are sort of accepting that the post-error state of your system is meaningful, recoverable, and not pointless (if it is in a degenerate state then I think the error should be fatal and should trigger some out-of-band recovery like restarting the server). Therefore I think that what is an error, or rather what ought to be sent to an error reporting channel, is more in the eye of the beholder than something that the author of the code knows before they have compiled.

My assumption would also be that we are shipping our logs to some system like graylog, syslog, papertrail (I'm supporting these in eris-db: https://github.com/silasdavis/eris-db/blob/logging/logging/config/sinks.go though I know some people think you should just write to stdout and shipping logs is an ops issue...). So I would rather annotate the 'error' logline with as much detail as possible and let the consumer decide how to filter and route errorful log messages. If there is Go generated error I'd put it under an 'error' key with as much structured metadata as possible:

```go
logger.Log("message", "Couldn't deserialise incoming BlockPart", "error", err, "validator_sync_array", vsArray, "state_code", statecodes.ValidatorDesync)
```

In this contrived example I'm imagining an enum-like `statecodes` package (kind of a bad name I know) where you could list certain 'exceptional' codes. `"error"` would hold the Go error. As a consumer I could choose to route anything with an error tag to my error reporting, or perhaps better, anything with a state_code tag, or if I was only interested in `ValidatorDesync`s then just those.

I think this is inversion makes sense for production, perhaps less useful for console output. For that though you should be able to provide a custom formatter that makes assumptions about what is probably an interesting error for a Tendermint app developer...

**Comment by ethanfrey** [comment] 2017-03-15 09:59
Interesting... I have to reflect a bit more, but a nice point.

I used ELK for logging, found it much nicer than papertrail.  And I think graylog is supposed to be at least as nice as ELK, if not better.

To make a system resilient, it must not just recover from bad states as well as possible, if should also alert the developers when poor conditions happen, so they can fix the root causes (eg. if 1% of the db connections are breaking, we can simply retry, but then 2%, 3%.... it is nice to recover AND notify the devs that there is some condition that should not happen, so they can investigate.

And I have gotten so spoiled with stack traces that a simple "ERROR: db connect failed" line just drives me nuts (where? what? who? when?).  I guess you are saying the consumer can just ship the entire error (with stack trace, if coming from pkg/errors) to rollbar, bugsnag, sentry, etc?

In the end, I guess the two proposals are just different syntax for the same functionality.  Let me call them elog and slog for the two interfaces we proposed:

```Go
elog.WithField(key, value).Info(msg)
slog.Log(key, value, "message", msg)

elog.WithField(key, value).Debug(msg)
slog.Log(key, value, "message", msg, "debug", true)

//elog.WithField(key, value).WithError(err).Error(msg)
elog.WithField(key, value).WithError(err).Info(msg)
slog.Log(key, value, "message", msg, "error", err)
```

If error state is defined by the presence of the "error" field, then there is no more need for explicit Error vs Info levels.  Just Debug/Trace and Info. I'm starting to like your approach more ;) And if they can easily be translated from one format to the other, that means, the logger could use your proposed interface and have logrus underneath, or use my proposal and have go-kit underneath.

**Comment by silasdavis** [comment] 2017-03-15 12:34
I'm capturing a reduced stack trace (filename only) with every logline: https://github.com/silasdavis/eris-db/blob/logging/logging/metadata.go#L32 

There is a bit of a tradeoff with verbosity here, but the logging is configurable and you can define a prune filter to remove it (the combination of the sink graph and defining a formatter should support most (all?) output cases is my hope).

I think it's more flexible to keep the interface small so that others can easily implement and provide 'extension methods' that are non-instance methods that take an instance of the logger (e.g. https://github.com/silasdavis/eris-db/blob/logging/logging/convention.go#L28). I like the fluent syntax but its a bit onerous if someone wants to implement a logger for them to have to implement that stuff (generic as it is). Another option is to have a wrapper:

```go
type FluentLogger struct {
    logger kitlog.Logger
}

func (fl *FluentLogger) WithField(key, value interface{}) {
   ...
}
```

Then callers who want the fluent (or another) interface just wrap the Logger themselves.

**Comment by adrianbrink** [comment] 2017-05-08 09:37
@melekes Isn't this solved by your new logging infrastructure?

**Comment by melekes** [comment] 2017-05-08 09:45
Yes, it is. This is the issue where we've gathered the specs for implementation.

**Comment by adrianbrink** [comment] 2017-05-08 10:04
@melekes I'm closing it since it has been merged. :-) If you want to keep it around just reopen it

**Closed by adrianbrink** 2017-05-08 10:04 UTC
Labels: enhancement
