### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by ArvonHuang** [tendermint/tendermint#4064] opened 2019-10-17 00:43 UTC
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.20

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
mideaBill 

**Environment**:
- **OS**  linux
- **Install tools**: docker
- **Others**:

**What happened**:
linux memory goes up to 100%

**Have you tried the latest version**: yes/no
no 

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

`759.42MB 96.61% 96.61%   759.92MB 96.67%  github.com/tendermint/tendermint/libs/pubsub/query.(*QueryParser).Init /home/bill/gopath/src/github.com/tendermint/tendermint/libs/pubsub/query/query.peg.go`

**Comment by ArvonHuang** [comment] 2019-10-17 01:03
will tendermint support go module in the soon future

**Comment by kwunyeung** [comment] 2019-10-17 13:42
I think this is related. https://github.com/cosmos/gaia/issues/160

Not sure if it is a memory leak but it uses a lot of memory. This happens when `gaiad` starts and connects peers the first time and it uses around 2.4G or memory. After restart, it uses less then 300M for a long time. I have prepared the memory profiles before and after restarting `gaiad`.

https://storage.cloud.google.com/cosmoshub-data-backup/before-restart.mprof
https://storage.cloud.google.com/cosmoshub-data-backup/after-restart.mprof

[mem-prof-before-after.pdf](https://github.com/tendermint/tendermint/files/3739558/mem-prof-before-after.pdf)

**Comment by melekes** [comment] 2019-10-17 15:11
@kwunyeung what Tendermint version were u using?

**Comment by melekes** [comment] 2019-10-17 15:24
the memory profile you posted only accounts for ~15MB. we won't be able to deduce anything from it. Ideally we'd have a report showing 2.4G

**Comment by melekes** [comment] 2019-10-17 15:56
> https://storage.cloud.google.com/cosmoshub-data-backup/before-restart.mprof

403 error

**Comment by kwunyeung** [comment] 2019-10-17 16:21
Sorry. I forgot to update the permission. Please try again.

I've uploaded to Google Drive just in case.

https://drive.google.com/open?id=1nIegalq80Q27ddR1uWf2hqUfZ3YKndB1

https://drive.google.com/open?id=1vk-qoVQcNoObHwYeOdyhDg95DCuuYS03

**Comment by HaoyangLiu** [comment] 2019-10-23 12:58
I think the out of memory issue in [cosmos/gaia#160](https://github.com/cosmos/gaia/issues/160) is caused by too small machine memory. I created node to join in cosmoshub-3-testnet and the memory of my machine is 8G. My node worked well. I tried to reset it and started it again, it always worked well. 

Besides, if you start a node with incorrect validator consensus address prefix, then you node will encounter consensus failure. But your node won't be shutdown automatically. However, node memory usage will increase along with time. This is because consensus msg will be continuously synced to your node and the msgs can't be processed any more, then the consensus msg queue will be full, then more and more goroutine will get stucked.

**Comment by ArvonHuang** [comment] 2019-10-31 03:18
> Hey! I am afraid `0.20` version is outdated and no longer supported. Please upgrade to newer versions of Tendermint (0.32). Thanks!

@melekes  I have run `0.20` version  in prod env. There is any ways that i can migrate? Furthermore, The OOM code is referred to `github.com/tendermint/tendermint/libs/pubsub/query.(*QueryParser).Init /home/bill/gopath/src/github.com/tendermint/tendermint/libs/pubsub/query/query.peg.go`
and i found that compared with the `0.32` version, the `0.20` version' query.peg.go does not change. So i am afraid even if i upgrade the OOM problem still exist.

**Comment by kwunyeung** [comment] 2019-11-02 06:09
> I created node to join in cosmoshub-3-testnet and the memory of my machine is 8G.

This is what I'm concerning. What if many of the public nodes have not enough memory now? The network may not start during the upgrade as the votes from the validator nodes can't be broadcasted.

**Comment by melekes** [comment] 2019-11-03 16:05
>  i found that compared with the 0.32 version, the 0.20 version' query.peg.go does not change

It does not matter because the problem is **not with the Query object itself**, the problem is that the caller who's creating them (Query objects) was retaining them in memory! There were quite a few memory  leaks since v0.20, but they all have been fixed.

**Comment by melekes** [comment] 2020-01-28 11:39
@kwunyeung do you still experiencing this?

**Comment by kwunyeung** [comment] 2020-02-16 17:32
@melekes no I don't.

**Comment by melekes** [comment] 2020-03-12 15:37
Cool. Given @ArvonHuang was using a really old version of Tendermint (0.20) and @kwunyeung response above, I think it's fine to close this issue. That said, I suspect there's still a memory leak somewhere present in the current (0.33.2) version. We'll try to gather more info and investigave.

**Closed by melekes** 2020-03-12 15:37 UTC
Labels: P:High, T:bug
