### ISSUE TITLE
validator key rotation feature

### ISSUE THREAD

**Issue by dlguddus** [tendermint/tendermint#4060] opened 2019-10-15 05:24 UTC
1. problem definition

- validators cannot rotate its consensus key
- validators cannot rotate its validator operator control key(wallet key)

2. new feature

- validators can rotate its consensus key by transaction
- validators can rotate its validator operator control key(wallet key) by transaction

3. things to discuss

- lots of location in current codebase should be revised to allow rotation of keys
- blockchain should store such mapping of each key
- mapping storage needs consideration of pruning strategy, related to slashing module

4. B-Harvest will tackle this issue after enough communication with tendermint devs.

**Comment by marbar3778** [comment] 2019-10-15 08:09
this is a duplicate of #1136, it would make sense to have the continued discussion in that issue as it already holds quite a bit of discussion.

**Closed by marbar3778** 2019-10-15 08:09 UTC
