### ISSUE TITLE
Use TUF to securely distribute the binaries

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#837] opened 2017-11-10 18:34 UTC
https://theupdateframework.github.io/

TUF includes a robust, role-based signature system and protects against many attacks including downgrades and CDN compromise.

tool: https://github.com/flynn/go-tuf
example: https://flynn.io/docs/development#the-update-framework-(tuf)
spec: https://github.com/theupdateframework/specification/blob/master/tuf-spec.md

**Comment by adrianbrink** [comment] 2017-11-11 16:22
This ties in to the talk by Zaki about how the Tor projects delivers binaries.

The essence:
* deterministic builds happen on Jenkins
* some core devs build the same source code
* the devs then sign the bits of the binary and upload that signature to Jenkins
* Jenkins now constructs an M out of N signature if the signatures match

This protects us against a compromised Jenkins and holds the devs accountable to the binaries they ship. 

@zmanian @Greg-Szabo

**Comment by zmanian** [comment] 2017-11-11 16:27
It would be good is someone can build Tendermint using the techniques from Fillipo's post and see if they run into any issues
https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/

**Comment by adrianbrink** [comment] 2018-01-08 12:05
@Greg-Szabo FYI, since you are currently working on this.

**Comment by Greg-Szabo** [comment] 2018-01-10 16:42
I went through the blog post @zmanian  mentioned and got down and built a few binaries using go 1.9.2.
Unfortunately the determinism in go (at least officialy) means that you can build the binary twice in the same environment and get the same results. You still need to pin down the details of the environment to be able to reproduce the binary on other machines. Here're a few of the findings (already discussed on meetings and in the `Makefile` improvements) that are not fully covered in the blogpost:
1. Trimpath can only be used once. The original intent of trimpath was to remove _most_ of the $GOPATH entries from the binary but (at leat on 1.9.2) it fails and the string is still present in the binary. (Although only in one place compared to the tens of places before using `-trimpath`.) It still doesn't resolve that $GOROOT has to match too, as it's pointed out in the blog.
2. The C linker dependency boils down to one flag: `debug-prefix-map`. It's actually two flags but the golang source assumes that both are available if one is available. The new information is that `muslc` in the Alpine linux distribution doesn't support that flag. I don't advise building using Alpine, although Jae's personal experiments seemed to disagree with this. Dragons, beware, indeed.

I wrote `Makefile` checks to advise if a build is going to be deterministic based on agreements we can/should make but they were unfortunately reverted. We should still have those agreements and I think if we match the environment of the official golang docker container, we should be good. These are the important (pinned down) parameters there: (this is what I propose we agree on)
1. go version 1.9.2 (specifically, until the next tendermint version, when we can upgrade if needed)
2. `debug-prefix-map` flag supported for the linker (glibc supports it, but we shouldn't require glibc specifically, to keep it open for variety)
3. GOROOT=/usr/local/go
4. GOPATH=/go
5. `-trimpath $GOPATH` added (in the future it might be enough)
6. Git version commit (injected with `-X`) is 8 characters long (`git rev parse --short=8`). This is important because git v2 (in docker) uses 8 by default whereas git v1 (CentOS release by default) uses 7, which makes the binary different.

**Comment by jackzampolin** [comment] 2019-06-21 15:52
@alessio is working on reproducible builds and binary distribution will be taken care of at an org wide level. Closing this issue as out of scope for this repo.

**Closed by jackzampolin** 2019-06-21 15:52 UTC
Labels: distribution, question
