### ISSUE TITLE
clean deps to minimize client binary size

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1182] opened 2018-02-03 03:09 UTC
We want to minimize how much code a client binary has to compile so we can run on small devices and so the code remains easily auditable.

**Comment by ValarDragon** [comment] 2018-08-05 22:10
I don't think the amount of deps we have is an issue for small devices which it makes sense to be compiling from. Golang will only compile the modules we are actually using.

Dep will download the entire repo, but the space taken by `tendermint/tendermint` with all of its vendors (plus overhead due to me having git history + stashes) is `61.5 MB`. That seems fine for expecting someone who wants to compile from source to download.

**Comment by marbar3778** [comment] 2019-06-21 10:20
No longer using dep, @melekes can you close this issue

**Comment by melekes** [comment] 2019-06-21 10:38
> No longer using dep

I think the issue is we're importing a lot of stuff, not that there's something wrong with dep/go modules.

**Comment by marbar3778** [comment] 2019-06-21 10:47
Seems like everything is being used within the go.mod file. Is the intention here to bring some of these packages into tendermint so they aren't being imported? there a few indirect imports.

**Comment by marbar3778** [comment] 2019-06-21 11:26
The current size of the binary is 28mb when I add `-s -w` i get 23, is this small enough for a binary, or is our aim smaller?

**Comment by marbar3778** [comment] 2019-06-24 14:46
Closing this issue as the most recent release of tendermint (v0.32.0) binary size is 23 mb, please reopen if you believe we should work on reducing it more.

**Closed by marbar3778** 2019-06-24 14:46 UTC
Labels: proposal
