### ISSUE TITLE
Reason for using Mutex instead of RWMutex in querier

### ISSUE THREAD

**Issue by YunSuk-Yeo** [tendermint/tendermint#6048] opened 2021-02-04 08:54 UTC
Is there any reason using just Mutex instead of RWMutex? 

Query speed will be super faster with RWMutex (read lock on query and write lock on other parts), 

https://github.com/tendermint/tendermint/blob/9b6d6a3ad0ad4a62caa50fb4939757f035f500ae/abci/client/local_client.go#L18

If we can ensure these queries are not doing write operation, we can change them to use read lock and can support concurrent queries.

* https://github.com/tendermint/tendermint/blob/9b6d6a3ad0ad4a62caa50fb4939757f035f500ae/abci/client/local_client.go#L246-L251

* https://github.com/tendermint/tendermint/blob/9b6d6a3ad0ad4a62caa50fb4939757f035f500ae/abci/client/local_client.go#L100-L102

**Comment by melekes** [comment] 2021-02-08 06:48
No reason. Do you want to make some benchmarks and show us the difference?

**Comment by hanjukim** [comment] 2021-02-08 10:48
with Mutex, 16% (0.49/3.02) of total time spent in Wait:
https://gist.github.com/hanjukim/644842107beba4a619b3f56f2c9a62c8/raw/659d50a42068cfa107e10724c69487043a0e7cf4/pprof_block_Mutex.svg

with RWMutex:
https://gist.githubusercontent.com/hanjukim/644842107beba4a619b3f56f2c9a62c8/raw/659d50a42068cfa107e10724c69487043a0e7cf4/pprof_block_RWMutex.svg

**Comment by melekes** [comment] 2021-02-08 16:11
cool! do you want to submit a PR?

**Comment by hanjukim** [comment] 2021-02-09 06:27
> cool! do you want to submit a PR?

We will make a PR once it's stable for real

**Comment by RiccardoM** [comment] 2021-02-23 06:40
@hanjukim Do you have any update on this? It looks like this is now causing significant slowness inside the entire Cosmos Hub as well now. If you want, I can open a PR implementing your solution if you don't have time

**Comment by melekes** [comment] 2021-02-23 12:16
It may be possible to completely remove `mtx` from `Info` and `Query` calls.

**Comment by alexanderbez** [comment] 2021-02-23 14:43
Curious why `Info` and `Query` need to be serialized?

**Comment by hanjukim** [comment] 2021-02-24 03:44
> @hanjukim Do you have any update on this? It looks like this is now causing significant slowness inside the entire Cosmos Hub as well now. If you want, I can open a PR implementing your solution if you don't have time

Yes, we have some progress here.

1. We've successfully applied RWMutex to our public nodes, but we had to make some tweaks for cosmwasm module to use write lock. You can see some changes in https://github.com/terra-project/tendermint/blob/rw-lock3/abci/client/local_client.go
2. Changing Mutex made some improvements. However,
3. You can only have one iterator at a time for accessing LevelDB which means it has to be synchronous and it blocks everything until it finishes.
4. There is a major blocker function in the staking module of Cosmos SDK: https://github.com/terra-project/cosmos-sdk/blob/v0.39.2/x/staking/keeper/delegation.go#L52-L65
5. Since changes in the KV changes the state, we couldn't find easy way to make it compatible without hard/soft forking. (i.e. making it able to query with height parameter)
6. We've decided to disable the blocker endpoints for public node until we have the solution.

**Comment by hanjukim** [comment] 2021-02-24 04:37
One more thing:

We have a special project called [mantle-sdk](https://github.com/terra-project/mantle-sdk), and [mantle](https://github.com/terra-project/mantle) that wraps over the Tendermint and the CosmosSDK and serves data via GraphQL.
We tried to touch same blocker path `custom/staking/validatorDelegations` to Mantle server, and the result is stunning:

```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    20.18ms   48.73ms 519.16ms   96.84%
    Req/Sec     1.24k   176.31     1.54k    84.50%
  49384 requests in 10.03s, 45.26MB read
Requests/sec:   4923.65
```

We are guessing from this result that it is probably a problem related to IAVL tree. (Huge amount of rebalancing between blocks?)

**Comment by alexanderbez** [comment] 2021-02-24 15:23
Yeah sounds like it!

**Comment by kjessec** [comment] 2021-02-26 09:11
We found out that this could potentially lead to cosmos application to panic.

https://github.com/cosmos/cosmos-sdk/blob/v0.39.1/x/staking/keeper/validator.go#L45

In `GetValidator` function cosmos-sdk caches validator lists in a map, and as we might already know, in case of golang concurrent writes to a map would lead to panic.

Technically this is not related to tendermint itself, but given most applications are using Tendermint+cosmos stack, we should be careful before merging this.

FYI Above map cache thing is removed in current master of cosmos-sdk (stargate) -- maybe safe in the future?

**Comment by RiccardoM** [comment] 2021-02-26 09:28
> FYI Above map cache thing is removed in current master of cosmos-sdk (stargate) -- maybe safe in the future?

I can confirm that this has been removed with cosmos/cosmos-sdk#8546 as it was making gRPC queries crash and a lot slower anyway (cosmos/cosmos-sdk#8545). I don't think it will ever return as it was a tricky hack to avoid high deserialization costs due to Amino (which is now gone). For this reason, it shouldn't be considered an issue anymore.

**Comment by reuvenpo** [comment] 2021-03-25 17:27
Has there been any progress on this issue since last month?
I'd love to see this work merged and propagate upstream to the next Cosmos SDK version if the improvements are so significant :)

**Comment by tychoish** [comment] 2021-04-05 19:49
https://github.com/tendermint/tendermint/commit/1c4dbe30d40bb4c1dc59a2247d5113b78702a014

I believe this is covered in the above change (sorry for not annotating the commit message appropriately!) I think the current view is that that while changing the locking strategy will help relieve some contention, but a lot of the performance bottlenecks are rooted deeper in the client implementations which changing locks won't help with that part.

**Closed** 2021-04-05 20:03 UTC
Labels: T:perf, T:question
