### ISSUE TITLE
 get_vendor_deps

### ISSUE THREAD

**Issue by ying2025** [tendermint/tendermint#1658] opened 2018-05-31 04:24 UTC
sudo make get_vendor_deps
--> Running dep
dep: WARNING: Unknown field in manifest: prune

**Comment by ValarDragon** [comment] 2018-05-31 04:33
Is this on master? I'm not getting the same error. Did you run make `get_tools` first?

**Comment by ying2025** [comment] 2018-05-31 06:18
I just run make get_tools

**Comment by ying2025** [comment] 2018-05-31 06:18
![image](https://user-images.githubusercontent.com/28092539/40764991-8331b960-64dd-11e8-84fa-e8cbaa7c90da.png)

**Comment by ying2025** [comment] 2018-05-31 06:19
@ubuntu:~/go/src/github.com/tendermint$ make get_vendor_deps
--> Running dep
dep: WARNING: Unknown field in manifest: prune
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export github.com/davecgh/go-spew: unable to update repository: : command failed: [git fetch --tags --prune origin]: exit status 255
Makefile:51: recipe for target 'get_vendor_deps' failed
make: *** [get_vendor_deps] Error 1

**Comment by ying2025** [comment] 2018-05-31 06:47
@ubuntu:~/go/src/github.com/tendermint$ make install
CGO_ENABLED=0 go install -ldflags "-X github.com/tendermint/tendermint/version.GitCommit=`git rev-parse --short=8 HEAD`" -tags 'tendermint' ./cmd/tendermint
fatal: not a git repository (or any of the parent directories): .git
cmd/tendermint/main.go:9:2: cannot find package "github.com/tendermint/tendermint/cmd/tendermint/commands" in any of:
	/usr/src/github.com/tendermint/tendermint/cmd/tendermint/commands (from $GOROOT)
	/home/zhr/go/src/github.com/tendermint/tendermint/cmd/tendermint/commands (from $GOPATH)
cmd/tendermint/main.go:10:2: cannot find package "github.com/tendermint/tendermint/config" in any of:
	/usr/src/github.com/tendermint/tendermint/config (from $GOROOT)
	/home/zhr/go/src/github.com/tendermint/tendermint/config (from $GOPATH)
cmd/tendermint/main.go:11:2: cannot find package "github.com/tendermint/tendermint/node" in any of:
	/usr/src/github.com/tendermint/tendermint/node (from $GOROOT)
	/home/zhr/go/src/github.com/tendermint/tendermint/node (from $GOPATH)
cmd/tendermint/main.go:7:2: cannot find package "github.com/tendermint/tmlibs/cli" in any of:
	/usr/src/github.com/tendermint/tmlibs/cli (from $GOROOT)
	/home/zhr/go/src/github.com/tendermint/tmlibs/cli (from $GOPATH)
Makefile:23: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by zramsay** [comment] 2018-05-31 11:49
duplicate of #1660. please try to stick to one Github issue per issue

**Closed by zramsay** 2018-05-31 11:49 UTC
