### ISSUE TITLE
Timed out waiting for tx to be included in a block, getting error again and again after some blocks created 

### ISSUE THREAD

**Issue by skdjango001** [tendermint/tendermint#4928] opened 2020-05-31 09:13 UTC
Hi i am hitting this error again and again while i am trying to resolve this issue, i can't so is there any one who help me out of this 
Tendermint version: 0.32

```json
{
  "jsonrpc": "2.0",
  "id": "",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "Timed out waiting for tx to be included in a block"
  }
}
```

```
E[2020-05-31|12:43:17.347] Error on broadcastTxCommit                   module=rpc err="Timed out waiting for tx to be included in a block"
E[2020-05-31|12:43:17.736] Error on broadcastTxCommit                   module=rpc err="Timed out waiting for tx to be included in a block"
E[2020-05-31|12:43:17.764] Error on broadcastTxCommit                   module=rpc err="Timed out waiting for tx to be included in a block"
E[2020-05-31|12:43:19.317] Error on broadcastTxCommit                   module=rpc err="Tx already exists in cache"
E[2020-05-31|12:43:19.446] Error on broadcastTxCommit                   module=rpc err="Tx already exists in cache"
E[2020-05-31|12:43:19.501] Error on broadcastTxCommit                   module=rpc err="Tx already exists in cache"
E[2020-05-31|12:43:19.738] Error on broadcastTxCommit                   module=rpc err="Tx already exists in cache"
E[2020-05-31|12:43:19.766] Error on broadcastTxCommit                   module=rpc err="Tx already exists in cache
```

any help is much appreciated @melekes @ValarDragon @ebuchman @erikgrinaker

**Comment by melekes** [comment] 2020-06-01 05:41
Could you paste logs from Tendermint instance? What's the average block time? Is transaction sitting in the mempool?

> https://docs.tendermint.com/master/rpc/#/Tx/broadcast_tx_commit

> IMPORTANT: use only for testing and development. In production, use BroadcastTxSync or BroadcastTxAsync. You can subscribe for the transaction result using JSONRPC via a websocket. See https://docs.tendermint.com/master/app-dev/subscribing-to-events-via-websocket.html

> Timed out waiting for tx to be included in a block

that can happen when block is not being produced for more than a few seconds.

> Tx already exists in cache

https://docs.tendermint.com/master/app-dev/app-development.html#replay-protection

**Comment by skdjango001** [comment] 2020-06-01 06:01
Hi @melekes  
![Screenshot from 2020-05-31 14-49-56](https://user-images.githubusercontent.com/49150428/83380338-536d1d00-a3fb-11ea-8542-aeacd8927651.png)
This is last block which i am getting

**Comment by melekes** [comment] 2020-06-01 06:10
> `wrong Block.Header.LastResultsHash`

Did you reset the state? Looks like LastResultsHash does not match with expected one.

You might want to reset everything to 0:

```sh
tendermint unsafe_reset_all
```

**Comment by skdjango001** [comment] 2020-06-01 06:21
yes i did at the time of mempool size change

**Comment by skdjango001** [comment] 2020-06-01 06:23
and This is my config.toml file which i am using 
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### main base config options #####

# TCP or UNIX socket address of the ABCI application,
# or the name of an ABCI application compiled in with the Tendermint binary
proxy_app = "tcp://127.0.0.1:20058"

# A custom human readable name for this node
moniker = "Test_Node0"

# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true

# Database backend: leveldb | memdb | cleveldb
db_backend = "cleveldb"

# Database directory
db_dir = "data"

# Output level for logging, including package level options
log_level = "main:info,state:info,*:error"

# Output format: 'plain' (colored text) or 'json'
log_format = "plain"

##### additional base config options #####

# Path to the JSON file containing the initial validator set and other meta data
genesis_file = "config/genesis.json"

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "config/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "config/node_key.json"

# Mechanism to connect to the ABCI application: socket | grpc
abci = "socket"

# TCP or UNIX socket address for the profiling server to listen on
prof_laddr = ""

# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = false

##### advanced configuration options #####

##### rpc server configuration options #####
[rpc]

# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:20057"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

# TCP or UNIX socket address for the gRPC server to listen on
# NOTE: This server only supports /broadcast_tx_commit
grpc_laddr = ""

# Maximum number of simultaneous connections.
# Does not include RPC (HTTP&WebSocket) connections. See max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
grpc_max_open_connections = 900

# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
unsafe = false

# Maximum number of simultaneous connections (including WebSocket).
# Does not include gRPC connections. See grpc_max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
max_open_connections = 900

# Maximum number of unique clientIDs that can /subscribe
# If you're using /broadcast_tx_commit, set to the estimated maximum number
# of broadcast_tx_commit calls per block.
max_subscription_clients = 100

# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
max_subscriptions_per_client = 5

# How long to wait for a tx to be committed during /broadcast_tx_commit.
# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.
# See https://github.com/tendermint/tendermint/issues/3435
timeout_broadcast_tx_commit = "10s"

# The name of a file containing certificate that is used to create the HTTPS server.
# If the certificate is signed by a certificate authority,
# the certFile should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server. Otherwise, HTTP server is run.
tls_cert_file = ""

# The name of a file containing matching private key that is used to create the HTTPS server.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server. Otherwise, HTTP server is run.
tls_key_file = ""

##### peer to peer configuration options #####
[p2p]

# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:20056"

# Address to advertise to peers for them to dial
# If empty, will use the same port as the laddr,
# and will introspect on the listener or use UPnP
# to figure out the address.
external_address = ""

# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = "c43490d7d9de9d1050df38fff5d7abba2e5c2505@Test_Node0:20056,7ef4b19596115bcb893be0029b12ac4542c2951e@Test_Node1:30056,6c75b2453da0067f1c5ac1ea5923889f16e9f2b5@Test_Node2:40056"

# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "config/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = false

# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "10ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024

# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

# Rate at which packets can be received, in bytes/second
recv_rate = 5120000

# Set true to enable the peer-exchange reactor
pex = true

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false

# Comma separated list of peer IDs to keep private (will not be gossiped to other peers)
private_peer_ids = ""

# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = true

# Peer connection configuration.
handshake_timeout = "20s"
dial_timeout = "3s"

##### mempool configuration options #####
[mempool]

recheck = true
broadcast = true
wal_dir = ""

# Maximum number of transactions in the mempool
size = 30000

# Limit the total size of all txs in the mempool.
# This only accounts for raw transactions (e.g. given 1MB transactions and
# max_txs_bytes=5MB, mempool will only accept 5 transactions).
max_txs_bytes = 1073741824

# Size of the cache (used to filter transactions we saw earlier) in transactions
cache_size = 20000

##### consensus configuration options #####
[consensus]

wal_file = "data/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "1s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = true
create_empty_blocks_interval = "0s"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

##### transactions indexer configuration options #####
[tx_index]

# What indexer to use for transactions
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "kv"

# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags (predefined tags:
# "tx.hash", "tx.height" and all tags from DeliverTx responses).
#
# Note this may be not desirable (see the comment above). IndexTags has a
# precedence over IndexAllTags (i.e. when given both, IndexTags will be
# indexed).
index_all_tags = false

##### instrumentation configuration options #####
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "tendermint"

**Comment by skdjango001** [comment] 2020-06-01 07:12
[2020-06-01|12:23:56.250] Executed block module=state height=4224 validTxs=1 invalidTxs=0
I[2020-06-01|12:23:56.251] Committed state module=state height=4224 txs=1 appHash=4E6F205374617465
2020/06/01 12:23:56 {0xc001dd4680 0xc0026e5db0}
I[2020-06-01|12:23:56.449] Executed block module=state height=4225 validTxs=1 invalidTxs=0
I[2020-06-01|12:23:56.450] Committed state module=state height=4225 txs=1 appHash=4E6F205374617465
2020/06/01 12:23:56 {0xc0018aad00 0xc001fa1120}
I[2020-06-01|12:23:56.743] Executed block module=state height=4226 validTxs=1 invalidTxs=0
I[2020-06-01|12:23:56.744] Committed state module=state height=4226 txs=1 appHash=4E6F205374617465
2020/06/01 12:23:57 {0xc000fc2400 0xc0017463d0}
I[2020-06-01|12:23:57.052] Executed block module=state height=4227 validTxs=1 invalidTxs=0
I[2020-06-01|12:23:57.053] Committed state module=state height=4227 txs=1 appHash=4E6F205374617465
2020/06/01 12:23:57 {0xc000fc3080 0xc0020b5280}
I[2020-06-01|12:23:57.351] Executed block module=state height=4228 validTxs=1 invalidTxs=0
I[2020-06-01|12:23:57.352] Committed state module=state height=4228 txs=1 appHash=4E6F205374617465
2020/06/01 12:23:57 {0xc001127300 0xc002392dc0}
I[2020-06-01|12:23:57.745] Executed block module=state height=4229 validTxs=1 invalidTxs=0
I[2020-06-01|12:23:57.746] Committed state module=state height=4229 txs=1 appHash=4E6F205374617465
2020/06/01 12:23:58 {0xc0020cbb00 0xc002c06730}
I[2020-06-01|12:23:58.053] Executed block module=state height=4230 validTxs=1 invalidTxs=0
I[2020-06-01|12:23:58.054] Committed state module=state height=4230 txs=1 appHash=4E6F205374617465
these are the logs which i got after tendermint unsafe_reset_all and then i restarted the nodes again 
@melekes @ebuchman @erikgrinaker @ValarDragon

**Comment by erikgrinaker** [comment] 2020-06-02 10:18
This is likely to be same problem as in #4914, closing as duplicate. If you are submitting more transactions than the application can process, then they will pile up until they time out.

**Closed by erikgrinaker** 2020-06-02 10:18 UTC

**Comment by xloem** [comment] 2023-07-05 09:06
I'm getting this error even though the transaction is confirmed.
