### ISSUE TITLE
Mempools grow indefinitely under load

### ISSUE THREAD

**Issue by ldmberman** [tendermint/tendermint#1661] opened 2018-05-31 15:28 UTC
Hi guys,

I would like to know your opinion on a certain problem, which I did not manage to find neither in the issues nor in the codebase.

According to our experiments, if a node keeps posting transactions at high pace, the network does not advance the blockchain - nodes receive the transactions and update their mempool, but do not engage in the consensus algorithm. This way, a single node can hold the blockchain construction off for an indefinite period of time (in our case tens of thousands of transactions ended up in the mempool and kept coming).

I imagine this to be by design, cause:

- no data is lost since everything is written to WAL;
- such an excess load may be prevented by some specific DOS prevention solution;
- some write availability is acquired at the cost of read availability.

How close is it to the truth? Do you have any other helpful insights into the problem?

Thank you!

**Comment by ebuchman** [comment] 2018-05-31 18:06
A few others have reported similar issue ie. https://github.com/tendermint/tendermint/issues/1642 and https://github.com/tendermint/tendermint/issues/1394

We're looking into this now.

What version of Tendermint are you using? We added a configurable cap to the mempool in v0.19.5 that should help with this, but it sounds like there might be something deeper we need to investigate.

Part of the challenge is to find the right balance between performance and the mempool UX (ie. what guarantees it provides).

**Comment by ldmberman** [comment] 2018-05-31 18:14
Thank you for the quick response.

I know about https://github.com/tendermint/tendermint/issues/1642 but I think it is unrelated - there the RPC server stops responding when everything else seems fine.

I did not see https://github.com/tendermint/tendermint/issues/1394 - it should be about the same issue indeed. But a single node is actually enough to observe this behaviour.

I was using `0.19.2`. I will try`v0.19.5` out, thank you!

**Comment by ldmberman** [comment] 2018-06-01 09:08
My colleague, @kansi tried out `0.19.7`:

> it seems to operate fine .i.e. blocks are being created slowly and steadly

So capping works, thank you!

There is now something else I would like to ask to avoid creating extra issues :)

While testing the capper, @kansi noticed that the RPC server stops responding intermittently for the time it commits new blocks. The same is actually happening when Tendermint replays the blocks for the proxy app. Is it a mempool implementation limitation? Do you expect the apps to implement additional buffering if rejecting transactions is not acceptable?

**Comment by melekes** [comment] 2018-06-01 11:58
> the RPC server stops responding intermittently for the time it commits new blocks. The same is actually happening when Tendermint replays the blocks for the proxy app. Is it a mempool implementation limitation?

It's intentional https://github.com/tendermint/tendermint/blob/178e357d7f31c698fa47af05749192a6f7ec44da/state/execution.go#L123-L124

> re: accepting txs while syncing

I believe doing this will result in bad UX because client will expect transaction to be committed during some period T (say 1 sec.), while if we buffer it, it will be sitting there until node is synced. It's better for the client to send it to another running node.

> Do you expect the apps to implement additional buffering if rejecting transactions is not acceptable?

the clients are expected to have some form of "retry" functionality where they resend txs if Tendermint is not yet synced or too busy. Note clients can send tx to another node in round-robin fashion (or weighted round-robin, or randomly chosen node, etc.).

**Comment by ldmberman** [comment] 2018-06-01 12:46
@melekes thank you for the insight - what you describe seems to be a valid client-side solution that also does not overload the network!

Sometimes though a server-side approach might work better - I can imagine it to be the case when network throughput is a concern - say you have a mobile cryptowallet - you probably want to give the transaction to a node and then occasionally check for the status but not send the same payload to multiple nodes.

**Comment by ebuchman** [comment] 2018-06-02 03:13
Can you clarify how to reproduce this ? 

One node on local machine with tm-bench running locally ? Something like ` tm-bench -c 1 -T 30 -r 25000 -v localhost:46657` ? 

Any changes to the config ? Maybe `create_empty_blocks = false` or anything else ? 

Any other details ?

**Comment by ldmberman** [comment] 2018-06-02 11:14
I tested it more thoroughly - Tendermint does seem to perform well, both `v0.19.2` and `v0.19.7`, except from 2 cases.

1. A cluster loaded by 1000 tx/s tends to accumulate the mempool as long as transactions keep going.

This is how I run the cluser:

```
tendermint testnet --n 2

./run_cluster_node 0 1  # 0th node connected to 1th node
./run_cluster_node 1 -1  #1th node connected to 0th node
./run_cluster_node 2 -1
./run_cluster_node 3 -1
./run_cluster_node 4 -1
./run_cluster_node 5 1
````

where `run_cluster_node`:

```
nohup tendermint node --home=mytestnet/node$1 \
	--p2p.laddr=tcp://0.0.0.0:4667$1 \
	--rpc.laddr=tcp://0.0.0.0:4668$1 \
	--proxy_app=persistent_kvstore \
	--p2p.persistent_peers=`tendermint show_node_id --home=mytestnet/node$(($1 + $2))`@0.0.0.0:4667$(($1 + $2)) \
	--consensus.create_empty_blocks=false \
	2>&1 >cluster_node_$1.log &
```

The low transaction rate does not trigger the mempool growth. The high rate does. I stressed it using `tm-bench -c 1 -T 10 -r 1000 -v localhost:46680`. 

We observed similar behaviour in our real cluster where each node is deployed to a separate VM, with around 7 nodes, on `v0.19.2`. It differs from the attempt to stress a single node where the RPC server simply timeouts when it does not manage to process the transactions timely (e. g. because it takes too long for the proxy app to validate transactions).

The mempool capper fixes the behaviour. Although locally under very heavy load (`tm-bench -c 1 -T 10 -r 1000 -v localhost:46680`) when the cap is hit the cluster is not committing blocks for some time and the logs of the first node produce tons of `I[06-02|11:03:47.657] Could not check tx                           module=mempool tx=Tx{..} err="Mempool is full"`. In a couple of minutes it starts to commit blocks - I am not sure if this is something undesired - may be deserves a separate issue but this one can be closed from my point of view.

2. The RPC server can be made unresponsive as reported in https://github.com/tendermint/tendermint/issues/1642.

Happens with both `v0.19.2` and `v0.19.7`. Inserting `time.Sleep(time.Second)` into the proxy app's `CheckTx` and repeatedly calling `tm-bench -c 1 -T 10 -r 25000 -v localhost:46657` helps to reproduce it.

At some point the RPC stopped serving any requests, the only reaction to them being the following log:

```
11:17:46 rts.1  | D[06-02|09:17:46.180] HTTP HANDLER                                 module=rpc-server req="&{Method:GET URL:/unconfirmed_txs Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[User-Agent:[curl/7.54.0] Accept:[*/*]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:localhost:46657 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:[::1]:56254 RequestURI:/unconfirmed_txs TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc422b1ae00}"
```

I tried your PR - https://github.com/tendermint/tendermint/pull/1673/files - it does seem to solve the problem!

**Comment by melekes** [comment] 2018-06-04 12:30
> In a couple of minutes it starts to commit blocks

weird stuff.. I can reproduce by running local network (`make localnet-start`) with `create_empty_blocks=false`.

```
node3    | I[06-04|12:24:37.898] enterPropose(41/0). Current: 41/0/RoundStepNewRound module=consensus height=41 round=0
node3    | I[06-04|12:24:37.898] enterPropose: Our turn to propose            module=consensus height=41 round=0 proposer=D3B5CD5D804082F73371034704799A9ADD5DD148 privValidator="PrivValidator{D3B5CD5D804082F73371034704799A9ADD5DD148 LH:41, LR:0, LS:2}"
node3    | E[06-04|12:24:37.903] enterPropose: Error signing proposal         module=consensus height=41 round=0 err="Error signing proposal: Step regression"
```

**Comment by melekes** [comment] 2018-06-06 08:49
Closed in favor of https://github.com/tendermint/tendermint/issues/1642

**Closed by melekes** 2018-06-06 08:49 UTC
