### ISSUE TITLE
when (pex=false), validator losses peers and its not able to reconnected to this lost peer

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1846] opened 2018-07-02 18:55 UTC
original issue: https://github.com/cosmos/cosmos-sdk/issues/1458 opened by @iammelea

**Comment by ebuchman** [comment] 2018-07-14 17:34
Believe this is a duplicate of #1720

**Closed by ebuchman** 2018-07-14 17:34 UTC
Labels: bug, p2p

**Comment by iammelea** [comment] 2018-07-14 17:44
Public ip. My case.
