### ISSUE TITLE
"Panicked on a Crisis: Could not determine external address!" when node is off network (local dev on node off network).

### ISSUE THREAD

**Issue by ratranqu** [tendermint/tendermint#621] opened 2017-08-24 19:32 UTC
BUG REPORT:

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): `0.10.2-'b467515` and `0.10.3-'8d76408`

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS Sierra
- **Install tools**: zip from github.com/tendermint
- **Other***: I am running a single node `ethermint` with ` local `tendermint` process on the same machine, which is not connected to a network. 

**What happened**:
When running on a node on a machine not connected to a network (for instance when doing dev in a place off grid), `tendermint` starts fine, but when I start `ethermint` I get the panic as shown below:

```
$ ./bin/tendermint --home ./.ethermint/tendermint node
E[08-24|19:07:00.278] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
E[08-24|19:07:03.280] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
E[08-24|19:07:06.281] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
E[08-24|19:07:09.282] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
E[08-24|19:07:12.283] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
E[08-24|19:07:15.285] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
panic: Panicked on a Crisis: Could not determine external address!

goroutine 1 [running]:
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.PanicCrisis(0x16ba480, 0xc420160fa0)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/errors.go:33 +0xdd
github.com/tendermint/tendermint/p2p.NewDefaultListener(0xc42000ab20, 0x3, 0xc42000ab26, 0xd, 0x1c6fc00, 0x1c6fc60, 0xc4204cfa70, 0x0, 0xc420180fc0)
	/go/src/github.com/tendermint/tendermint/p2p/listener.go:93 +0x72f
github.com/tendermint/tendermint/node.(*Node).OnStart(0xc420162120, 0xc420160c30, 0xd)
	/go/src/github.com/tendermint/tendermint/node/node.go:241 +0x1f5
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.(*BaseService).Start(0xc420162120, 0x1c6fc60, 0xc4204fef90, 0xc420162120)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/service.go:105 +0x482
github.com/tendermint/tendermint/cmd/tendermint/commands.runNode(0x1cb1e80, 0xc4204da440, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/tendermint/tendermint/cmd/tendermint/commands/run_node.go:79 +0x38d
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).execute(0x1cb1e80, 0xc4204da400, 0x2, 0x2, 0x1cb1e80, 0xc4204da400)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1cb1c60, 0x100ff48, 0x20, 0x1719520)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).Execute(0x1cb1c60, 0x15fc581, 0x1719520)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x1cb1c60, 0x19130d0, 0x2, 0xc4204da200)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/cli/setup.go:97 +0x4e
main.main()
	/go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:12 +0x8b
```

connecting the machine so that it has an ip address during the handshake process prevents the bug from happening.

**What you expected to happen**:
I wouldn't think that the external ip is necessary when both processes are local. So I would expect that the process still goes ahead. I concede that this is a very low priority bug, but I think it's good to be aware of the behaviour.

**How to reproduce it** (as minimally and precisely as possible):
install `ethermint` and `tendermint` on a machine that can be disconnected from the network completely. run `tendermint` first, then run `ethermint` (as detailed on the Ethermint README.md on github).

**Comment by melekes** [comment] 2017-08-25 02:56
Duplicate of https://github.com/tendermint/tendermint/issues/537?

**Comment by ratranqu** [comment] 2017-08-25 08:42
Very likely.

**Comment by melekes** [comment] 2017-08-27 02:26
Closing in favor of #537

**Closed by melekes** 2017-08-27 02:26 UTC
