### ISSUE TITLE
Config for starting mempool, consensus, evidence reactor or not like pex reactor does

### ISSUE THREAD

**Issue by yutianwu** [tendermint/tendermint#2197] opened 2018-08-09 08:20 UTC
Sometimes, we may need nodes that only propagate blocks like seed nodes. 

So I think it would be better if we can a config to decide which reactor we want to start when we start the node.

**Comment by ValarDragon** [comment] 2018-08-10 01:26
duplicate of https://github.com/tendermint/tendermint/issues/1148

**Closed by ValarDragon** 2018-08-10 01:26 UTC
