### ISSUE TITLE
/block endpoint could be cleaner

### ISSUE THREAD

**Issue by fedekunze** [tendermint/tendermint#2689] opened 2018-10-22 14:02 UTC
From https://github.com/cosmos/cosmos-sdk/issues/2504
cc: @nckrtl 

## Summary
I am playing around with the block endpoint that's available on port 26657, and I noticed some redundant header information. Im posting this as a feature request as I'm not sure if its really a bug.

## Problem Definition
When you request for example the api endpoint <node>:26657/block?height=10000, you see a section with block_meta and block. However, they both contain a header part that contain exactly the same information and is therefor being redundant.

<img width="609" alt="screenshot 2018-10-16 at 13 49 06" src="https://user-images.githubusercontent.com/18613261/47014586-f26fd300-d14a-11e8-9798-d4dca1b1cb8d.png">

## Proposal
Remove the header part from block_meta or remove the header part from block. Perhaps choosing the first option is best as the header part is actually containing meta information about the block.

If there is a good reason why we need two headers with the same information, I'd like to know.

Thanks.

**Comment by marbar3778** [comment] 2019-07-30 12:32
@melekes is the blockID needed here?

**Comment by melekes** [comment] 2019-07-30 13:44
Duplicate of https://github.com/tendermint/tendermint/issues/3188

**Comment by marbar3778** [comment] 2019-07-30 13:50
closing in favor of #3188

**Closed by marbar3778** 2019-07-30 13:50 UTC
Labels: enhancement, rpc
