### ISSUE TITLE
Timeouts become extremely long in case we halt for a while and should be reset faster

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1464] opened 2018-04-14 15:55 UTC
Today the testnet went down because >1/3 of the voting power went down. However even after that was fixed, the testnet took another hour to come back online (this is an estimate) due to (my guess) extremely long consensus timeouts. 

We should look into:
* an upper limit on the consensus timeouts of let’s say 1 minute
* restarting a node resets all local timeouts

**Comment by kidinamoto01** [comment] 2018-04-15 11:52
@adrianbrink I was reading through this [doc]
and according to this function
https://github.com/tendermint/tendermint/blob/4930b61a381b9fb9bc530eb5deb56ea6429a1c3a/config/config.go#L449
if we are at round 100k then the proposal timeout can be several hours?

**Comment by jaekwon** [comment] 2018-04-16 12:52
Please share the logs here.  We can't have upper limits on consensus timeouts, the timeout system is fine as it only goes up with round number.  We can't just naively restart a node to reset local timeouts.  We'll figure out the bug by reading the logs, lets not jump to conclusions.

**Comment by jaekwon** [comment] 2018-04-16 12:53
> the proposal timeout can only be several seconds then why the proposal timeout could be several hours?

time.Duration represents an arbitrary duration of time, seconds to hours.  But anyways the timeout is probably not the issue.  I bet it's some peer networking issue.

**Comment by kidinamoto01** [comment] 2018-04-16 13:05
@jaekwon 
this is my log
https://gist.github.com/kidinamoto01/191a4755781eb10f18c5524419c7e835

**Comment by melekes** [comment] 2018-04-16 16:57
consensus state: https://gist.github.com/melekes/b8ee87c4ed258e3a73f4f355e6d67e19

**Comment by kidinamoto01** [comment] 2018-04-17 01:15
I recalled what happened is at heigh 106451 a validator with +1/3 power went unbond, then the next proposer was somehow offline. In the end, we waited for two hours for the next block.

**Comment by milosevic** [comment] 2018-04-18 07:39
I have reviewed code once more and can confirm that timeouts linearly grow with round number, but validators move to the next round only upon receiving +2/3 votes (both prevotes and precommits). Therefore, in case a validator(s) with +1/3 of voting power are down, network will not make progress and therefore timeout will not keep increasing.
I don't see how resetting timeouts help, and in general I am not sure that restarting a node should be seen as a mechanism for fixing issues. 

I would however suggest to add mechanism for periodically logging critical information such as consensus state, especially if a process is not making progress for some time. In case we are stuck at some height, it should be straightforward to obtain validators state so we can do analysis.

**Comment by kidinamoto01** [comment] 2018-04-18 07:59
@milosevic thanks for your feedback
I agree with you that reseting timeout will not be much helpful.
Right now, it's hard to figure out consensus status from log. we should expose relevant info in `/status` RPC endpoint, could we add "consensus_info"?

**Comment by kidinamoto01** [comment] 2018-04-18 08:59
@milosevic sure,  maybe we could get consensus state of a certain Height ? even a certain round?
`/dump_consensus_state` returns everything, it's hard to monitor.

**Comment by ebuchman** [comment] 2018-04-24 16:31
I'm not sure exactly what happened here, but the rounds (and thus the timeouts) will not be increasing if +1/3 is offline.

We should run some tests of this to see if we can replicate the behaviour under controlled conditions - that should help direct the solution. 

One thing we could consider is an `/unsafe_skip_consensus_timeout` so we can manually move to the next state in the consensus machine.

As for `/dump_consensus_state`, we'll keep working on improving it.

**Comment by ebuchman** [comment] 2018-04-24 16:31
I've marked this as "bug" because "Timeouts become extremely long in case we halt for a while" should not be a true statement. Let's try to reproduce and figure out what happened

**Comment by kidinamoto01** [comment] 2018-04-30 09:39
@ebuchman I noted it was `0.15.0-rc1-9d90c6b` for  `gaiad`

**Comment by ebuchman** [comment] 2018-04-30 12:05
Ok. So if I:

- start a one node gaia chain
- bond a new validator with half the stake
- wait a while (while the chain is halted)
- start the new validator node

Then everything works as expected (they start quickly making blocks).

Same if I now stop one of the nodes for a minute and restart - they start making blocks again.

Any idea how to replicate then ? Do I need to take a node down for much longer ?

**Comment by kidinamoto01** [comment] 2018-04-30 12:30
en, I think we had similar issue on Gaia-4000 just the other day. 
@adrianbrink now have two nodes, each accounts for like 1/3 power, then one node was crashed, and the network halted for hours . `dump_consensus_state` showed the crashed node was the next proposer. 
I wish @adrianbrink has the logs.

**Comment by jackzampolin** [comment] 2019-06-22 00:05
We haven't seen this recur anywhere.

**Closed** 2019-06-22 00:05 UTC
Labels: bug, consensus
