### ISSUE TITLE
Seed nodes drop all peers with pong timeout

### ISSUE THREAD

**Issue by zmanian** [tendermint/tendermint#3230] opened 2019-01-29 22:09 UTC
Here is what I am observing.

When I run a node with `seed_node=true` and moderate to high incoming connection load.

Every peer stops on a `pong timeout` error.

```
E[2019-01-28|23:11:41.878] Stopping peer for error                      module=p2p peer="Peer{MConn{35.178.255.1:26656} 2da253df860538fd0adcc7fd79f89f088aca7353 out}" err="pong timeout"
E[2019-01-28|23:11:43.451] Connection failed @ sendRoutine              module=p2p peer=e47b9895c092122821b0f166501b594195054f43@8.8.8.8:26656 conn=MConn{52.52.28.101:26656} err="pong timeout"
E[2019-01-28|23:11:43.451] Stopping peer for error                      module=p2p peer="Peer{MConn{52.52.28.101:26656} e47b9895c092122821b0f166501b594195054f43 out}" err="pong timeout"
E[2019-01-28|23:11:44.132] Connection failed @ sendRoutine              module=p2p peer=5b2d308c2e24dfd1d7a89c8779621839c7bd0719@13.52.136.172:26656 conn=MConn{13.52.136.172:26656} err="pong timeout"
E[2019-01-28|23:11:44.133] Stopping peer for error                      module=p2p peer="Peer{MConn{13.52.136.172:26656} 5b2d308c2e24dfd1d7a89c8779621839c7bd0719 out}" err="pong timeout"
E[2019-01-28|23:11:44.794] Connection failed @ sendRoutine              module=p2p peer=5691f066133eaa40c9fdb0f2a76106bff06469bd@0.0.0.0:26656 conn=MConn{35.234.98.115:26656} err="pong timeout"
E[2019-01-28|23:11:44.794] Stopping peer for error                      module=p2p peer="Peer{MConn{35.234.98.115:26656} 5691f066133eaa40c9fdb0f2a76106bff06469bd out}" err="pong timeout"
E[2019-01-28|23:11:45.145] Connection failed @ sendRoutine              module=p2p peer=1cf82349127cd57ae8727d9161805bf9ecf4ad5e@77.87.106.26:26656 conn=MConn{77.87.106.26:26656} err="pong timeout"
E[2019-01-28|23:11:45.145] Stopping peer for error                      module=p2p peer="Peer{MConn{77.87.106.26:26656} 1cf82349127cd57ae8727d9161805bf9ecf4ad5e out}" err="pong timeout"
E[2019-01-28|23:12:23.318] MConnection flush failed                     module=p2p peer=0a4a79aa03439848c9b55d51a86169efdfe68b58@34.219.198.246:26656 err="write tcp 10.128.0.6:60358->34.219.198.246:26656: write: connection timed out"
E[2019-01-28|23:12:23.318] Failed to write PacketMsg                    module=p2p peer=0a4a79aa03439848c9b55d51a86169efdfe68b58@34.219.198.246:26656 err="write tcp 10.128.0.6:60358->34.219.198.246:26656: write: connection timed out"
E[2019-01-28|23:12:23.318] Stopping peer for error                      module=p2p peer="Peer{MConn{34.219.198.246:26656} 0a4a79aa03439848c9b55d51a86169efdfe68b58 out}" err="write tcp 10.128.0.6:60358->34.219.198.246:26656: write: connection timed out"
```

**Comment by ebuchman** [comment] 2019-01-29 22:58
Possibly related https://github.com/tendermint/tendermint/issues/2955 and https://github.com/tendermint/tendermint/issues/2821

Can you SIGABRT ( `kill -6` ) the process and capture the dump so we can see if there's possibly a deadlock? Alternatively run the node with pprof so we can just query the go-routines without killing the node.

**Comment by ebuchman** [comment] 2019-01-30 00:36
Looks like there's an infinite loop in the `book.GetSelectionWithBias`. I've written a very simple test that reproduces it:

```
func TestAddrBookNonsense(t *testing.T) {
	fname := createTempFileName("addrbook_test")
	defer deleteTempFile(fname)

	// 0 addresses
	book := NewAddrBook(fname, true)
	book.SetLogger(log.TestingLogger())
	assert.Zero(t, book.Size())

	N := 10
	randAddrs := randNetAddressPairs(t, N)
	for _, addr := range randAddrs {
		book.AddAddress(addr.addr, addr.src)
	}
	book.MarkGood(randAddrs[0].addr)

	for _, addr := range randAddrs[N/2:] {
		book.RemoveAddress(addr.addr)
	}

	addrs := book.GetSelectionWithBias(10)
	assert.NotNil(t, addrs, "expected an address")
}
```

**Comment by ebuchman** [comment] 2019-02-08 05:36
Should be fixed in #3232, released in v0.29.2 :)

**Closed by ebuchman** 2019-02-08 05:36 UTC
Labels: bug

**Comment by njmurarka** [comment] 2020-05-31 04:52
Noticing similar issue in #4924

**Comment by zmanian** [comment] 2020-05-31 06:34
I've been seeing these messages like #4924 in the game of zones sentry nodes.

**Comment by erikgrinaker** [comment] 2020-06-02 10:02
>I've been seeing these messages like #4924 in the game of zones sentry nodes.

@zmanian This may simply be peers losing network connectivity or otherwise having operational problem, do you see any patterns or correlated problems? Could you please add some details on https://github.com/tendermint/tendermint/issues/4925#issuecomment-637432515?
