### ISSUE TITLE
Health/Status do not report error when chain halts

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#1729] opened 2018-06-09 22:33 UTC
**BUG REPORT**

- version: 0.20.0 (released package)
- OS: OSX
- created 2 node setup, both nodes are validators
- create_empty_blocks = true
- used JavaCounter app as ABCI app (https://github.com/jTendermint/jabci)
- killed one of the ABCI apps
- remaining validator node stopped producing blocks
- queried status and health endpoint on remaining endpoint

**What happened**:
Both do not report an error

**What you expected to happen**:
They should report an error

**Output of /status**
```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "id": "14a6dcadc896a08e87ea12ff464711d889d5b77a",
      "listen_addr": "192.168.42.44:46656",
      "network": "test-chain-QMHJ4W",
      "version": "0.20.0-27bd1dea",
      "channels": "4020212223303800",
      "moniker": "my machine name",
      "other": [
        "amino_version=0.9.9",
        "p2p_version=0.5.0",
        "consensus_version=v1/0.2.2",
        "rpc_version=0.7.0/3",
        "tx_index=on",
        "rpc_addr=tcp://0.0.0.0:46657"
      ]
    },
    "sync_info": {
      "latest_block_hash": "8C3B2D7CD8FB569E9E407391BEEDD39BAEF7C703",
      "latest_app_hash": "",
      "latest_block_height": 22,
      "latest_block_time": "2018-06-10T00:27:17.297249329+02:00",
      "syncing": false
    },
    "validator_info": {
      "address": "B5A8E53B84C94FB98C94C487FC19B0CC4F490DEA",
      "pub_key": {
        "type": "AC26791624DE60",
        "value": "xZYfYQGfrDi4dFF1ETY6qRGFfyZ6HUg7OpdRJpS1BAY="
      },
      "voting_power": 10
    }
  }
}
```

**Output of /health**
`{
  "jsonrpc": "2.0",
  "id": "",
  "result": {}
}`

**Log of remaining validator when killing the 2nd one**
```
}#
  Data{

  }#
  Commit{
    BlockID:    6D25D71DB79FCC2336AAEBAE504A3D9407C1BFD2:1:B1E7B2BED032
    Precommits: Vote{0:377218B1A541 21/00/2(Precommit) 6D25D71DB79F /E2AFF14547C6.../ @ 2018-06-09T22:27:16.194Z}
    Vote{1:B5A8E53B84C9 21/00/2(Precommit) 6D25D71DB79F /F5A1C712D5E6.../ @ 2018-06-09T22:27:16.093Z}
  }#E91F57A8FB46ECC0294E79ADE3D97CC58490AD63
}#8C3B2D7CD8FB569E9E407391BEEDD39BAEF7C703 module=consensus
I[06-09|22:27:17.511] Executed block                               module=state height=22 validTxs=0 invalidTxs=0
I[06-09|22:27:17.511] Committed state                              module=state height=22 txs=0 appHash=
I[06-09|22:27:17.512] Recheck txs                                  module=mempool numtxs=0 height=22
I[06-09|22:27:17.512] Indexed block                                module=txindex height=22
E[06-09|22:27:18.230] Connection failed @ recvRoutine (reading byte) module=p2p peer=127.0.0.1:57841 conn=MConn{127.0.0.1:57841} err=EOF
I[06-09|22:27:18.230] Stopping MConnection                         module=p2p peer=127.0.0.1:57841 impl=MConn{127.0.0.1:57841}
E[06-09|22:27:18.231] Stopping peer for error                      module=p2p peer="Peer{MConn{127.0.0.1:57841} b7ea63cf5733de753713fbf310bdbc208be75db9 in}" err=EOF
I[06-09|22:27:18.231] Stopping Peer                                module=p2p peer=127.0.0.1:57841 impl="Peer{MConn{127.0.0.1:57841} b7ea63cf5733de753713fbf310bdbc208be75db9 in}"
I[06-09|22:27:18.301] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{127.0.0.1:57841} b7ea63cf5733de753713fbf310bdbc208be75db9 in}"
I[06-09|22:27:18.317] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{127.0.0.1:57841} b7ea63cf5733de753713fbf310bdbc208be75db9 in}"
I[06-09|22:27:18.418] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{127.0.0.1:57841} b7ea63cf5733de753713fbf310bdbc208be75db9 in}"
I[06-09|22:27:18.508] Timed out                                    module=consensus dur=995.078395ms height=23 round=0 step=RoundStepNewHeight
I[06-09|22:27:18.508] enterNewRound(23/0). Current: 23/0/RoundStepNewHeight module=consensus height=23 round=0
I[06-09|22:27:18.508] enterPropose(23/0). Current: 23/0/RoundStepNewRound module=consensus height=23 round=0
I[06-09|22:27:18.508] enterPropose: Not our turn to propose        module=consensus height=23 round=0 proposer=377218B1A5419768569B7829CE95C774F125DB35 privValidator="PrivValidator{B5A8E53B84C94FB98C94C487FC19B0CC4F490DEA LH:22, LR:0, LS:3}"
I[06-09|22:27:21.508] Timed out                                    module=consensus dur=3s height=23 round=0 step=RoundStepPropose
I[06-09|22:27:21.508] enterPrevote(23/0). Current: 23/0/RoundStepPropose module=consensus
I[06-09|22:27:21.508] enterPrevote: ProposalBlock is nil           module=consensus height=23 round=0
I[06-09|22:27:21.510] Signed and pushed vote                       module=consensus height=23 round=0 vote="Vote{1:B5A8E53B84C9 23/00/1(Prevote) 000000000000 /AF40A63C70FC.../ @ 2018-06-09T22:27:21.508Z}"
```

**Comment by muawiakh** [comment] 2018-06-11 10:15
Faced a similar problem with `0.19.2`, seems like this hasn't been fixed yet.

**Comment by melekes** [comment] 2018-07-23 17:46
Duplicate of https://github.com/tendermint/tendermint/issues/1772.

**Closed by melekes** 2018-07-23 17:46 UTC
Labels: bug, rpc
