### ISSUE TITLE
Non-validating nodes getting "Connection failed @ sendRoutine" in P2P module

### ISSUE THREAD

**Issue by njmurarka** [tendermint/tendermint#4922] opened 2020-05-30 22:01 UTC
**Note**:

I filed #4922, #4924, #4925 separately, but they entirely might be related. Apologies in advance if they are all the same issue.

**Tendermint version**:

Tendermint Core Semantic Version: 0.33.3
P2P Protocol Version: 7
Block Protocol Version: 10
```
"node_info": {
    "protocol_version": {
      "p2p": "7",
      "block": "10",
      "app": "0"
    },
    "id": "dbc39feecf277f59b4b16ae277e8545c54ac244a",
    "listen_addr": "tcp://0.0.0.0:26656",
    "network": "bluzelle",
    "version": "0.33.3",
    "channels": "4020212223303800",
    "moniker": "daemon-sentry-3",
    "other": {
      "tx_index": "on",
      "rpc_address": "tcp://0.0.0.0:26657"
    }
```

**ABCI app**:

Cosmos SDK Version: v0.38.3
```
"application_version": {
    "name": "BluzelleService",
    "server_name": "blzd",
    "client_name": "blzcli",
    "version": "0.0.0-74-ge1ee575",
    "commit": "e1ee575051ad2ea18ef22fc6bf7a6fc904612a49",
    "build_tags": "ledger,faucet,cosmos-sdk v0.38.3",
    "go": "go version go1.14.3 linux/amd64"
  }
```

Big Dipper Explorer URL:

```
http://explorer.testnet.public.bluzelle.com:3000
```

Instructions to setup a similar node (I'd suggest just setting up a sentry):
```
https://github.com/bluzelle/curium/blob/devel/docs/public/buildvalidatorsentry.md
```

Access to genesis file for chain:
```
http://a.sentry.bluzellenet.bluzelle.com:1317/genesis.json
```

Sample command to get node info:
```
curl --location --request GET 'http://a.sentry.testnet.public.bluzelle.com:1317/node_info'
```

Discord channel invite (in case you want to live chat with me... I am Neeraj one of the admins):
```
https://discord.gg/BbBZJZJ
```

**Environment**:
- **OS** (e.g. from /etc/os-release):

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

- **Install tools**:

Using COSMOS SDK. Otherwise, not sure what else to say here.

- **Others**:

We are running a testnet with our CRUD database as one of the application modules, in COSMOS. 

We currently (as of filing this issue) have 5 "sentries" and 3 validators. To be clear, the sentries have no voting power and are the only peers that the validators talk to (the validators can talk to each other too). Furthermore, the validators are IP firewalled to only be able to talk to the sentries and other validators. The sentries themselves keep the validator node id's private.

Sentry hostnames:

```
a.sentry.testnet.public.bluzelle.com
b.sentry.testnet.public.bluzelle.com
c.sentry.testnet.public.bluzelle.com
d.sentry.testnet.public.bluzelle.com
e.sentry.testnet.public.bluzelle.com
```

I am not listing the validator hostnames, since they are inaccessible (due to the firewall) anyways.

The validators are only listening on 26656 to validators and sentries. The sentries are listening on 26656 and 26657 and also each run the cosmos REST server, listening on 1317. 

We have opened our network to the public. Members of the public have setup sentries and validators of their own, and are expected to use our five sentries as their P2P peers in config.toml. 

**What happened**:

We are getting constantly messages as follows on the sentries.

```
E[2020-05-30|20:58:37.063] Connection failed @ sendRoutine              module=p2p peer=f1b412c2a33bda98f42959e86602a0ca9a3ede22@54.163.188.170:26656 conn=MConn{54.163.188.170:26656} err="pong timeout"
E[2020-05-30|20:58:37.063] Stopping peer for error                      module=p2p peer="Peer{MConn{54.163.188.170:26656} f1b412c2a33bda98f42959e86602a0ca9a3ede22 out}" err="pong timeout"
```

Note that these messages only happen on our sentries. Our validators never show these messages.

Also note I have removed lines that are considered "clean" from the above output, for brevity. The same sentries showing this "bad" output will also output the "clean" output lines.

This could be related to #4924 and #4925. I filed these separately since they seem related but still different issues.

**What you expected to happen**:

We expect "clean" output, as so:

```
I[2020-05-30|21:53:04.286] Executed block                               module=state height=20416 validTxs=0 invalidTxs=2
I[2020-05-30|21:53:04.309] Committed state                              module=state height=20416 txs=2 appHash=80D70DC5FF062F34D3F79F15FC85CB367A5A7F9CF39B4EE6C1DC68E9F1958EA1
```

(The fact that invalidTxs is non-zero is the subject of another investigation)

**Have you tried the latest version**: 

Not sure. I think so. Although in looking at the Tendermint Github, I see there are two minor versions available that are newer than what we have.

**How to reproduce it**:

Difficult to answer this. We never saw this when we were running a "small" chain with say < 20 nodes (ie: we were getting "clean" output. Once we opened to the public and allowed anyone to join in, we started to see this happen constantly. 

I suppose if you setup a network like ours and used the same code, you might reproduce it. The good news is it is happening right now and readily happens.

**Logs**:

Listed above.

**Config**:

No specific changes made to Tendermint. 

**node command runtime flags**:

This is all running from within our daemon that was built with the COSMOS SDK.

**`/dump_consensus_state` output for consensus bugs**

Not sure how to do this.

**Anything else we need to know**:

Most details given above. 

I did some searching ahead of time to see if I could resolve this myself. I saw some issues related to it but they were closed, yet I am seeing this now.

I have also files some other issues that might be related to this one and have done my best to refer related issues to each other.

**Comment by erikgrinaker** [comment] 2020-06-02 09:57
These pong timeouts indicate that a peer has stopped responding - the default pong timeout is 45 seconds, from what I can tell. It may be because the peer simply lost network connectivity, but it may also indicate some other problem with the peer and/or networking preventing the node from communicating with the peer.

Could you provide some more details about this? How often do you see these errors? Is the peer still up and available when the errors occur? Do you see them primarily from the same set of peers, or is it widely distributed? Do you see timeouts against multiple peers, and/or on multiple sentries, in the same time period?

**Comment by melekes** [comment] 2020-06-02 12:45
Duplicate of https://github.com/tendermint/tendermint/issues/4925

**Closed** 2020-06-02 12:45 UTC
Labels: C:p2p
