### ISSUE TITLE
p2p/trust: remove sleeps from tests

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#916] opened 2017-12-02 04:08 UTC
Tests are still racey, possibly due to `time.Sleep`. We should try to change the trustmetric so we can run the tests properly without sleeps

**Comment by ebuchman** [comment] 2017-12-02 04:12
See comment from https://github.com/tendermint/tendermint/pull/914

```
WARNING: DATA RACE
Read at 0x00c4200bc758 by goroutine 42:
  github.com/tendermint/tendermint/p2p/trust.(*TrustMetric).calcTrustValue()
      github.com/tendermint/tendermint/p2p/trust/_test/_obj_test/trustmetric.go:584 +0xa7
  github.com/tendermint/tendermint/p2p/trust.(*TrustMetric).NextTimeInterval()
      github.com/tendermint/tendermint/p2p/trust/_test/_obj_test/trustmetric.go:348 +0xef
  github.com/tendermint/tendermint/p2p/trust.(*TrustMetric).processRequests()
      github.com/tendermint/tendermint/p2p/trust/_test/_obj_test/trustmetric.go:607 +0xdb

Previous write at 0x00c4200bc758 by goroutine 8:
  [failed to restore the stack]

Goroutine 42 (running) created at:
  github.com/tendermint/tendermint/p2p/trust.NewMetricWithConfig()
      github.com/tendermint/tendermint/p2p/trust/_test/_obj_test/trustmetric.go:448 +0x281
  github.com/tendermint/tendermint/p2p/trust.(*TrustMetricStore).loadFromDB()
      github.com/tendermint/tendermint/p2p/trust/_test/_obj_test/trustmetric.go:147 +0x34a
  github.com/tendermint/tendermint/p2p/trust.TestTrustMetricStoreSaveLoad()
      /go/src/github.com/tendermint/tendermint/p2p/trust/trustmetric_test.go:66 +0x685
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xf5
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0xbe
  github.com/tendermint/tendermint/vendor/github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /go/src/github.com/tendermint/tendermint/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:571 +0x18c
  github.com/tendermint/tendermint/vendor/github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /go/src/github.com/tendermint/tendermint/vendor/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:386 +0x2dd
```

I thought we'd fixed that.
[test_integrations (1).log.zip](https://github.com/tendermint/tendermint/files/1523533/test_integrations.1.log.zip)

**Comment by ebuchman** [comment] 2017-12-02 04:35
May just be due to missing lock in `Copy` method, fixed in https://github.com/tendermint/tendermint/pull/917

But we should still aim to remove those Sleeps.

**Comment by zramsay** [comment] 2017-12-28 13:36
duplicate of #956

**Closed by zramsay** 2017-12-28 13:36 UTC
Labels: Area: P2P
