### ISSUE TITLE
Tendermint shows time dependent performance degredation

### ISSUE THREAD

**Issue by z-bowen** [tendermint/tendermint#1835] opened 2018-06-29 09:45 UTC
**BUG REPORT**

**Tendermint version**: 0.20.0-27bd1dea

**Environment**:
- **OS**: Ubuntu 18.04 LTS (Bionic Beaver)
- **Processor**: Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz (10 cores)
- **Memory**: 15GB

**What happened**:
The tm-bench tool shows a performance degradation over time. Initially, I can get performance on the order of 2000tx/s, but this drops off rapidly as the test duration increases. After 1000s, I see transaction rates of only ~200tx/s, and this continues to fall as the test duration increases.

**What you expected to happen**:
Tendermint transaction rates should be consistent, regardless of test duration.

**How to reproduce it**:
A detailed report of the study can be found [here](https://github.com/bigchaindb/BEPs/tree/ecdf09868be7b8c922f893aa09e1acdd1e0d5912/19)

This report contains scripts to reproduce the problem, as well as the config.toml from the test runs.

**Anything else do we need to know**:
I'll be out of the office and unable to check emails for the next week, but I'll be happy to communicate with your team about this issue when I'm back on 9.7.18

**Comment by ValarDragon** [comment] 2018-06-29 16:13
We've recently created patches to tm-bench to fix this. There was an issue with the tm-bench code. (Basically stats were only being collected from the last 20 blocks, not over all blocks in that duration) Thanks for making the report, its awesome!

The graphs you made look roughly like a `1/x` curve which is what we'd expect since tm-bench was only reading the last 20 blocks

**Comment by melekes** [comment] 2018-07-02 07:54
> Any pauses needed to maintain throughput on the Tendermint end should be invisible to the user, as the memory buffer stays available at all times.

given you are limiting the number of requests per IP, right? Otherwise, any DDOS attack will lead to OOM (out of memory) errors.

**Comment by melekes** [comment] 2018-07-02 10:55
I run the scripts on my dev. machine and can confirm there is a slight decline in performance.

Tendermint: https://github.com/tendermint/tendermint/tree/release/v0.22.0
tm-bench: https://github.com/tendermint/tools/commit/db419a308e6618eb52d0df6193fbbce482417311

![screen shot 2018-07-02 at 14 52 41](https://user-images.githubusercontent.com/1282182/42160320-d41a6a96-7e07-11e8-87a1-3a62e45bb428.png)

red - std.dev
yellow - max

**Comment by melekes** [comment] 2018-07-02 13:47
Not immediately apparent of why this is happening.

**Comment by melekes** [comment] 2018-07-02 14:32
Mempool is growing over time:

![screen shot 2018-07-02 at 18 30 11](https://user-images.githubusercontent.com/1282182/42169945-3607f99e-7e26-11e8-845a-e546b12a61d5.png)

Block size is unstable at first few min, but later tends to be at max - 10000 txs

![screen shot 2018-07-02 at 18 30 58](https://user-images.githubusercontent.com/1282182/42169948-37c988ba-7e26-11e8-8a0d-4c721de02f74.png)

**Comment by melekes** [comment] 2018-07-02 19:48
With mempool.recheck turned off and limited mempool (10000)

```sh
sed -i'' -e 's/^recheck = true/recheck = false/' ./mktemp/config/config.toml
sed -i'' -e "s/^size = 100000/size = $6/" ./mktemp/config/config.toml
```

![screen shot 2018-07-02 at 23 46 06](https://user-images.githubusercontent.com/1282182/42183250-23924946-7e52-11e8-9a58-cb022aab3d86.png)

There is a decline, although not so steep.

**Comment by melekes** [comment] 2018-07-03 08:21
![screen shot 2018-07-03 at 01 16 21](https://user-images.githubusercontent.com/1282182/42207571-4be44eee-7ebb-11e8-8184-b821073321d0.png)

It looks like indexing blocks can take a surprising amount of time (up to 23 sec.) and pauses become longer over time.

**Comment by melekes** [comment] 2018-07-03 09:39
Short summary:
1) There was an issue with tm-bench, which is now fixed https://github.com/tendermint/tendermint/issues/1835#issuecomment-401402231
2) given default mempool size - 100000, rechecking that many transactions (eventually mempool gets full) slows us down
3) sometimes indexing a block can take up to 20 sec. and the duration seems to increase over time (given constant load).

**Comment by ValarDragon** [comment] 2018-08-25 19:08
Given the lack of response in the goleveldb issue, is the resolution for that just to switch to cleveldb?

**Comment by melekes** [comment] 2018-08-26 04:26
> Given the lack of response in the goleveldb issue, is the resolution for that just to switch to cleveldb?

we may try to fix it ourselves or switch to another Golang DB

- https://symas.com/lmdb/
- https://github.com/coreos/bbolt
- https://github.com/dgraph-io/badger

**Comment by melekes** [comment] 2018-09-12 08:08
Performed the same set of tests with CLevelDB https://github.com/tendermint/tendermint/pull/2337: **no performance degradation**.

**Comment by melekes** [comment] 2018-09-12 09:29
OK, managed to fix it with goleveldb by increasing DB limits: https://github.com/tendermint/tendermint/pull/2370/files#diff-dce1ae536a4b73f300ab57af2affaab5R27

I don't know how to do this nicely without breaking `db.NewDB` abstraction.

**Comment by ebuchman** [comment] 2018-09-12 23:38
Interesting. Would be cool to see benchmarks with bolt and badger as well.

Go-ethereum is using `syndtr/goleveldb`, so it's relatively trusted, and we should discuss the options changes you linked above.

We probably won't want to use bolt: https://news.ycombinator.com/item?id=14336617. Mainly it's a lot slower because it provides higher guarantees that we don't need because we provide them at the consensus layer.

Badger looks really promising but it's also still young (1.0 was November 2017). I'd be interested in running nodes with it to try it out, but we probably need to prioritize a solid CLevelDB build story.

**Comment by melekes** [comment] 2018-09-17 18:03
TODO:

- [ ] Check with indexing turned off that we don't have perf. degredation
- [ ] See if the old versions of goleveldb have the same behavior (regression issue)
- [ ] Check if etcd-io/bbolt has the same issue
- [ ] How big a B+tree can be in bbolt (probably memory limited)
- [ ] How bloom-filter in LevelDB improves read efficiency?

**Comment by mdyring** [comment] 2018-10-03 09:14
Referencing https://github.com/cosmos/cosmos-sdk/issues/2131 to ensure that, in addition to looking at the performance characteristics of the underlying DB, consideration is given to *how* data is stored as well.

Specifically, the key used to reference each node in the DB should be immutable over the lifetime of the node (a unique integer value could fit nicely). This to avoid page fills and thus reorgs/compactions.

Sorry if this is obvious, just seemed natural to bring it up in the context of this issue.

**Comment by jackzampolin** [comment] 2019-06-22 00:31
This is some 🔥 work here @melekes

**Comment by melekes** [comment] 2019-06-22 06:11
bbolt is reported to be slower when fast-syncing.

**Comment by melekes** [comment] 2020-08-27 11:00
closed https://github.com/syndtr/goleveldb/issues/226. I'm no longer seeing pauses due to compaction or rather pauses are manageble - 2-3s (for a block with 5000 txs 250 bytes each).

![Screenshot 2020-08-27 at 14 55 14](https://user-images.githubusercontent.com/1282182/91434477-e6d8b180-e875-11ea-9d12-9a0d0e204dd7.png)

**Comment by melekes** [comment] 2020-08-27 11:14
Refs https://github.com/tendermint/tendermint/issues/3905#issuecomment-681854328

**Comment by melekes** [comment] 2020-08-27 11:47
latest master (5c62ab1) with default settings

I'm no longer observing time dependent performance degradation. However, long pauses are still present (for possible reasons and, hopefully, a fix refer to https://github.com/tendermint/tendermint/issues/3905).

![Screenshot 2020-08-27 at 15 42 36](https://user-images.githubusercontent.com/1282182/91438371-49cd4700-e87c-11ea-8911-d5c0fb015aa6.png)

If anyone is still experiencing this, please let us know!

**Closed by melekes** 2020-08-27 11:47 UTC
Labels: T:perf
