### ISSUE TITLE
whether dep problem ?

### ISSUE THREAD

**Issue by ying2025** [tendermint/tendermint#1677] opened 2018-06-03 10:14 UTC
When I install tendermint, I use VPN.  I did not install dep and gometalinter.v2. So I install them by
"go get -u github.com/golang/dep/cmd/dep" and "go get -u gopkg.in/alecthomas/gometalinter.v2".
But I cannot set run them, so I cope "dep" and "gometalinter.v2" to "/usr/local/go/bin" as following
![image](https://user-images.githubusercontent.com/28092539/40885446-bfb82554-6758-11e8-9cd8-a54ba833693f.png)
![image](https://user-images.githubusercontent.com/28092539/40885458-df6100ec-6758-11e8-9efd-99167499d9c9.png)

So I  can pass when I run "make get_tools"  command. But I cannot pass "make get_vendor_deps". I consider whether the problem is that I set wrong dep enviroment. Hoping you can give me advise. Thank you !

**Comment by xla** [comment] 2018-06-03 11:09
@ying2025 Please provide the output you get when running the failing command.

**Comment by ying2025** [comment] 2018-06-03 12:03
~/goApps/src/github.com/tendermint/tendermint$ make get_vendor_deps
--> Running dep
dep: WARNING: Unknown field in manifest: prune

**Comment by ying2025** [comment] 2018-06-03 13:01
Yes, I install dep by "go get -u gopkg.in/alecthomas/gometalinter.v2"

**Comment by xla** [comment] 2018-06-03 13:35
That’s not dep, also did you make sure the `make` command returns an error code?

**Comment by ying2025** [comment] 2018-06-03 14:48
Yes

**Comment by ying2025** [comment] 2018-06-04 06:21
It is normal when install cosmos-sdk using "make get_vendor_deps"
zhr@ubuntu:~/goApps/src/github.com/cosmos/cosmos-sdk$ make get_vendor_deps
--> Running dep ensure
dep: WARNING: Unknown field in manifest: prune
Gopkg.lock was already in sync with imports and Gopkg.toml
(1/49) Wrote github.com/spf13/jwalterweatherman@master
(2/49) Wrote github.com/tendermint/abci@v0.10.3
(3/49) Wrote github.com/spf13/cast@v1.2.0
(4/49) Wrote github.com/ebuchman/fail-test@master
(5/49) Wrote github.com/mitchellh/mapstructure@master
(6/49) Wrote github.com/pmezard/go-difflib@v1.0.0
(7/49) Wrote github.com/pkg/errors@v0.8.0
(8/49) Wrote github.com/pelletier/go-toml@v1.1.0
(9/49) Wrote github.com/tendermint/go-amino@0.9.9
(10/49) Wrote github.com/davecgh/go-spew@v1.1.0
(11/49) Wrote gopkg.in/yaml.v2@v2.2.1
(12/49) Wrote github.com/spf13/cobra@v0.0.3
(13/49) Wrote github.com/tendermint/ed25519@master
(14/49) Wrote github.com/bgentry/speakeasy@v0.1.0
(15/49) Wrote github.com/fsnotify/fsnotify@v1.4.7
(16/49) Wrote github.com/btcsuite/btcd@master
(17/49) Wrote github.com/go-logfmt/logfmt@v0.3.0
(18/49) Wrote github.com/spf13/pflag@v1.0.1
(19/49) Wrote github.com/spf13/viper@v1.0.2
(20/49) Wrote github.com/rcrowley/go-metrics@master
(21/49) Wrote github.com/stretchr/testify@v1.2.1
(22/49) Wrote github.com/syndtr/goleveldb@master
(23/49) Wrote github.com/go-kit/kit@v0.6.0
(24/49) Wrote github.com/go-stack/stack@v1.7.0
(25/49) Wrote github.com/spf13/afero@v1.1.0
(26/49) Wrote github.com/golang/snappy@master
(27/49) Wrote github.com/gorilla/websocket@v1.2.0
(28/49) Wrote github.com/golang/protobuf@v1.0.0
(29/49) Wrote github.com/gogo/protobuf@v1.0.0
(30/49) Wrote github.com/inconshreveable/mousetrap@v1.0
(31/49) Wrote github.com/jmhodges/levigo@master
(32/49) Wrote github.com/hashicorp/hcl@master
(33/49) Wrote github.com/mattn/go-isatty@v0.0.3
(34/49) Wrote github.com/tendermint/go-crypto@v0.6.2
(35/49) Wrote github.com/kr/logfmt@master
(36/49) Wrote github.com/tendermint/go-wire@v0.7.3
(37/49) Wrote github.com/howeyc/crc16@master
(38/49) Wrote google.golang.org/genproto@7fd901a49ba6a7f87732eb344f6e3c5b19d1b200
(39/49) Wrote github.com/magiconair/properties@v1.8.0
(40/49) Wrote github.com/tendermint/tmlibs@v0.8.3
(41/49) Wrote golang.org/x/crypto@master
(42/49) Wrote golang.org/x/net@master
(43/49) Wrote google.golang.org/grpc@v1.7.5
(44/49) Wrote github.com/gorilla/context@v1.1.1
(45/49) Wrote golang.org/x/text@v0.3.0
(46/49) Wrote golang.org/x/sys@master
(47/49) Wrote github.com/gorilla/mux@v1.6.2
(48/49) Wrote github.com/tendermint/iavl@v0.7.0
(49/49) Wrote github.com/tendermint/tendermint@v0.19.7-rc0

**Comment by melekes** [comment] 2018-06-04 08:11
Duplicate of #1660

**Closed by melekes** 2018-06-04 08:11 UTC
