### ISSUE TITLE
retract 0.35.9

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#9766] opened 2022-11-25 17:22 UTC
seems like 0.35.9 is still go gettable, we should retract it in order to avoid confusion of what latest is. 

```
/tmp/tmp.MczkUhGQ75 # go mod tidy
go: finding module for package github.com/tendermint/tm-db
go: finding module for package github.com/syndtr/goleveldb/leveldb/opt
go: finding module for package github.com/tendermint/tendermint/abci/types
go: finding module for package github.com/cosmos/gogoproto/proto
go: downloading github.com/syndtr/goleveldb v1.0.0
go: downloading github.com/tendermint/tendermint v0.35.9
```

**Comment by thanethomson** [comment] 2022-11-26 13:41
Duplicate of #9355.

**Closed by thanethomson** 2022-11-26 13:41 UTC
