### ISSUE TITLE
When operating in seedMode, Disconnected every 3 hours does not work.

### ISSUE THREAD

**Issue by qkrwnsgh1288** [tendermint/tendermint#2715] opened 2018-10-27 10:51 UTC
https://github.com/tendermint/tendermint/blob/master/p2p/pex/pex_reactor.go#L629
This point is not work correctly.
I think,
https://github.com/tendermint/tendermint/blob/master/p2p/conn/connection.go#L148
created variable is missing the current time setting.

**Comment by ebuchman** [comment] 2018-11-08 03:58
Can you clarify what the issue is here?

**Comment by qkrwnsgh1288** [comment] 2018-11-13 01:37
In crawlPeersRoutine, which is performed when seedMode is run, there is logic that disconnects the peer's state information at 3-hour intervals through the duration value. The duration value is calculated by referring to the created value of MConnection. When MConnection is created for the first time, the created value is not initiated, so it is not disconnected every 3 hours but every time it is disconnected. So, normal nodes are connected to seedNode and disconnected immediately, so address exchange does not work properly.

**Comment by melekes** [comment] 2018-12-11 12:38
@qkrwnsgh1288 thanks for pointing this out 💛 PR with a fix/feature was merged to develop. Will be shipped with 0.27.1 or 0.28.0 release (check the changelog).

**Closed by melekes** 2018-12-11 12:38 UTC
Labels: bug, p2p
