### ISSUE TITLE
conensus: Restarting node causes DataCorruptionError in WAL

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/tendermint#3295] opened 2019-02-11 17:56 UTC
(originally posted by @fkbenjamin in https://github.com/cosmos/cosmos-sdk/issues/3603)

Reproduced by @jackzampolin with `sudo systemctl stop gaiad && sudo systemctl start gaiad`

**Tendermint Version:** `v0.30.0-rc0`
**Gaia Version:** `v0.31.1`

## Summary of Bug 
 
On GoS6, I changed the values in gaiad.toml in two of my nodes (one validating node, one not-validating node). After stopping and restarting the node again immediately, I get the following:

```
I[2019-02-11|15:53:34.544] Starting ABCI with Tendermint                module=main
E[2019-02-11|15:53:35.878] Error dialing peer                           module=p2p err="dial tcp X:X:X:X:12345: i/o timeout"
E[2019-02-11|15:53:36.032] Corrupted entry. Skipping...                 module=consensus wal=/home/ubuntu/.gaiad/data/cs.wal/wal err="DataCorruptionError[failed to read data: EOF]"
E[2019-02-11|15:53:36.202] data has been corrupted in last height of consensus WAL module=consensus err="DataCorruptionError[failed to read data: EOF]" height=1944
E[2019-02-11|15:53:36.202] Encountered corrupt WAL file                 module=consensus err="DataCorruptionError[failed to read data: EOF]"
E[2019-02-11|15:53:36.202] Please repair the WAL file before restarting module=consensus
You can attempt to repair the WAL as follows:

----
WALFILE=~/.tendermint/data/cs.wal/wal
cp $WALFILE ${WALFILE}.bak # backup the file
go run scripts/wal2json/main.go $WALFILE > wal.json # this will panic, but can be ignored
rm $WALFILE # remove the corrupt file
go run scripts/json2wal/main.go wal.json $WALFILE # rebuild the file without corruption
----
E[2019-02-11|15:53:36.202] Error starting conS                          module=consensus err="DataCorruptionError[failed to read data: EOF]"
E[2019-02-11|15:53:36.669] Error dialing peer                           module=p2p err="dial tcp X:X:X:X:12345: connect: connection refused"
E[2019-02-11|15:53:37.559] Error dialing peer                           module=p2p err="dial tcp X:X:X:X:12345: i/o timeout"
E[2019-02-11|15:53:37.813] Connection failed @ recvRoutine (reading byte) module=p2p peer=censoredcensored@X:X:X:X:12345 conn=MConn{X:X:X:X:12345} err=EOF
E[2019-02-11|15:53:37.813] Stopping peer for error                      module=p2p peer="Peer{MConn{X:X:X:X:12345} censoredcensored out}" err=EOF
E[2019-02-11|15:53:38.146] Connection failed @ recvRoutine (reading byte) module=p2p peer=censoredcensored@X:X:X:X:12345 conn=MConn{X:X:X:X:12345} err=EOF
E[2019-02-11|15:53:38.146] Stopping peer for error                      module=p2p peer="Peer{MConn{X:X:X:X:12345} censoredcensored out}" err=EOF
E[2019-02-11|15:53:38.146] MConnection flush failed                     module=p2p peer=censoredcensored@X:X:X:X:12345 err="write tcp X:X:X:X:59324->X:X:X:X:12345: use of closed network connection"
E[2019-02-11|15:53:38.479] Connection failed @ recvRoutine (reading byte) module=p2p peer=censoredcensored@X:X:X:X:12345 conn=MConn{X:X:X:X:12345} err=EOF
```

This caused me to miss a few blocks on Game of Stakes 6. The issue was solved by stopping the node again, waiting for a few seconds and then restarting it.
## Steps to Reproduce
 
```
cosmos-sdk: 0.31.1
git commit: b9e523212ec47910a00db00be2f1b7935e201ee7
vendor hash: 85e6c5c7a700e822cccf169c97f4a3974312dfd1
go version go1.11.5 linux/amd64
```
1. Change value in gaiad.toml (although I don't think it has anything to do with this)
2. Stop Node
3. Immediately start node again with `gaiad start`
4. See corrupted WAL Errors
____
#### For Admin Use
 - [ ] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

**Comment by hendrikhofstadt** [comment] 2019-02-11 22:02
Can confirm this happened on our nodes as well.

Actually, do we really need to panic in the case that the WAL is corrupted? The cs-reactor could safely resume even with an incomplete replay.

**Comment by ebuchman** [comment] 2019-02-11 23:11
Whoops sorry folks.

> Do we really need to panic in the case that the WAL is corrupted?

We used to do just that, and were generally fine, but in some rare cases we couldn't recover (eg. #3089). So we changed it in #3246 to exit and return the information on how to manually fix the WAL file (if you run those commands, you should then be able to restart just fine).

That said, I believe the real fix here is to fsync on shutdown (#3043) to avoid the corruption. So only if we don't shut down gracefully will we be faced with this message.

Of course two things just occurred to me:
- we could probably have Tendermint just run that set of commands directly in-process to repair the corrupt WAL file and try again, so the user doesn't have to
- if we don't want or can't do that, we might be able to detect if we'll be able to recover despite the corrupt WAL, or if we really need to exit; but this will take more thought.

**Comment by melekes** [comment] 2019-02-13 04:32
Merged https://github.com/tendermint/tendermint/pull/3297 to develop.

**Comment by fkbenjamin** [comment] 2019-03-09 13:24
The issue appeared again yesterday on Cosmos v0.33.0 which uses Tendermint v0.30.1-dev0.

```
[[override]]
  name = "github.com/tendermint/tendermint"
  revision = "v0.31.0-dev0"
```

The issue therefore doesn't seem to be solved or Cosmos needs to be changed from `v0.31.0-dev0`to `v0.31.0` (I haven't yet checked if there is a difference in the two).

```
E[2019-03-08|17:29:20.218] Please repair the WAL file before restarting module=consensus
You can attempt to repair the WAL as follows:

----
WALFILE=~/.tendermint/data/cs.wal/wal
cp $WALFILE ${WALFILE}.bak # backup the file
go run scripts/wal2json/main.go $WALFILE > wal.json # this will panic, but can be ignored
rm $WALFILE # remove the corrupt file
go run scripts/json2wal/main.go wal.json $WALFILE # rebuild the file without corruption
----
E[2019-03-08|17:29:20.218] Error starting conS                          module=consensus err="DataCorruptionError[failed to read data: EOF (read: 44, wanted: 256)]"
```

**Comment by hendrikhofstadt** [comment] 2019-03-09 13:27
I can confirm we also saw this.

@ebuchman I don't think this was related to the WAL fsyncs. In some version ~0.29.0 this started to pop up. It never happened before even though the fsyncing was not properly implemented. So I guess the issue was introduced by a change.

**Comment by pbostrom** [comment] 2019-03-13 17:30
Still seeing this too:
```
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: E[2019-03-13|17:27:53.789] Corrupted entry. Skipping...                 module=consensus wal=/home/gaiad/.gaiad/data/cs.wal/wal err="DataCorruptionError[failed to read data: EOF (read: 7, wanted: 257)]"
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: E[2019-03-13|17:27:53.895] data has been corrupted in last height of consensus WAL module=consensus err="DataCorruptionError[failed to read data: EOF (read: 7, wanted: 257)]" height=82194
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: E[2019-03-13|17:27:53.895] Encountered corrupt WAL file                 module=consensus err="DataCorruptionError[failed to read data: EOF (read: 7, wanted: 257)]"
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: E[2019-03-13|17:27:53.895] Please repair the WAL file before restarting module=consensus
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: You can attempt to repair the WAL as follows:
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: ----
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: WALFILE=~/.tendermint/data/cs.wal/wal
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: cp $WALFILE ${WALFILE}.bak # backup the file
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: go run scripts/wal2json/main.go $WALFILE > wal.json # this will panic, but can be ignored
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: rm $WALFILE # remove the corrupt file
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: go run scripts/json2wal/main.go wal.json $WALFILE # rebuild the file without corruption
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: ----
Mar 13 17:27:53 ip-10-255-239-207 gaiad[4637]: E[2019-03-13|17:27:53.895] Error starting conS                          module=consensus err="DataCorruptionError[failed to read data: EOF (read: 7, wanted: 257)]"
```

**Comment by melekes** [comment] 2019-04-02 10:24
Can somebody post the actual WAL file here?

**Comment by davepuchyr** [comment] 2019-04-09 20:47
> Can somebody post the actual WAL file here?

[cs.wal.zip](https://github.com/tendermint/tendermint/files/3060896/cs.wal.zip)

```
[root@gaia gaia-13k3]$ gaiad version --long
cosmos-sdk: 0.34.0-rc2
git commit: c255764c4f1e274499a7b21d248c009391e9dee5
vendor hash: 
build tags: netgo ledger
go version go1.11.5 linux/amd64
```

```
[root@gaia gaia-13k3]$ systemctl status gaiad.service 
● gaiad.service - Cosmos Gaia Node
   Loaded: loaded (/etc/systemd/system/gaiad.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-04-09 20:11:41 UTC; 5min ago
  Process: 7679 ExecStopPost=/usr/bin/sync (code=exited, status=0/SUCCESS)
  Process: 7665 ExecStart=/opt/go/bin/gaiad start (code=exited, status=143)
 Main PID: 7665 (code=exited, status=143)
```
I'm certain that the wal corruption is due to the unclean shutdown of gaiad on SIGTERM/SIGINT (the exit code on those signals is 143 or 130, ie not 0).  The corruption happens using either a systemd-based restart of gaiad or terminal based (Ctrl+c) and immediate re-run of gaiad.  As you can see, I explicitly put a /usr/bin/sync in the systemd service ExecStopPost, which I believe means that [OnStop()](https://github.com/tendermint/tendermint/blob/master/consensus/wal.go#L161) in gaiad is not being called on shutdown.

**This is a very serious bug for small validators** because the missed block count is a crucial metric for judging validators and the unclean shutdown and subsequent missed blocks absolutely destroys any chance of a delegator choosing a small validator.

**Comment by kwunyeung** [comment] 2019-04-10 13:27
I can confirm it's still happening.

**Comment by mnugumanova** [comment] 2019-04-10 19:55
I saw it on the gaia-13003 too

**Comment by davepuchyr** [comment] 2019-04-18 17:54
It seems to me that missing blocks due to this issue is no longer an issue in gaiad v0.34.0!  (I still can't get a clean shutdown, though.)

```
gaiad version --long
cosmos-sdk: 0.34.0
git commit: 0f7877c23b407e24e56056469e90fe6b8a78d84c
vendor hash: b0ee613acca9a3a572b558d0481ec7baa008f732431392af81db3555c92c8dd7
build tags: netgo ledger
go version go1.11.5 linux/amd64
```
```
Apr 18 14:23:01 gaiad[14369]: I[2019-04-18|14:23:01.115] Executed block                               module=state height=142420 validTxs=0 invalidTxs=0
Apr 18 14:23:01 gaiad[14369]: I[2019-04-18|14:23:01.130] Committed state                              module=state height=142420 txs=0 appHash=91DCE0DA932906662E7E0D008E481466EFCB833586409A815F648EEAD6DDDFB9
Apr 18 14:23:07 gaiad[14369]: I[2019-04-18|14:23:07.051] Executed block                               module=state height=142421 validTxs=0 invalidTxs=0
Apr 18 14:23:07 gaiad[14369]: I[2019-04-18|14:23:07.066] Committed state                              module=state height=142421 txs=0 appHash=68397071B5AC7545E2917E9117C7F944F52DB89F436E286862887569D2582A38
Apr 18 14:23:08 systemd[1]: Stopping Cosmos Gaia Node...
Apr 18 14:23:08 systemd[1]: gaiad.service: Main process exited, code=exited, status=143/n/a
Apr 18 14:23:08 systemd[1]: gaiad.service: Failed with result 'exit-code'.
Apr 18 14:23:08 systemd[1]: Stopped Cosmos Gaia Node.
Apr 18 14:23:08 systemd[1]: Started Cosmos Gaia Node.
Apr 18 14:23:08 gaiad[14490]: I[2019-04-18|14:23:08.777] Starting ABCI with Tendermint                module=main
.
.
.
Apr 18 14:23:10 gaiad[14490]: E[2019-04-18|14:23:10.223] Corrupted entry. Skipping...                 module=consensus wal=/home/cosmos/.gaiad/data/cs.wal/wal err="DataCorruptionError[checksums do not match: read: 724598077, actual: 2728034289]"
Apr 18 14:23:10 gaiad[14490]: E[2019-04-18|14:23:10.223] Corrupted entry. Skipping...                 module=consensus wal=/home/cosmos/.gaiad/data/cs.wal/wal err="DataCorruptionError[length 1426701924 exceeded maximum possible value of 1048576 bytes]"
Apr 18 14:23:10 gaiad[14490]: E[2019-04-18|14:23:10.223] Corrupted entry. Skipping...                 module=consensus wal=/home/cosmos/.gaiad/data/cs.wal/wal err="DataCorruptionError[length 4199610359 exceeded maximum possible value of 1048576 bytes]"
.
.
.
Apr 18 14:23:10 gaiad[14490]: E[2019-04-18|14:23:10.686] Corrupted entry. Skipping...                 module=consensus wal=/home/cosmos/.gaiad/data/cs.wal/wal err="DataCorruptionError[length 1952804931 exceeded maximum possible value of 1048576 bytes]"
Apr 18 14:23:10 gaiad[14490]: E[2019-04-18|14:23:10.686] Corrupted entry. Skipping...                 module=consensus wal=/home/cosmos/.gaiad/data/cs.wal/wal err="DataCorruptionError[length 1958833632 exceeded maximum possible value of 1048576 bytes]"
Apr 18 14:23:10 gaiad[14490]: E[2019-04-18|14:23:10.686] Corrupted entry. Skipping...                 module=consensus wal=/home/cosmos/.gaiad/data/cs.wal/wal err="DataCorruptionError[failed to read data: EOF (read: 305515, wanted: 658184)]"
Apr 18 14:23:10 gaiad[14490]: E[2019-04-18|14:23:10.686] Error on catchup replay. Proceeding to start ConsensusState anyway module=consensus err="Cannot replay height 142422. WAL does not contain #ENDHEIGHT for 142421"
Apr 18 14:23:13 gaiad[14490]: I[2019-04-18|14:23:13.057] Executed block                               module=state height=142422 validTxs=0 invalidTxs=0
Apr 18 14:23:13 gaiad[14490]: I[2019-04-18|14:23:13.075] Committed state                              module=state height=142422 txs=0 appHash=C30C0B49DA2F164D8C4DC39990048C06A8EAA88134AA4D972392253C8E9E75C4
Apr 18 14:23:16 gaiad[14490]: I[2019-04-18|14:23:16.990] Executed block                               module=state height=142423 validTxs=0 invalidTxs=0
Apr 18 14:23:17 gaiad[14490]: I[2019-04-18|14:23:17.006] Committed state                              module=state height=142423 txs=0 appHash=07924879F345AE1D4F446B4898AFADC87CE646A143289C057C26ECCC8ABEBC95
```

This is a big deal for small validators!  Thank-you to whoever came up with the missing blocks workaround!!!

**Comment by ebuchman** [comment] 2019-05-07 17:50
So after I bit of testing I was able to confirm this issue still exists. However, it seems that restarting the node is sufficient for it to be able to sync properly again (though sometimes it may take multiple restarts).

So I think at least for now we should cause the node to exit when the WAL replay fails like this, rather than just printing the info and hanging like we do now. At least that way process managers can restart the service automatically, which should mitigate the problems.

We should still keep some issue open to further investigate what's causing this in the first place.

**Comment by ebuchman** [comment] 2019-05-10 19:09
So I believe this is actually a gaia issue: https://github.com/cosmos/cosmos-sdk/issues/4323

Follow up for the Tendermint side in #3656

**Comment by ebuchman** [comment] 2019-05-10 19:09
If anyone experiences this with a different application, or in the future once it's fixed gaia side, please open a new issue. Thanks!

**Closed by ebuchman** 2019-05-10 19:09 UTC
Labels: bug, cosmos, validator
