### ISSUE TITLE
Avoid unnecessary "Sum" field and duplication in pubkey serialization to JSON

### ISSUE THREAD

**Issue by webmaster128** [tendermint/tendermint#8583] opened 2022-05-19 20:13 UTC
The interface CosmJS is expecting for public keys from a few versions ago is

```ts
interface RpcPubkey {
  readonly type: string;
  /** base64 encoded */
  readonly value: string;
}
```

with types like `tendermint/PubKeyEd25519`. It seems like the response has changed in two ways: the type identifier was changed to `tendermint.crypto.PublicKey_Ed25519` and we now get a structure like this:

```
"validator_updates": [
  {
    "pub_key": {
      "Sum": {
        "type": "tendermint.crypto.PublicKey_Ed25519",
        "value": {
          "ed25519": "0kNlxBMpm+5WtfHIG1xsWatOXTKPLtmSqn3EiEIDZeI="
        }
      }
    },
    "power": "11418237"
  },
```

(see https://rpc.cosmos.network/block_results?height=10539773).

I wonder where this `Sum` field is coming from and why it is in the JSON. Also why is "ed25519" duplicated in a value and the value key?

Would it be possible to design this JSON once and then test against a defined JSON output in order to guarantee API stability?

**Comment by creachadair** [comment] 2022-05-19 20:42
That field is probably coming from incorrect marshaling of protobuf types as JSON. 

Can you give a bit more context about when you observed the difference? E.g., what version was it that worked as you expected, and what version shows this change?

**Comment by webmaster128** [comment] 2022-05-19 20:49
It just came up recently when users used the query for "block_results" on the Cosmos Hub (0.34.x). I think it is very well possible that out decoder is broken for all 0.34.x and we just never tested it against a backend with actual data in `validator_updates`. So at some point between the Amino days and 0.34.19 this changed.

I think it is fine that it changed in a minor version of Tendermint which we missed. But the format now does not look like the one you want to offer to JSON users.

**Comment by creachadair** [comment] 2022-05-19 22:14
It probably wasn't intended to change, my guess is that if it wasn't an oversight as you suggest, it was probably an unintended consequence of other work.

I suspect this is probably fixed in v0.35.x and beyond, but I'd like to test it to be sure. Is the way to reproduce this to issue any `block_results` request against a running node, or is there more that I'd need to set up to trigger this combination?

**Comment by webmaster128** [comment] 2022-05-20 06:25
You need to find a block that has entries in `validator_updates`. Since we don't have that in our local Tendermint client tests, we did not find this issue earlier. But it's probably best to write unit tests for the pubkey marshalling to check the current format.

**Comment by creachadair** [comment] 2022-05-20 19:12
This is not fixed in v0.35.x, but should be.

**Comment by creachadair** [comment] 2022-05-20 19:55
Ok, so the `"Sum"` field is an artifact of the protobuf JSON encoding issue I mentioned above. But from what you describe, that isn't the whole story. What this _should_ emit for a public key with the current encoding scheme is something like:

```json
"pub_key": {
   "type": "tendermint/PubKeyEd25519",
   "value": "0kNlxBMpm+5WtfHIG1xsWatOXTKPLtmSqn3EiEIDZeI="
}
```

That's how the key types defined in the `tendermint/tendermint/crypto` package work. You are probably right that this happened as a result of the swap away from Amino, but the protobuf encoding of the `oneof` field does not follow the same scheme: Protobuf uses its own naming scheme for the `"type"` field and uses the field name as the variant selector.

Fixing this for real may require us to shim the `ValidatorUpdate` type in the RPC interface so that it generates the Amino-compatible format. It seems like this has been in this state for quite a while.

**Comment by creachadair** [comment] 2022-05-20 20:06
I see part of the problem. There are two distinct representations for validator updates: The [ABCI `ValidatorUpdate`](https://github.com/tendermint/tendermint/blob/master/proto/tendermint/abci/types.proto#L458) is what we get in the `block_updates` response, but most other places we use the [`Validator`](https://github.com/tendermint/tendermint/blob/master/proto/tendermint/types/validator.proto#L15) message to represent updates (e.g., [in event items](https://github.com/tendermint/tendermint/blob/master/types/events.go#L231)).

The latter are generating the expected format, but the former are not (at least when translated into the RPC output). So we may need to transcribe them to get the outcome we want here. That may be the easiest approach.

**Closed** 2022-05-23 21:43 UTC
Labels: T:bug, C:rpc
