### ISSUE TITLE
p2p: unify MarkBad and exponential backoff in pex reactor

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1356] opened 2018-03-23 08:51 UTC
See https://github.com/tendermint/tendermint/pull/1349/files#diff-8c6b1a350a161ced01d68514ccda7484R415

**Comment by ebuchman** [comment] 2018-04-24 16:39
Copying in the comments from that thread:

"""
So the problem is that the addr might get removed from the AddrBook later once it's full, but it's still being tracked in attemptsToDial, and then will never get deleted ?

So our attemptsToDial map could get bloated with these bad peers.

I think these means we really do nee to unify the MarkBad mechanisms more intelligently.Maybe the AddrBook just needs access to the attemptsToDial somehow?

Let's open a new issue for it. It's not critical right now but it is important.
"""

This is also more follow up from https://github.com/tendermint/tendermint/issues/1304#issuecomment-374955032, which comment is maybe not completely correct given the above :)

**Comment by jackzampolin** [comment] 2019-06-21 23:56
I feel like this code has undergone significant refactor since this time. Going to close this issue. Please reopen if I'm crazy.

**Comment by cmwaters** [comment] 2021-11-18 13:53
PEX reactor was refactored as part of v0.35. Closing this issue as being stale

**Closed by cmwaters** 2021-11-18 13:53 UTC
Labels: T:bug, C:p2p
