### ISSUE TITLE
Data race on blocksync

### ISSUE THREAD

**Issue by p4u** [tendermint/tendermint#7729] opened 2022-01-29 22:47 UTC
Found a data race using `go run -race` while stressing the network.

The full log is attached to this issue.

```
WARNING: DATA RACE
Read at 0x00c000359238 by goroutine 28:
  runtime.racereadrange()
      <autogenerated>:1 +0x1b
  github.com/tendermint/tendermint/internal/consensus.(*Reactor).queryMaj23Routine()
      /home/p4u/go/pkg/mod/github.com/tendermint/tendermint@v0.35.1/internal/consensus/reactor.go:831 +0x1b5
  github.com/tendermint/tendermint/internal/consensus.(*Reactor).processPeerUpdate·dwrap·37()
      /home/p4u/go/pkg/mod/github.com/tendermint/tendermint@v0.35.1/internal/consensus/reactor.go:968 +0x47

Previous write at 0x00c00035923c by goroutine 171:
  github.com/tendermint/tendermint/internal/consensus.(*State).updateRoundStep()
      /home/p4u/go/pkg/mod/github.com/tendermint/tendermint@v0.35.1/internal/consensus/state.go:577 +0x510
  github.com/tendermint/tendermint/internal/consensus.(*State).updateToState()
      /home/p4u/go/pkg/mod/github.com/tendermint/tendermint@v0.35.1/internal/consensus/state.go:704 +0x4e6
  github.com/tendermint/tendermint/internal/consensus.(*Reactor).SwitchToConsensus()
      /home/p4u/go/pkg/mod/github.com/tendermint/tendermint@v0.35.1/internal/consensus/reactor.go:291 +0x124
  github.com/tendermint/tendermint/internal/blocksync/v0.(*Reactor).poolRoutine()
      /home/p4u/go/pkg/mod/github.com/tendermint/tendermint@v0.35.1/internal/blocksync/v0/reactor.go:504 +0x1e2c
  github.com/tendermint/tendermint/internal/blocksync/v0.(*Reactor).OnStart·dwrap·24()
      /home/p4u/go/pkg/mod/github.com/tendermint/tendermint@v0.35.1/internal/blocksync/v0/reactor.go:176 +0x46

Goroutine 28 (running) created at:
  github.com/tendermint/tendermint/internal/consensus.(*Reactor).processPeerUpdate()
      /home/p4u/go/pkg/mod/github.com/tendermint/tendermint@v0.35.1/internal/consensus/reactor.go:968 +0x967
  github.com/tendermint/tendermint/internal/consensus.(*Reactor).processPeerUpdates()
      /home/p4u/go/pkg/mod/github.com/tendermint/tendermint@v0.35.1/internal/consensus/reactor.go:1388 +0xf7
  github.com/tendermint/tendermint/internal/consensus.(*Reactor).OnStart·dwrap·27()
      /home/p4u/go/pkg/mod/github.com/tendermint/tendermint@v0.35.1/internal/consensus/reactor.go:212 +0x39
```
[Uploading data-race-tendermint.txt…]()

**Comment by tychoish** [comment] 2022-02-01 19:16
I initially thought that this was a simple shutdown ordering bug, and I thought that my PR above would help fix it, but I now believe that I initially miss-read the line numbers in the error message, and that this is actually something more interesting (and maybe slightly harder).

I'm not sure that this is a new bug in 0.35 and not just a long standing issue that is exacerbated by changes in the timing. This is probably little solace though. 

It looks like blocksync is modifying some consensus-internal data structures that aren't protected by mutexes. I tried some trivial fixes (just putting/using the mutex more in some relevant calls, and that lead to deadlocks, and I think while this is "correct" I suspect that it'll be pretty disruptive to take 

I think the problem, which is sort of a long standing complaint, is that when starting into blocksync, the consensus reactor is already running, and so both reactors can modify state at the same time. There's no reason that the consensus reactor needs to actually do any of this work until blocksync is done, so one possible solution is to signal that blocksync is over, and use that to start the go routines that cause the data race. 

I'll keep looking at this, but I don't have a good reproduction of the issue, to validate that the fix is actually a fix, If you have something reasonably self contained I'd love to see it! 
I don't have a good reproduction of

**Comment by p4u** [comment] 2022-02-01 22:57
Your proposed soluton makes sense IMHO.

Yeah, reproducing data races is hard... What I do is to run the benchmarking nodes with `go run -race ... 2> error.log`
After executing some benchmarks and stressing the network then I collect the error.log files to look for data races.

Once you make the potential-fix, let me know and I'll update our source.

**Comment by tychoish** [comment] 2022-02-01 22:58
> Your proposed soluton makes sense IMHO.
> 
> Yeah, reproducing data races is hard... What I do is to run the benchmarking nodes with `go run -race ... 2> error.log` After executing some benchmarks and stressing the network then I collect the error.log files to look for data races.
> 
> Once you make the potential-fix, let me know and I'll update our source.

I'll start looking into it shortly, but it's a bit non trivial and master has diverged somewhat which might make it take a bit longer than I'd like. 

I guess I'd like to also see what the `...` that you're running for the benchmark. :D

**Comment by peterbourgon** [comment] 2022-02-02 01:50
Don't use `go run` basically ever — just `go build` or `go install` with the `-race` flag to enable the race detector.

**Comment by tychoish** [comment] 2022-02-04 15:19
I believe that the tip of 0.35.x shouldn't suffer from this anymore. I'm going to go ahead and close this, but feel free to reopen or open a new ticket if it reoccurs.

**Closed by tychoish** 2022-02-04 15:19 UTC
