### ISSUE TITLE
Issues after upgrading from 0.31.5 -> 0.31.8

### ISSUE THREAD

**Issue by ruseinov** [tendermint/tendermint#3853] opened 2019-07-31 09:24 UTC
Some of the functionality that is using the jsonrpc client started throwing errors:

```
ABCIQuery: response ID (jsonrpc-client) does not match request ID (jsonrpc-client-NGjRHAU0)
``` 

It does seem that this code has been touched recently so I can't help but wonder if there might be a bug somewhere or should we use it differently?

Currently we are instantiating the client like this:

```
// NewHTTPConnection takes a URL and sends all requests to the remote node
func NewHTTPConnection(remote string) client.Client {
	// This uses a custom implementation with support for https/wss
	// We can make local changes easily in tools, and add them back
	// upstream as we just copied some classes over.
	return rpcclient.NewHTTP(remote, "/websocket")
}
```
which leads to id validation errors after the migration from v0.31.5 to v0.31.8.

I can't help but wonder whether it's a bug or something should be changed in terms of usage. I couldn't find any interface changes though.

**Comment by melekes** [comment] 2019-07-31 17:50
Commit: 90465f727 (PR https://github.com/tendermint/tendermint/pull/3534)
Version: v0.31.6

Don't understand why response ID does not match request ID... Maybe because the response is for another request made by some other client?

**Comment by ruseinov** [comment] 2019-08-01 07:55
> Don't understand why response ID does not match request ID... Maybe because the response is for another request made by some other client?

This is what our tests report. I have tried running an isolated test that instantiates the client once and does exactly one request - still the same problem.
It seems to only be happening with `ABCIQuery` though.

**Comment by ruseinov** [comment] 2019-08-01 08:39
@melekes It looks like the id that is being sent back is incorrect:
```
 main_test.go:42: cannot sign a multisig request: cannot get the next sequence number: ABCIQuery: response ID (jsonrpc-client) does not match request ID (jsonrpc-client-lz96HAkE)
```
Here we can see that we send with `jsonrpc-client-lz96HAkE` and get back `jsonrpc-client`, which should never happen as the client is always initialised with a hash. Looks like a bug to me.

**Comment by melekes** [comment] 2019-08-01 13:26
Could you try to reproduce the issue with https://github.com/tendermint/tendermint/pull/3858?

**Comment by ruseinov** [comment] 2019-08-01 14:25
@melekes Yeah, I'm backporting that now to see if it works.

**Comment by ruseinov** [comment] 2019-08-01 14:58
@melekes I can't really test this with 0.31.x, because I can't go get the tendermint module from my repo with `github.com/tendermint/tendermint` - url needs to match the module name :/

If you could backport this to 0.31.x just as a PR - I'd be able to fetch this from your repo by commit hash and verify.

**Comment by melekes** [comment] 2019-08-02 07:57
Sure, I will try to merge https://github.com/tendermint/tendermint/pull/3858 to master and then create a backport PR today.

**Comment by ruseinov** [comment] 2019-08-02 10:22
Thanks, I did try to figure it all out, but didn't want to mess with go mod internal storage, so figured I'd wait for the backport.

**Comment by ruseinov** [comment] 2019-08-13 18:47
@melekes I assume that other PR is not going to be backported, right? So at this point it's probably easier to stay on 31.5 and then upgrade to something that has all the fixes in.

**Comment by melekes** [comment] 2019-08-14 06:05
Yeah, I'm afraid you'll have to upgrade in order to test https://github.com/tendermint/tendermint/pull/3858.

**Comment by ruseinov** [comment] 2019-08-14 10:06
Got it. Going to see if we can squeeze that in.

**Comment by ruseinov** [comment] 2019-08-15 09:40
@melekes so this is going to be something like 0.33.x?
I'm wondering what to upgrade to currently, this is based roughly on `0.32.x`, right?

**Comment by melekes** [comment] 2019-08-15 10:40
> so this is going to be something like 0.33.x?

v0.33.0

**Comment by ebuchman** [comment] 2019-08-23 00:36
Trying to understand how this was even possible. @ruseinov did you update both your client and server node to v0.31.8 or just one or the other? Were you using the new batching feature from #3534? And really it only affected `/abci_query` ?

**Comment by ruseinov** [comment] 2019-08-23 06:41
I have not been using batching and this did pop up in tests, so it was that same tendermint version that is used for client.

**Comment by ebuchman** [comment] 2019-08-23 21:16
Is it at all possible there's another client running with the old software? Or can you give us a test we can use to reproduce?

**Comment by ruseinov** [comment] 2019-08-24 08:09
https://github.com/iov-one/weave/pull/927 there you go

**Comment by thanethomson** [comment] 2019-08-24 13:23
Does this not have something to do with [this line in the Weave code](https://github.com/iov-one/weave/blob/master/cmd/validators/main_test.go#L113)?

**Comment by ruseinov** [comment] 2019-08-24 22:04
@thanethomson I did not check this code path before because I was investigating the ones that were using the actual client. That particular test is failing because of this line, but if you look into other tests that are failing - they would be using the official client against the same version of tendermint, because both client and server are within tendermint dependency, so are the same version by design.

**Comment by thanethomson** [comment] 2019-08-24 22:57
Can you reproduce this with a minimal piece of Go code? (Simple Tendermint RPC client connecting to the Tendermint server)

**Comment by ruseinov** [comment] 2019-08-24 23:33
Yeah, I'm going to try and do this sometime soon.

**Comment by melekes** [comment] 2019-12-11 11:39
Should be fixed by https://github.com/tendermint/tendermint/pull/4141.

**Closed by melekes** 2019-12-11 11:39 UTC
Labels: bug, rpc
