### ISSUE TITLE
CI Failures

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#460] opened 2017-04-26 04:45 UTC
Let comments be failure from CI logs.

https://circleci.com/gh/tendermint/tendermint/970#tests/containers/0

```
* Test FailIndex 7
Starting persistent dummy and tendermint
[32mNOTE[0m[04-26|04:31:36] Loaded state                             [32mmodule[0m=dummy [32mblock[0m=21 [32mroot[0m=
[32mNOTE[0m[04-26|04:31:36] Waiting for new connection...            [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:36] Loaded PrivValidator                     [32mmodule[0m=types [32mfile[0m=/root/.tendermint_persist/priv_validator.json [32mprivValidator[0m="PrivValidator{B0DF30401832A10A791ED2AAC6DB4C40CFE70D99 LH:21, LR:0, LS:3}"
[34mINFO[0m[04-26|04:31:36] Starting multiAppConn                    [34mmodule[0m=proxy [34mimpl[0m=multiAppConn
[32mNOTE[0m[04-26|04:31:36] Accepted a new connection                [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:36] Waiting for new connection...            [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:36] Accepted a new connection                [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:36] Waiting for new connection...            [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:36] Accepted a new connection                [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:36] Waiting for new connection...            [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:36] ABCI Handshake                           [32mmodule[0m=consensus [32mappHeight[0m=21 [32mappHash[0m=
[32mNOTE[0m[04-26|04:31:36] ABCI Replay Blocks                       [32mmodule[0m=consensus [32mappHeight[0m=21 [32mstoreHeight[0m=21 [32mstateHeight[0m=21
[32mNOTE[0m[04-26|04:31:36] Completed ABCI Handshake - Tendermint and App are synced [32mmodule[0m=consensus [32mappHeight[0m=21 [32mappHash[0m=
[34mINFO[0m[04-26|04:31:36] Starting EventSwitch                     [34mmodule[0m=events [34mimpl[0m=EventSwitch
[36mDBUG[0m[04-26|04:31:36] addRound(round)                          [36mmodule[0m=consensus [36mround[0m=0
[34mINFO[0m[04-26|04:31:36] Starting Node                            [34mmodule[0m=node [34mimpl[0m=Node
[34mINFO[0m[04-26|04:31:36] Local listener                           [34mmodule[0m=p2p [34mip[0m=:: [34mport[0m=46656
[34mINFO[0m[04-26|04:31:36] Getting UPNP external address            [34mmodule[0m=p2p
[34mINFO[0m[04-26|04:31:39] Could not perform UPNP discover          [34mmodule[0m=p2p [34merror[0m="write udp4 0.0.0.0:50565->239.255.255.250:1900: i/o timeout"
[34mINFO[0m[04-26|04:31:39] Starting DefaultListener                 [34mmodule[0m=p2p [34mimpl[0m=Listener(@172.18.0.3:46656)
[34mINFO[0m[04-26|04:31:39] Starting P2P Switch                      [34mmodule[0m=p2p [34mimpl[0m="P2P Switch"
[34mINFO[0m[04-26|04:31:39] Starting MempoolReactor                  [34mmodule[0m=mempool [34mimpl[0m=MempoolReactor
[34mINFO[0m[04-26|04:31:39] Starting BlockchainReactor               [34mmodule[0m=blockchain [34mimpl[0m=BlockchainReactor
[34mINFO[0m[04-26|04:31:39] Starting ConsensusReactor                [34mmodule[0m=consensus [34mimpl[0m=ConsensusReactor
[32mNOTE[0m[04-26|04:31:39] ConsensusReactor                         [32mmodule[0m=consensus [32mfastSync[0m=false
[34mINFO[0m[04-26|04:31:39] Starting ConsensusState                  [34mmodule[0m=consensus [34mimpl[0m=ConsensusState
[34mINFO[0m[04-26|04:31:39] Starting WAL                             [34mmodule[0m=consensus [34mimpl[0m=WAL
[34mINFO[0m[04-26|04:31:39] Starting TimeoutTicker                   [34mmodule[0m=consensus [34mimpl[0m=TimeoutTicker
[36mDBUG[0m[04-26|04:31:39] Starting timeout routine                 [36mmodule[0m=consensus
[32mNOTE[0m[04-26|04:31:39] Catchup by replaying consensus messages  [32mmodule[0m=consensus [32mheight[0m=22
[32mNOTE[0m[04-26|04:31:39] Replay: New Step                         [32mmodule[0m=consensus [32mheight[0m=22 [32mround[0m=0 [32mstep[0m=RoundStepNewHeight
[32mNOTE[0m[04-26|04:31:39] Replay: Done                             [32mmodule[0m=consensus
[32mNOTE[0m[04-26|04:31:39] Starting RPC HTTP server on unix socket /go/src/github.com/tendermint/tendermint/rpc.sock [32mmodule[0m=rpcserver
[36mDBUG[0m[04-26|04:31:39] Received tick                            [36mmodule[0m=consensus [36mold_ti[0m="{Duration:0s Height:0 Round:0 Step:RoundStepUnknown}" [36mnew_ti[0m="{Duration:-2.003698313s Height:22 Round:0 Step:RoundStepNewHeight}"
[36mDBUG[0m[04-26|04:31:39] Timer already stopped                    [36mmodule[0m=consensus
[36mDBUG[0m[04-26|04:31:39] Scheduled timeout                        [36mmodule[0m=consensus [36mdur[0m=-2.003698313s [36mheight[0m=22 [36mround[0m=0 [36mstep[0m=RoundStepNewHeight
[32mNOTE[0m[04-26|04:31:39] Started node                             [32mmodule[0m=main [32mnodeInfo[0m="&{PubKey:PubKeyEd25519{B08B786E1A74C3CC5643CBE63AAA4A18F02FCE7F70CE99B03237B2EF5CAA2457} Moniker:anonymous Network:test-chain-4XAknx RemoteAddr: ListenAddr:172.18.0.3:46656 Version:0.9.2 Other:[wire_version=0.6.1 p2p_version=0.5.0 consensus_version=v1/0.2.2 rpc_version=0.7.0/3 tx_index=on rpc_addr=unix:///go/src/github.com/tendermint/tendermint/rpc.sock]}"
[34mINFO[0m[04-26|04:31:39] Timed out                                [34mmodule[0m=consensus [34mdur[0m=-2.003698313s [34mheight[0m=22 [34mround[0m=0 [34mstep[0m=RoundStepNewHeight
[36mDBUG[0m[04-26|04:31:39] Received tock                            [36mmodule[0m=consensus [36mtimeout[0m=-2.003698313s [36mheight[0m=22 [36mround[0m=0 [36mstep[0m=RoundStepNewHeight
[32mNOTE[0m[04-26|04:31:39] enterNewRound(22/0). Current: 22/0/RoundStepNewHeight [32mmodule[0m=consensus
[36mDBUG[0m[04-26|04:31:39] addRound(round)                          [36mmodule[0m=consensus [36mround[0m=1
[34mINFO[0m[04-26|04:31:39] enterPropose(22/0). Current: 22/0/RoundStepNewRound [34mmodule[0m=consensus
[34mINFO[0m[04-26|04:31:39] enterPropose: Our turn to propose        [34mmodule[0m=consensus [34mproposer[0m=B0DF30401832A10A791ED2AAC6DB4C40CFE70D99 [34mprivValidator[0m="PrivValidator{B0DF30401832A10A791ED2AAC6DB4C40CFE70D99 LH:21, LR:0, LS:3}"
[36mDBUG[0m[04-26|04:31:39] Received tick                            [36mmodule[0m=consensus [36mold_ti[0m="{Duration:-2.003698313s Height:22 Round:0 Step:RoundStepNewHeight}" [36mnew_ti[0m="{Duration:3s Height:22 Round:0 Step:RoundStepPropose}"
[36mDBUG[0m[04-26|04:31:39] Timer already stopped                    [36mmodule[0m=consensus
[36mDBUG[0m[04-26|04:31:39] Scheduled timeout                        [36mmodule[0m=consensus [36mdur[0m=3s [36mheight[0m=22 [36mround[0m=0 [36mstep[0m=RoundStepPropose
[34mINFO[0m[04-26|04:31:39] Signed proposal                          [34mmodule[0m=consensus [34mheight[0m=22 [34mround[0m=0 [34mproposal[0m="Proposal{22/0 1:89368E29CD82 (-1,:0:000000000000) /6816FDE20560.../}"
[36mDBUG[0m[04-26|04:31:39] Signed proposal block: Block{
  Header{
    ChainID:        test-chain-4XAknx
    Height:         22
    Time:           2017-04-26 04:31:39.591512705 +0000 UTC
    NumTxs:         0
    LastBlockID:    B241CAF789C6600E5ADE96D6F95598C01C52A2E2:1:75D69BD97121
    LastCommit:     E3D59F6E3EE917AAFD0ED50ABAC262E235293957
    Data:           
    Validators:     616AB4EB9707EBD2F18B1B96CDFCEBECD07CEAD0
    App:            
  }#E51EE2628BA0FA89EA98D62F8A03971651A67646
  Data{
    
  }#
  Commit{
    BlockID:    B241CAF789C6600E5ADE96D6F95598C01C52A2E2:1:75D69BD97121
    Precommits: Vote{0:B0DF30401832 21/00/2(Precommit) B241CAF789C6 /ED9BA833C263.../}
  }#E3D59F6E3EE917AAFD0ED50ABAC262E235293957
}#E51EE2628BA0FA89EA98D62F8A03971651A67646 [36mmodule[0m=consensus
[36mDBUG[0m[04-26|04:31:39] Broadcast                                [36mmodule[0m=p2p [36mchannel[0m=20 [36mmsg[0m="{ConsensusMessage:[NewRoundStep H:22 R:0 S:RoundStepPropose LCR:0]}"
[34mINFO[0m[04-26|04:31:39] Received complete proposal block         [34mmodule[0m=consensus [34mheight[0m=22 [34mhash[0m=E51EE2628BA0FA89EA98D62F8A03971651A67646
[34mINFO[0m[04-26|04:31:39] enterPrevote(22/0). Current: 22/0/RoundStepPropose [34mmodule[0m=consensus
[34mINFO[0m[04-26|04:31:39] Signed and pushed vote                   [34mmodule[0m=consensus [34mheight[0m=22 [34mround[0m=0 [34mvote[0m="Vote{0:B0DF30401832 22/00/1(Prevote) E51EE2628BA0 /8E6728688AEA.../}" [34merror[0m=nil
[36mDBUG[0m[04-26|04:31:39] Broadcast                                [36mmodule[0m=p2p [36mchannel[0m=20 [36mmsg[0m="{ConsensusMessage:[NewRoundStep H:22 R:0 S:RoundStepPrevote LCR:0]}"
[36mDBUG[0m[04-26|04:31:39] addVote                                  [36mmodule[0m=consensus [36mvoteHeight[0m=22 [36mvoteType[0m=1 [36mcsHeight[0m=22
[36mDBUG[0m[04-26|04:31:39] Broadcast                                [36mmodule[0m=p2p [36mchannel[0m=20 [36mmsg[0m="{ConsensusMessage:[HasVote VI:0 V:{22/00/1} VI:0]}"
[34mINFO[0m[04-26|04:31:39] Added to prevote                         [34mmodule[0m=consensus [34mvote[0m="Vote{0:B0DF30401832 22/00/1(Prevote) E51EE2628BA0 /8E6728688AEA.../}" [34mprevotes[0m="VoteSet{H:22 R:0 T:1 +2/3:E51EE2628BA0FA89EA98D62F8A03971651A67646:1:89368E29CD82 BA{1:X} map[]}"
[36mDBUG[0m[04-26|04:31:39] enterNewRound(22/0): Invalid args. Current step: 22/0/RoundStepPrevote [36mmodule[0m=consensus
[34mINFO[0m[04-26|04:31:39] enterPrecommit(22/0). Current: 22/0/RoundStepPrevote [34mmodule[0m=consensus
[32mNOTE[0m[04-26|04:31:39] enterPrecommit: +2/3 prevoted proposal block. Locking [32mmodule[0m=consensus [32mhash[0m=E51EE2628BA0FA89EA98D62F8A03971651A67646
[34mINFO[0m[04-26|04:31:39] Signed and pushed vote                   [34mmodule[0m=consensus [34mheight[0m=22 [34mround[0m=0 [34mvote[0m="Vote{0:B0DF30401832 22/00/2(Precommit) E51EE2628BA0 /52555BF36A10.../}" [34merror[0m=nil
[36mDBUG[0m[04-26|04:31:39] Broadcast                                [36mmodule[0m=p2p [36mchannel[0m=20 [36mmsg[0m="{ConsensusMessage:[NewRoundStep H:22 R:0 S:RoundStepPrecommit LCR:0]}"
[36mDBUG[0m[04-26|04:31:39] addVote                                  [36mmodule[0m=consensus [36mvoteHeight[0m=22 [36mvoteType[0m=2 [36mcsHeight[0m=22
[36mDBUG[0m[04-26|04:31:39] Broadcast                                [36mmodule[0m=p2p [36mchannel[0m=20 [36mmsg[0m="{ConsensusMessage:[HasVote VI:0 V:{22/00/2} VI:0]}"
[34mINFO[0m[04-26|04:31:39] Added to precommit                       [34mmodule[0m=consensus [34mvote[0m="Vote{0:B0DF30401832 22/00/2(Precommit) E51EE2628BA0 /52555BF36A10.../}" [34mprecommits[0m="VoteSet{H:22 R:0 T:2 +2/3:E51EE2628BA0FA89EA98D62F8A03971651A67646:1:89368E29CD82 BA{1:X} map[]}"
[36mDBUG[0m[04-26|04:31:39] enterNewRound(22/0): Invalid args. Current step: 22/0/RoundStepPrecommit [36mmodule[0m=consensus
[36mDBUG[0m[04-26|04:31:39] enterPrecommit(22/0): Invalid args. Current step: 22/0/RoundStepPrecommit [36mmodule[0m=consensus
[34mINFO[0m[04-26|04:31:39] enterCommit(22/0). Current: 22/0/RoundStepPrecommit [34mmodule[0m=consensus
[36mDBUG[0m[04-26|04:31:39] Broadcast                                [36mmodule[0m=p2p [36mchannel[0m=20 [36mmsg[0m="{ConsensusMessage:[NewRoundStep H:22 R:0 S:RoundStepCommit LCR:0]}"
[36mDBUG[0m[04-26|04:31:39] Broadcast                                [36mmodule[0m=p2p [36mchannel[0m=20 [36mmsg[0m="{ConsensusMessage:[CommitStep H:22 BP:1:89368E29CD82 BA:BA{1:X}]}"
[32mNOTE[0m[04-26|04:31:39] Finalizing commit of block with 0 txs    [32mmodule[0m=consensus [32mheight[0m=22 [32mhash[0m=E51EE2628BA0FA89EA98D62F8A03971651A67646 [32mroot[0m=
[34mINFO[0m[04-26|04:31:39] Block{
  Header{
    ChainID:        test-chain-4XAknx
    Height:         22
    Time:           2017-04-26 04:31:39.591 +0000 UTC
    NumTxs:         0
    LastBlockID:    B241CAF789C6600E5ADE96D6F95598C01C52A2E2:1:75D69BD97121
    LastCommit:     E3D59F6E3EE917AAFD0ED50ABAC262E235293957
    Data:           
    Validators:     616AB4EB9707EBD2F18B1B96CDFCEBECD07CEAD0
    App:            
  }#E51EE2628BA0FA89EA98D62F8A03971651A67646
  Data{
    
  }#
  Commit{
    BlockID:    B241CAF789C6600E5ADE96D6F95598C01C52A2E2:1:75D69BD97121
    Precommits: Vote{0:B0DF30401832 21/00/2(Precommit) B241CAF789C6 /ED9BA833C263.../}
  }#E3D59F6E3EE917AAFD0ED50ABAC262E235293957
}#E51EE2628BA0FA89EA98D62F8A03971651A67646 [34mmodule[0m=consensus
[34mINFO[0m[04-26|04:31:39] Executed block                           [34mmodule[0m=state [34mheight[0m=22 [34mvalid txs[0m=0 [34minvalid txs[0m=0
[34mINFO[0m[04-26|04:31:39] Saved state                              [34mmodule[0m=dummy [34mroot[0m=
[32mNOTE[0m[04-26|04:31:39] Saving block                             [32mmodule[0m=dummy [32mheight[0m=22 [32mroot[0m=
[34mINFO[0m[04-26|04:31:39] Committed state                          [34mmodule[0m=state [34mhash[0m=
[34mINFO[0m[04-26|04:31:39] Recheck txs                              [34mmodule[0m=mempool [34mnumtxs[0m=0
*** fail-test 7 ***
[36mDBUG[0m[04-26|04:31:39] addRound(round)                          [36mmodule[0m=consensus [36mround[0m=0
captured interrupt, exiting...
[34mINFO[0m[04-26|04:31:39] Stopping Node                            [34mmodule[0m=node [34mimpl[0m=Node
[32mNOTE[0m[04-26|04:31:39] Stopping Node                            [32mmodule[0m=node
[34mINFO[0m[04-26|04:31:39] Stopping P2P Switch                      [34mmodule[0m=p2p [34mimpl[0m="P2P Switch"
[34mINFO[0m[04-26|04:31:39] Stopping DefaultListener                 [34mmodule[0m=p2p [34mimpl[0m=Listener(@172.18.0.3:46656)
[34mINFO[0m[04-26|04:31:39] Stopping MempoolReactor                  [34mmodule[0m=mempool [34mimpl[0m=MempoolReactor
[34mINFO[0m[04-26|04:31:39] Stopping BlockchainReactor               [34mmodule[0m=blockchain [34mimpl[0m=BlockchainReactor
[34mINFO[0m[04-26|04:31:39] Stopping BlockPool                       [34mmodule[0m=blockchain [34mimpl[0m=BlockPool
[34mINFO[0m[04-26|04:31:39] Stopping ConsensusReactor                [34mmodule[0m=consensus [34mimpl[0m=ConsensusReactor
[34mINFO[0m[04-26|04:31:39] Stopping ConsensusState                  [34mmodule[0m=consensus [34mimpl[0m=ConsensusState
[34mINFO[0m[04-26|04:31:39] Stopping TimeoutTicker                   [34mmodule[0m=consensus [34mimpl[0m=TimeoutTicker
[34mINFO[0m[04-26|04:31:39] Closing rpc listener                     [34mmodule[0m=node [34mlistener[0m="&{fd:0xc4201e35e0 path:/go/src/github.com/tendermint/tendermint/rpc.sock unlink:true}"
[33mWARN[0m[04-26|04:31:39] Connection error                         [33mmodule[0m=abci-server [33merror[0m=EOF
./test/persist/test_failure_indices.sh: line 49: 11714 Killed                  $DUMMY_CMD
Starting persistent dummy and tendermint
rm: cannot remove '/go/src/github.com/tendermint/tendermint/rpc.sock': No such file or directory
[32mNOTE[0m[04-26|04:31:39] Loaded state                             [32mmodule[0m=dummy [32mblock[0m=22 [32mroot[0m=
[32mNOTE[0m[04-26|04:31:39] Waiting for new connection...            [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:39] Loaded PrivValidator                     [32mmodule[0m=types [32mfile[0m=/root/.tendermint_persist/priv_validator.json [32mprivValidator[0m="PrivValidator{B0DF30401832A10A791ED2AAC6DB4C40CFE70D99 LH:22, LR:0, LS:3}"
[34mINFO[0m[04-26|04:31:39] Starting multiAppConn                    [34mmodule[0m=proxy [34mimpl[0m=multiAppConn
[32mNOTE[0m[04-26|04:31:39] Accepted a new connection                [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:39] Waiting for new connection...            [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:39] Accepted a new connection                [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:39] Waiting for new connection...            [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:39] Accepted a new connection                [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:39] Waiting for new connection...            [32mmodule[0m=abci-server
[32mNOTE[0m[04-26|04:31:39] ABCI Handshake                           [32mmodule[0m=consensus [32mappHeight[0m=22 [32mappHash[0m=
[32mNOTE[0m[04-26|04:31:39] ABCI Replay Blocks                       [32mmodule[0m=consensus [32mappHeight[0m=22 [32mstoreHeight[0m=22 [32mstateHeight[0m=22
[32mNOTE[0m[04-26|04:31:39] Completed ABCI Handshake - Tendermint and App are synced [32mmodule[0m=consensus [32mappHeight[0m=22 [32mappHash[0m=
[34mINFO[0m[04-26|04:31:39] Starting EventSwitch                     [34mmodule[0m=events [34mimpl[0m=EventSwitch
[36mDBUG[0m[04-26|04:31:39] addRound(round)                          [36mmodule[0m=consensus [36mround[0m=0
[34mINFO[0m[04-26|04:31:39] Starting Node                            [34mmodule[0m=node [34mimpl[0m=Node
[34mINFO[0m[04-26|04:31:39] Local listener                           [34mmodule[0m=p2p [34mip[0m=:: [34mport[0m=46656
[34mINFO[0m[04-26|04:31:39] Getting UPNP external address            [34mmodule[0m=p2p
[34mINFO[0m[04-26|04:31:42] Could not perform UPNP discover          [34mmodule[0m=p2p [34merror[0m="write udp4 0.0.0.0:56479->239.255.255.250:1900: i/o timeout"
[34mINFO[0m[04-26|04:31:42] Starting DefaultListener                 [34mmodule[0m=p2p [34mimpl[0m=Listener(@172.18.0.3:46656)
[34mINFO[0m[04-26|04:31:42] Starting P2P Switch                      [34mmodule[0m=p2p [34mimpl[0m="P2P Switch"
[34mINFO[0m[04-26|04:31:42] Starting MempoolReactor                  [34mmodule[0m=mempool [34mimpl[0m=MempoolReactor
[34mINFO[0m[04-26|04:31:42] Starting BlockchainReactor               [34mmodule[0m=blockchain [34mimpl[0m=BlockchainReactor
[34mINFO[0m[04-26|04:31:42] Starting ConsensusReactor                [34mmodule[0m=consensus [34mimpl[0m=ConsensusReactor
[32mNOTE[0m[04-26|04:31:42] ConsensusReactor                         [32mmodule[0m=consensus [32mfastSync[0m=false
[34mINFO[0m[04-26|04:31:42] Starting ConsensusState                  [34mmodule[0m=consensus [34mimpl[0m=ConsensusState
[34mINFO[0m[04-26|04:31:42] Starting WAL                             [34mmodule[0m=consensus [34mimpl[0m=WAL
[34mINFO[0m[04-26|04:31:42] Starting TimeoutTicker                   [34mmodule[0m=consensus [34mimpl[0m=TimeoutTicker
[36mDBUG[0m[04-26|04:31:42] Starting timeout routine                 [36mmodule[0m=consensus
[32mNOTE[0m[04-26|04:31:42] Catchup by replaying consensus messages  [32mmodule[0m=consensus [32mheight[0m=23
[32mNOTE[0m[04-26|04:31:42] Replay: New Step                         [32mmodule[0m=consensus [32mheight[0m=23 [32mround[0m=0 [32mstep[0m=RoundStepNewHeight
[32mNOTE[0m[04-26|04:31:42] Replay: Done                             [32mmodule[0m=consensus
[32mNOTE[0m[04-26|04:31:42] Starting RPC HTTP server on unix socket /go/src/github.com/tendermint/tendermint/rpc.sock [32mmodule[0m=rpcserver
[36mDBUG[0m[04-26|04:31:42] Received tick                            [36mmodule[0m=consensus [36mold_ti[0m="{Duration:0s Height:0 Round:0 Step:RoundStepUnknown}" [36mnew_ti[0m="{Duration:-2.003523365s Height:23 Round:0 Step:RoundStepNewHeight}"
[36mDBUG[0m[04-26|04:31:42] Timer already stopped                    [36mmodule[0m=consensus
[36mDBUG[0m[04-26|04:31:42] Scheduled timeout                        [36mmodule[0m=consensus [36mdur[0m=-2.003523365s [36mheight[0m=23 [36mround[0m=0 [36mstep[0m=RoundStepNewHeight
[34mINFO[0m[04-26|04:31:42] Timed out                                [34mmodule[0m=consensus [34mdur[0m=-2.003523365s [34mheight[0m=23 [34mround[0m=0 [34mstep[0m=RoundStepNewHeight
Timed out waiting for tendermint to start
make: *** [test_integrations] Error 1

```

**Comment by ebuchman** [comment] 2017-05-02 15:50
https://circleci.com/gh/tendermint/tendermint/1014#artifacts/containers/0

```
* Passed Test for FailIndex 8



Passed Test: Persistence


* [08:05:21] running p2p tests on a local docker network
Failed to stop container (local_testnet_1): Error response from daemon: No such container: local_testnet_1
Failed to remove container (local_testnet_1): Error response from daemon: No such container: local_testnet_1
Failed to stop container (local_testnet_2): Error response from daemon: No such container: local_testnet_2
Failed to remove container (local_testnet_2): Error response from daemon: No such container: local_testnet_2
Failed to stop container (local_testnet_3): Error response from daemon: No such container: local_testnet_3
Failed to remove container (local_testnet_3): Error response from daemon: No such container: local_testnet_3
Failed to stop container (local_testnet_4): Error response from daemon: No such container: local_testnet_4
Failed to remove container (local_testnet_4): Error response from daemon: No such container: local_testnet_4
Error response from daemon: network local_testnet not found
Seeds: 172.57.0.101:46656,172.57.0.102:46656,172.57.0.103:46656,172.57.0.104:46656
53250908cde6a8e7cb77db43a23dba180745e87cab8ac866fb3c7fec3bed7711
starting tendermint peer ID=1
a6deab908d79790ce009dd4d500382290c59b3ae56919f12ab0390bac363981a
starting tendermint peer ID=2
38e1af47efee0c7f8129576203678e6ff9bbadd3ddd82f7557e332c3453a366b
starting tendermint peer ID=3
9c553701b05d5a3e8b7e9eb41987f97fbf9011b56ca13b0faafa8798694ce93a
starting tendermint peer ID=4
96e1a8bba7e5195a2dc9135b0d1a5d4c94f4bac7f2f4910f13714a9dba4db729
starting test client container with CMD=test/p2p/basic/test.sh 4
Waiting for nodes to come online


command cd "$PROJECT_PATH" && set -o pipefail && make test_integrations 2>&1 | tee test_integrations.log took more than 1800 seconds since last output

```

**Comment by adrianbrink** [comment] 2017-06-16 12:07
@ebuchman What is this issue about?

**Comment by ebuchman** [comment] 2017-07-09 18:28
https://circleci.com/gh/tendermint/tendermint/1229#artifacts/containers/0

[test_integrations.txt](https://github.com/tendermint/tendermint/files/1133960/test_integrations.txt)

Seems to have gotten stuck in `TestValidatorSetChanges`

**Comment by melekes** [comment] 2017-07-21 17:11
Got the same error (or rather deadlock) in https://github.com/tendermint/tendermint/pull/568/commits/52f8a1651ac6fb19498a82daafe3b861893f6396

**Comment by ebuchman** [comment] 2017-08-31 04:15
https://circleci.com/gh/tendermint/tendermint/1451#artifacts/containers/0

`Timed out waiting for transaction to be included in a block` in the first p2p test

[test_integrations.txt](https://github.com/tendermint/tendermint/files/1265756/test_integrations.txt)

**Comment by adrianbrink** [comment] 2017-10-16 17:53
It fails consistently for me on `develop` `a1e0f0b`. 

I ran it 3 times and every time it got stuck at `TestValidatorSetChanges`.

<img width="1249" alt="screen shot 2017-10-16 at 19 44 33" src="https://user-images.githubusercontent.com/11320251/31626930-be564ce8-b2ab-11e7-933b-aa87dd7ee212.png">

**Comment by zramsay** [comment] 2017-10-16 20:18
^ ya that's happened to me before as well. haven't been running the tests locally since

**Comment by adrianbrink** [comment] 2017-10-17 08:04
Indeterminism is the root of all evil.

**Comment by zramsay** [comment] 2017-12-21 12:04
duplicate of #908

**Closed by zramsay** 2017-12-21 12:04 UTC
Labels: Area: CI
