### ISSUE TITLE
mempool: spurious panic in the recheck callback

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6429] opened 2021-05-07 09:22 UTC
## Summary

This occurred during an e2e test I was running where a full node halted due to this [panic](https://github.com/tendermint/tendermint/blob/0b0914b3df50b06e6ca59fc76ccedb71d0bce8c1/mempool/clist_mempool.go#L431)

```
full03         | goroutine 29 [running]:
full03         | github.com/tendermint/tendermint/mempool.(*CListMempool).resCbRecheck(0xc0002c81a0, 0xc002bba190, 0xc0051ef400)
full03         | 	github.com/tendermint/tendermint/mempool/clist_mempool.go:432 +0x60e
full03         | github.com/tendermint/tendermint/mempool.(*CListMempool).globalCb(0xc0002c81a0, 0xc002bba190, 0xc0051ef400)
full03         | 	github.com/tendermint/tendermint/mempool/clist_mempool.go:279 +0x7a
full03         | github.com/tendermint/tendermint/abci/client.(*socketClient).didRecvResponse(0xc000533a20, 0xc0051ef400, 0x0, 0x0)
full03         | 	github.com/tendermint/tendermint/abci/client/socket_client.go:222 +0x202
full03         | github.com/tendermint/tendermint/abci/client.(*socketClient).recvResponseRoutine(0xc000533a20, 0x1633c20, 0xc0004f4728)
full03         | 	github.com/tendermint/tendermint/abci/client/socket_client.go:185 +0x107
full03         | created by github.com/tendermint/tendermint/abci/client.(*socketClient).OnStart
full03         | 	github.com/tendermint/tendermint/abci/client/socket_client.go:93 +0x2bc
```

In addition I have appended the manifest of the node:

```
  [node.full03]
    mode = "full"
    seeds = ["seed01"]
    database = "cleveldb"
    abci_protocol = "tcp"
    privval_protocol = "unix"
    start_at = 0
    fast_sync = ""
    state_sync = false
    persist_interval = 5
    snapshot_interval = 3
    retain_blocks = 0
    perturb = []
    log_level = ""
    disable_legacy_p2p = false
    queue_type = "priority"
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment] 2021-05-07 15:55
Can you post the full log? i.e. why it paniced? 

See https://github.com/tendermint/tendermint/issues/5439 and the relevant (attempted) fix https://github.com/tendermint/tendermint/pull/6124.

So if this is a `panic: Unexpected tx response from proxy during recheck`, then my patch clearly didn't fix this :(

**Comment by alexanderbez** [comment] 2021-05-07 15:57
Looks like it is the same error based on the stacktrace :-/

**Comment by alexanderbez** [comment] 2021-05-07 15:59
But this is coming from a different line in the socket client. Perhaps on line 222 we need to call `InvokeCallback` (my patch) instead?

**Comment by alexanderbez** [comment] 2021-05-07 16:39
Nor am I 😆. Are you able to reproduce this locally? If so, can you take a stab at trying `InvokeCallback` instead?

**Comment by cmwaters** [comment] 2021-05-07 16:48
Yeah I will see if I can reproduce it on Monday

**Comment by tychoish** [comment] 2022-06-15 20:50
I think given the current state of the code there are a few reasons why we should close this issue:

- this is an issue in the v0 mempool, which no longer in 0.36 or master
- the v0 mempool is not the default in 0.35, and this issue hasn't reoccurred 
- this issue has not reproduced on 0.34 at any point recently.
- in 0.36+ the socket client/server is *much* simpler, and based on the stack trace, none of the code implicated in this stack exists anymore, so I think the bug as stated can't exist anymore, and if something similar happens we'd be better served by opening a new issue.

**Closed by tychoish** 2022-06-15 20:50 UTC
