### ISSUE TITLE
API call /genesis include app_options

### ISSUE THREAD

**Issue by Greg-Szabo** [tendermint/tendermint#717] opened 2017-10-05 03:42 UTC
Feature request.
I would like the /genesis API call to return the app_options portion of the initial genesis.json.

This is required for cosmos-ui to be able to automatically download the merged genesis.json file from the testnet.

Tendermint 0.11 (develop branch)
basecoin 0.7.0 (develop branch)

**Comment by melekes** [comment] 2017-10-05 05:09
Thanks! Will do today.

**Comment by melekes** [comment] 2017-10-05 05:09
Duplicate of #564

**Closed by melekes** 2017-10-05 05:09 UTC
