### ISSUE TITLE
double-signing protection 

### ISSUE THREAD

**Issue by dlguddus** [tendermint/tendermint#4059] opened 2019-10-15 05:16 UTC
1. problem definition
- validators often mistakenly run duplicated validators to cause double-signing incident
- this proposed feature is to reduce the risk of mistaken double-signing incident
- when we think of such serious impact on double-signing incident, it is very reasonable to have multiple protection algorithm built in gaiad

2. new feature
- "gaiad start" has default setting to not participate on consensus, aka "fullnode as default"
- after starting gaiad, user enter command "gaiad activate-validation --from {key} --pubkey {valconspub}" with the signature from the {key}
- when gaiad receive this command, gaiad will look up recent(predifined block heights) consensus result and search for any consensus votes by given validator operator of the {key} AND also by given {valconspub}
- if there exists any vote from given validator operator or {valconspub}, gaiad will reject(or reconfirm) the activate-validation request and stays in fullnode
- if there exists no vote from given {key}, gaiad will transform this node from fullnode to validator which only use the private key paired with given {valconspub}
- when priv_validator_key changes while node is running as validator, the given {valconspub} and the new pubkey of priv_validator_key does not match therefore the node will not sign any consensus vote.
- all default setting can be customized by config.toml

3. B-Harvest wants to tackle this when we confirm enough support from community.

**Comment by marbar3778** [comment] 2019-10-15 07:57
I believe this can be considered a duplicate of https://github.com/tendermint/tendermint/issues/2237#issuecomment-520477659. We have discussed this on a few calls, just not gotten around to working on it.

**Comment by dlguddus** [comment] 2019-10-15 08:24
> I believe this can be considered a duplicate of [#2237 (comment)](https://github.com/tendermint/tendermint/issues/2237#issuecomment-520477659). We have discussed this on a few calls, just not gotten around to working on it.

We will review #2237 and provide updated spec so that it can include the "mode" abstraction! Thank you for connecting this!

**Comment by alexanderbez** [comment] 2019-10-15 13:57
Seems reasonable. One question I have surrounds the following:

```
when gaiad receive this command, gaiad will look up recent(predifined block heights) consensus result and search for any consensus votes by given validator operator of the {key} AND also by given {valconspub}
```

Will it only need to look past "unbonding period" # of blocks?

**Comment by dlguddus** [comment] 2019-10-15 14:03
@alexanderbez no. Practically it will be definitely much less than that. I am imagining like 50 blocks or less. 

The main purpose of this feature is to double check that another node is "currently" validating with same valoper or valconspub on the chain.

I think maximum look up height might be around several hundred blocks because this usecase does not need more.

**Comment by alexanderbez** [comment] 2019-10-15 14:58
I think you still have to be careful here though. The node could be offline > 50 blocks.

**Comment by dlguddus** [comment] 2019-10-15 15:11
That's true. Maybe we want to 

1) check whole # of unbonding period(this might take very long time tho..)
2) tell users that the most recent consensus vote height and time by given key
3) then re-ask user that he/she really wants to start validating(type "yes I really do") if vote exist in the period

How do you think?

**Comment by marbar3778** [comment] 2019-10-15 16:42
I think to start just have a node not be started with privval.json, the feature of switching is a bit harder and would have to have more in-depth thought and research, but would be eaiser solved when we have different modes for validating and full nodes

**Comment by dlguddus** [comment] 2019-10-15 18:05
Keep in mind that looking up recent voting is only possible if the node is synced well. Therefore, if we want to add the prevention method to check recent votes, the procedure should be fullnode>validator.

**Comment by dlguddus** [comment] 2019-11-01 08:51
below is our new spec of double-signing protection which also includes "mode" concept.

1. problem definition
- validators often mistakenly run duplicated validators to cause double-signing incident
- this proposed feature is to reduce the risk of mistaken double-signing incident
- when we think of such serious impact on double-signing incident, it is very reasonable to have multiple protection algorithm built in gaiad

2. tendermint mode v0.1

- the state machine has two modes to start : fullnode & validator
    - fullnode mode : fullnode mode does not have any capability to participate on consensus
    - validator mode : this mode is exactly same as existing state machine behavior. sync without voting on consensus, and participate consensus when fully synced.
- broad direction of implementation
    - state machine cmd flag "mode" : fullnode(default), validator
    - fullnode : in state machine, do not load "priv_validator_key.json"(consider non-existence)
    - validator : working same as existing state machine

3. double signing protection(only for validator mode)

- general objective
    - check recent consensus votes to prevent double-signing
    - allow users to ignore this checking feature
- broad direction of implementation
    - consensus vote check

        1) when a validator is transformed from syncing status to fully synced status, the state machine check recent N blocks to find out whether there exists consensus votes using the validator's consensus key

        2) if there exists votes from the validator's consensus key, exit state machine program

    - parameter setting(when starting state machine)

        1) --vote-check-height : how many blocks state machine looks back to check votes

        2) state machine ignore checking procedure when vote-check-height == 0

**Comment by melekes** [comment] 2020-08-27 04:58
Per https://github.com/tendermint/tendermint/pull/5147#discussion_r469351250, https://github.com/tendermint/tendermint/pull/5147 will not work without fast sync / state sync.

**Comment by tessr** [comment] 2020-11-13 17:17
I think this Issue is now effectively a duplicate of the one that's tracking the "Tendermint Modes" work, so I'm going to close it. But please re-open it if I misunderstood!

**Closed by tessr** 2020-11-13 17:17 UTC
Labels: S:proposal
