### ISSUE TITLE
Broken link in https://tendermint.com/docs/app-dev/ecosystem.html#ecosystem

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4110] opened 2019-11-05 09:51 UTC
We thank the community for their contributions and welcome the addition of new projects. A pull request can be submitted to this file to include your project.

https://github.com/tendermint/tendermint/blob/master/docs/app-dev/ecosystem.json

file does not exist

**Comment by marbar3778** [comment] 2019-11-06 15:34
Should we instead have a duplicate of the list in the awesome repo as json and then when people add there projects they have to also add it to json?

**Comment by melekes** [comment] 2019-11-06 15:37
Better to have one location imho

**Comment by marbar3778** [comment] 2019-11-06 15:52
yes the one location would be in the awesome repo

**Comment by melekes** [comment] 2019-11-06 16:43
no, I mean one document. I think the whole ecosystem page can migrate to awesome#README, but we should probably still link to it from the docs. Or have an ecosystem page in the docs.

**Closed** 2019-11-20 12:23 UTC
Labels: docs
