### ISSUE TITLE
Paniced on a Sanity Check: State mismatch for LastBlockHeight. Got 7, Expected 8

### ISSUE THREAD

**Issue by tglaeser** [tendermint/tendermint#409] opened 2017-02-18 00:03 UTC
**BUG REPORT**

**Tendermint version** :: 0.8.0

**ABCI app** :: self-written, not publicly available

Essentially, this is a Java app similar to the Go Counter app. In the context of the error, what it does is the following:
1. Stores the received `hash` value received in callback `requestBeginBlock`
2. Stores the received `height` value received in callback `requestEndBlock`
3.  Returns those two stored values via callback `requestInfo`

**Merkleeyes version** :: n/a

**Environment**
- **OS** :: Any
- **Install tools** :: Tendermint from source

**What happened**

I'm running `tendermint node`. After killing the process and starting it again, I'm seeing the following error. I assume this is a defect as `appHeight` and `storeHeight` are identical.

`NOTE[02-17|18:49:08] ABCI Handshake                           module=state appHeight=7 appHash=51FBECC7C1F24D2326CA74241C0374A7C132695D
NOTE[02-17|18:49:08] ABCI Replay Blocks                       module=state appHeight=7 storeHeight=7 stateHeight=7
panic: Paniced on a Sanity Check: State mismatch for LastBlockHeight. Got 7, Expected 8`

`goroutine 1 [running]:
panic(0x9b4320, 0xc042140cf0)
        C:/opt/go/src/runtime/panic.go:500 +0x1af
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common.PanicSanity(0x9b4320, 0xc042140cd0)
        C:/home/projects/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common/errors.go:26 +0xe7
github.com/tendermint/tendermint/state.(*State).LoadIntermediate(0xc0420da0b0)
        C:/home/projects/go/src/github.com/tendermint/tendermint/state/state.go:100 +0xa33
github.com/tendermint/tendermint/state.(*Handshaker).ReplayBlocks(0xc04213cd20, 0xc042008860, 0x14, 0x14, 0x7, 0xeb2a80, 0xc04214bd40, 0x14, 0x14)
        C:/home/projects/go/src/github.com/tendermint/tendermint/state/execution.go:369 +0x127d
github.com/tendermint/tendermint/state.(*Handshaker).Handshake(0xc04213cd20, 0xeb3dc0, 0xc0424fe3f0, 0x0, 0x0)
        C:/home/projects/go/src/github.com/tendermint/tendermint/state/execution.go:329 +0x48a
github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc0424fe3f0, 0xc042151700, 0x15)
        C:/home/projects/go/src/github.com/tendermint/tendermint/proxy/multi_app_conn.go:100 +0x20d
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common.(*BaseService).Start(0xc0424fe3f0, 0x0, 0x0, 0x0)
        C:/home/projects/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common/service.go:96 +0x54d
github.com/tendermint/tendermint/node.NewNode(0xeb4940, 0xc042151820, 0xc0424bfae0, 0xea75a0, 0xc042177bf0, 0x0)
        C:/home/projects/go/src/github.com/tendermint/tendermint/node/node.go:68 +0x48a
github.com/tendermint/tendermint/node.NewNodeDefault(0xeb4940, 0xc042151820, 0x1)
        C:/home/projects/go/src/github.com/tendermint/tendermint/node/node.go:51 +0xc1
github.com/tendermint/tendermint/node.RunNode(0xeb4940, 0xc042151820)
        C:/home/projects/go/src/github.com/tendermint/tendermint/node/node.go:350 +0x530
main.main()
        C:/home/projects/go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:42 +0x37a`

**What you expected to happen**

Expecting value `8` for `LastBlockHeight` seems to be wrong considering the last block height is consistently `7`. The 8th block was not even yet created, so why not simply building upon block `7`.

**How to reproduce it**

I assume this could be easily reproduced with a test or the Go Counter example if the `Info()` function only would return values for properties `"last_block_height"` and `"last_block_app_hash"`. I see the following reply for Tendermint / Go Counter client / server combination ...
`$ curl http://localhost:46657/abci_info
{"jsonrpc":"2.0","id":"","result":[113,{"data":"{\"hashes\":259,\"txs\":0}","version":"","last_block_height":0,"last_block_app_hash":""}],"error":""}`

**Comment by ebuchman** [comment] 2017-02-18 00:20
Thanks for this. Can you give me some more details please? https://github.com/tendermint/tendermint/blob/develop/.github/ISSUE_TEMPLATE

That said, I did just overhaul this system, and just finished. It's on `mock_app` branch. Should be merged to develop soon and to 0.9.0 release by next week.

**Comment by tglaeser** [comment] 2017-02-18 19:21
Sorry for not following the template. I updated the original report above. Thanks for your time...

**Comment by ebuchman** [comment] 2017-02-20 04:37
Thanks for the updated info.

I think this might be a problem: 

> Stores the received hash value received in callback requestBeginBlock

That hash is the block hash. What you want is the app hash (computed and returned in commit). I think this may have confused the logic for handling crashes. In any case, that logic has been much simplified in https://github.com/tendermint/tendermint/tree/mock_app and hopefully this problem is fixed there. I'll see if I can reproduce, and then if I can't.

**Comment by ebuchman** [comment] 2017-02-20 04:47
Ooo! Very easy to replicate. Yuk. It's fixed on `mock_app` branch. Expect it in v0.9 coming soon

**Comment by tglaeser** [comment] 2017-02-20 15:48
Yep, it looked like the usual OB1 error. Thanks for the quick return. Looking forward to the release of 0.9...

**Comment by srmo** [comment] 2017-02-23 10:45
@tglaeser Hi. Just wondering if you are using jTMSP aka jABCI https://github.com/jTendermint/jabci  as library to the node. If not, are you even aware of this implementation? I'd like to stay in touch to hear about how your ABCI implemenation looks like :)

**Comment by tglaeser** [comment] 2017-02-23 22:49
Well, yes and no. I started to look into this shortly after Tendermint 0.8 was released. Back then there was still jTMSP, which wasn't updated yet to work with 0.8, so I just forked it and did the necessary changes. I see that there is now jABCI compatible with 0.9, so I might give it another try...

**Comment by tglaeser** [comment] 2017-03-05 06:58
This works as expected with the latest `develop` branch. Feel free to close the ticket. Thanks.

**Comment by ebuchman** [comment] 2017-03-05 07:04
Sweet - thank you!

**Closed by ebuchman** 2017-03-05 07:04 UTC
