### ISSUE TITLE
ws: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#613] opened 2017-08-16 18:56 UTC
@melekes commented on [Thu Mar 23 2017](https://github.com/tendermint/go-rpc/issues/15)

version: fcea0cda21f64889be00a0f4b6d13266b1a76ee7

```
NOTE[03-23|16:32:23] New websocket connection                 module=rpcserver remote=127.0.0.1:61890
NOTE[03-23|16:32:23] Failed to read from connection           module=rpcserver remote=127.0.0.1:61727 err="websocket: close 1006 (abnormal closure): unexpected EOF"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1091ad2]

goroutine 36681 [running]:
time.(*Ticker).Stop(0x0)
        /usr/local/go/src/time/tick.go:46 +0x22
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server.(*wsConnection).OnStop(0xc422995680)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server/handlers.go:373 +0x6d
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common.(*BaseService).Stop(0xc422995680, 0x16f6eee)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-common/service.go:117 +0x68
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server.(*wsConnection).readRoutine(0xc422995680)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server/handlers.go:444 +0xd51
created by github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server.(*wsConnection).OnStart
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-rpc/server/handlers.go:346 +0x45
```

**Comment by odeke-em** [comment] 2017-08-26 02:04
Looks like we literally invoked a nil timer, of which an almost similar stacktrace can be reproduced with this snippet https://play.golang.org/p/ngmylMOkcK or inlined
```go
package main

import (
	"time"
)

func main() {
	var t *time.Ticker
	t.Stop()
}
```

**Comment by odeke-em** [comment] 2017-08-26 02:08
@zramsay unfortunately as you probably knew before me, we deprecated `go-rpc`
<img width="1179" alt="screen shot 2017-08-25 at 8 05 38 pm" src="https://user-images.githubusercontent.com/4898263/29737765-f7f42a3c-89d0-11e7-930b-b68ec2bc84b8.png">

and the only vestiges of `go-rpc` are changelog mentions, please see below:
```shell
$ grep -Rni 'go-rpc' *
basecoin/vendor/github.com/tendermint/tendermint/CHANGELOG.md:96:- Merge `tendermint/go-p2p -> tendermint/tendermint/p2p` and `tendermint/go-rpc -> tendermint/tendermint/rpc/lib`
basecoin/vendor/github.com/tendermint/tendermint/CONTRIBUTING.md:54:especially `go-p2p` and `go-rpc`, as their versions are referenced in tendermint core.
ethermint/vendor/github.com/tendermint/tendermint/CHANGELOG.md:113:- Merge `tendermint/go-p2p -> tendermint/tendermint/p2p` and `tendermint/go-rpc -> tendermint/tendermint/rpc/lib`
ethermint/vendor/github.com/tendermint/tendermint/CONTRIBUTING.md:54:especially `go-p2p` and `go-rpc`, as their versions are referenced in tendermint core.
tendermint/CHANGELOG.md:113:- Merge `tendermint/go-p2p -> tendermint/tendermint/p2p` and `tendermint/go-rpc -> tendermint/tendermint/rpc/lib`
tendermint/CONTRIBUTING.md:54:especially `go-p2p` and `go-rpc`, as their versions are referenced in tendermint core.
```

Perhaps we should close this issue as timed out and in the future if it comes up, cross reference it.

**Comment by zramsay** [comment] 2017-08-26 02:16
this issue was moved while consolidating the open issues. I think the issue is to change that behaviour (i.e. it should not panic)

**Comment by ebuchman** [comment] 2017-08-28 18:24
Can this behaviour be reproduced ?

**Comment by odeke-em** [comment] 2017-08-28 18:30
@ebuchman plausibly, and I suspect that the server quit right during connection setup which IMHO would explain why a ticker would be nil as in https://github.com/tendermint/tendermint/issues/613#issuecomment-325073259 and also for the abnormal close in the stack
```
NOTE[03-23|16:32:23] Failed to read from connection           module=rpcserver remote=127.0.0.1:61727 err="websocket: close 1006 (abnormal closure): unexpected EOF"
```

Sometime when we get the time, I'd like to reproduce it with a crafted test but I figured I'd spend time working on the urgent issues that are already open, since no one else has reported this ever since March 2017(5 months ago), plus recreating it would be time consuming, I think.

**Comment by ebuchman** [comment] 2017-09-21 18:22
Seems this has been fixed over some refactoring.

**Closed by ebuchman** 2017-09-21 18:22 UTC
