### ISSUE TITLE
mempool: "weird stuff" when sending transaction batches

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5796] opened 2020-12-15 06:43 UTC
Reported via https://discord.com/channels/669268347736686612/669283915743232011/786256976724230215

> I have no idea what's actually happening inside the mempool, but something is very broken. In addition to the problem described above, I also observed internal mempool loops (transactions that are invalid being executed infinite times by checkTx), node disconnections (for bad behavior?) and weird stuff.

> I have reverted the @melekes PR on 0.34.0 and everything seems to go to normal: https://github.com/vocdoni/tendermint/tree/revert_batch_txs

**Comment by p4u** [comment] 2020-12-15 09:31
I am pretty sure that #5773 have something to do with the behavior I observed. However I reproduced this issue using the same `MaxBatchBytes` value for all blockchain nodes. 

Here a Grafana snapshot that might help to understand what is going on: https://snapshot.raintank.io/dashboard/snapshot/tghfYhI8TbdbChcgxlBh9a3gAVp2BspS?viewPanel=26&orgId=2
The node named "gw2" is the one originating the transactions, it has a bigger mempool (150k). In the other side, the "miners" have a smaller mempool of 5k.

See how gw2 mempool is full of transactions, the other nodes starts filling their own mempool and then suddenly stop receiving transactions. For the next minutes gw2 will still have transactions to send but other nodes won't accept them anymore.

I did not see anything special on the logs, but it looks like for some reason then gw2 tries to send a transaction batch to the other nodes, it gets disconnected (probably batch is too big or the check is not correctly performed).

After reducing the `MaxBatchBytes` to a smaller number, this behavior stops happening however I can see many transactions in loop executing `checkTx()`. So it kind of works (all transactions end up being processed by validators) but still the mempool do very weird stuff which does not seem very healthy. 

I reverted the Batch transactions commit https://github.com/vocdoni/tendermint/tree/revert-batch-txs
Then I executed the same test again and everything worked smooth (as expected), no more transaction loops or p2p disconnects. 

I think there is something very wrong on the batch TX implementation and I'd recommend to revert it until the problem is found.

**Comment by melekes** [comment] 2020-12-15 13:46
My current theory is that the `flowrate` lib we're using to control flow (multiplex over a single TCP connection) was not designed w/ large blobs (1MB batch of txs) in mind. We'll either need to fix it or revert the batch change, which will be a breaking change 😞

**Comment by erikgrinaker** [comment] 2020-12-15 13:49
> revert the batch change, which will be a breaking change

Would it help to revert to sending batches of size 1? That shouldn't require protocol changes, at least.

**Comment by melekes** [comment] 2020-12-15 13:54
> Would it help to revert to sending batches of size 1? That shouldn't require protocol changes, at least.

yes, that's possible 👍

**Comment by p4u** [comment] 2020-12-15 15:55
I think that would explain that reducing the `MaxBatchBytes` the problem was kind of fixed in my tests. However, I still observed not normal behaviors on the mempool (loops), so I'd recommend to deeply test and check the mempool before closing this issue.

**Closed** 2020-12-21 15:17 UTC
Labels: C:mempool, T:bug-unconfirmed
