### ISSUE TITLE
nil-pointer in TestReactorConcurrency mempool test

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#7481] opened 2021-12-20 20:58 UTC
```
--- FAIL: TestReactorConcurrency (0.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xda1e6a]

goroutine 3091 [running]:
testing.tRunner.func1.2({0xf43040, 0x180f150})
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1212 +0x3b6
panic({0xf43040, 0x180f150})
	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/panic.go:1047 +0x266
github.com/tendermint/tendermint/internal/libs/clist.(*CElement).Prev(0x0)
	/home/runner/work/tendermint/tendermint/internal/libs/clist/clist.go:125 +0x2a
github.com/tendermint/tendermint/internal/libs/clist.(*CList).Remove(0xc0024175e0, 0x0)
	/home/runner/work/tendermint/tendermint/internal/libs/clist/clist.go:356 +0x52
github.com/tendermint/tendermint/internal/mempool.(*TxMempool).removeTx(0xc0000149c0, 0xc0024a7a40, 0x0)
	/home/runner/work/tendermint/tendermint/internal/mempool/mempool.go:795 +0x1fe
github.com/tendermint/tendermint/internal/mempool.(*TxMempool).Flush(0xc0000149c0)
	/home/runner/work/tendermint/tendermint/internal/mempool/mempool.go:331 +0x1a9
github.com/tendermint/tendermint/internal/mempool.TestReactorConcurrency(0xc0024504e0)
	/home/runner/work/tendermint/tendermint/internal/mempool/reactor_test.go:274 +0x22f
testing.tRunner(0xc0024504e0, 0x1177430)
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1306 +0x727
```

Observed [here](https://github.com/tendermint/tendermint/runs/4585500505?check_suite_focus=true)

**Comment by tychoish** [comment] 2022-01-13 16:00
I just ran this test a few hundred times and couldn't reproduce this failure.

Anecdotally, I also haven't seen this fail in CI in a long time, so I'm going to go ahead and close this case.

**Closed by tychoish** 2022-01-13 16:00 UTC
