### ISSUE TITLE
evidence: potential scenario where lunatic validator can be falsely created

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5200] opened 2020-08-04 09:20 UTC
## Problem Definition

I could be missing an essential part of this process that prevents this, but if a block is proposed in one round and a few vote on it but it doesn't get enough votes to continue and then a new and different block is proposed in a later round that does get enough votes and is committed on the chain, could someone take those previous votes for the first block and submit lunatic validator evidence against those validators because they voted on a block that differs to the one that eventually got committed?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by erikgrinaker** [comment] 2020-08-04 10:43
I don't think so, because the commit [includes the round index](https://github.com/tendermint/tendermint/blob/66ed8ec39d55d8d4e2ad7a429a678fe4d9513ab0/proto/tendermint/types/types.proto#L112). Votes in round n are independent of votes in round n+1.

**Comment by cmwaters** [comment] 2020-08-04 11:10
Sure that might be the case but Lunatic validator evidence doesn't contain the commit nor does any of the logic. It's just:

```
type LunaticValidatorEvidence struct {
	Header             *Header `json:"header"`
	Vote               *Vote   `json:"vote"`
	InvalidHeaderField string  `json:"invalid_header_field"`
}
```

**Comment by erikgrinaker** [comment] 2020-08-04 11:17
The vote contains the round, which can be checked against the block data.

**Comment by cmwaters** [comment] 2020-08-04 11:20
So are you saying that one of our checks should be that the round of the commit for the block that the full node has should be equal to the round of the vote within the lunatic validator evidence?

**Comment by erikgrinaker** [comment] 2020-08-04 11:37
I don't know all of the details here off the top of my head, and you should probably check with Informal, but yes, the round must be taken into account when verifying lunatic validator evidence. Casting votes in multiple rounds is valid and expected behavior and should not be punished. Casting multiple votes in a _single_ round should be punished, even if this was not the final round that got committed.

**Comment by cmwaters** [comment] 2020-08-04 11:49
If we have this check in place (that the rounds should be equal) then an actual lunatic validator attack might want to forge a block with a commit at a different round to the one on the main chain hence making the evidence itself invalid. If we don't have the check in place then votes in previous rounds for different blocks could be used to wrongly accuse someone of being a lunatic validator. I also may be missing details but I want to make sure that this can't happen. 

Perhaps @ebuchman or @josef-widder can provide some light on whether this is actually a problem or not.

**Comment by josef-widder** [comment] 2020-08-04 13:04
I think also @milosevic can add something here. 

I believe the case you described is linked to F3 discussed in the [accountability document](https://github.com/tendermint/spec/blob/master/spec/consensus/light-client/accountability.md#flip-flopping), and called back to the past, and a special case of amnesia. If there are +1/3 faults, the faulty nodes can generate a (light client) fork, and someone can consequently submit this fork as evidence. However, it is the responsibility of the [challenge/response](https://docs.google.com/document/d/11ZhMsCj3y7zIZz4udO9l25xqb0kl7gmWqNpGVRzOeyY/edit?usp=sharing) protocol to make sure that correct processes that changed their minds are not wrongfully slashed. In particular, the correct nodes will have to prove that at a higher round they received +2/3 messages that supported another block, so that it was "legal" to vote on a different block in a later round.

**Comment by ebuchman** [comment] 2020-08-04 13:15
See `Valid vs Invalid` in https://github.com/tendermint/tendermint/issues/5083

Blocks from prior rounds are `Valid` with respect to the chain (they have correct ValidatorHash, NextValidatorHash, AppHash, etc.) and cannot be used in lunatic attacks. They require equivocation/amnesia.

If I'm not mistaken, any lunatic attack involves at least a fake ValidatorHash

**Comment by cmwaters** [comment] 2020-08-04 13:31
Okay good - just checking 😄  - The fact that these values a predetermined by the block before means there shouldn't be a case where any validator voting for a different block (in any round) during consensus could be wrongly accused as a lunatic validator.

**Closed** 2020-08-04 13:32 UTC
Labels: C:evidence
