### ISSUE TITLE
Tendermint node restart after app failure sometimes doesn't work

### ISSUE THREAD

**Issue by surajpayu** [tendermint/tendermint#350] opened 2017-01-03 09:34 UTC
I have 4 nodes running. Each of them is mapped to tmsp app. In one of the tmsp app tree got corrupted and merkle root hash was different. All the other nodes started giving following warning
```
NOTE[01-03|09:31:42] enterNewRound(64429/20). Current: 64429/19/RoundStepPrecommit module=consensus
WARN[01-03|09:31:43] enterPrevote: ProposalBlock is invalid   module=consensus error="Wrong Block.Header.AppHash.  Expected 7820B976E6E7FC55A9124B7D94B6F31E8FFE0179, got 87A01D3C30FAA6F239AC114F6D24840447106690"
NOTE[01-03|09:31:54] enterNewRound(64429/21). Current: 64429/20/RoundStepPrecommit module=consensus
```

After this, we are not able to produce any new block. The system is never able to recover. We need to reset everything and start it from scratch.

**Comment by ebuchman** [comment] 2017-01-03 18:38
Are you sure the corruption didn't happen on every app? Is every node a validator? If there are 4 separate validators and only one is corrupted, when that one proposes, the hash should be wrong and everyone rejects it. Then they should go to the next round with a new proposer who will propose a correct block, unless its app is also corrupt

**Comment by surajpayu** [comment] 2017-01-04 07:25
I had 4 validators running, i stopped TMSP app for one on validator for some time. When i stopped the app, the corresponding validator crossed. I started the app and node after some time,  my app sent wrong root hash as my earlier db got wiped out. All 4 nodes started complaining of  ProposalBlock is invalid module=consensus error="Wrong Block.Header.AppHash. The system could never recover.

**Comment by melekes** [comment] 2017-01-20 15:34
Tried to replicate this by extending consensus/state_test.go `TestBadProposal` with:

```
	<-newRoundCh

	re := <-proposalCh
	rs := re.(types.EventDataRoundState).RoundState.(*RoundState)

	prop := rs.Validators.Proposer()
	if !bytes.Equal(prop.Address, cs1.privValidator.GetAddress()) {
		t.Fatalf("expected proposer to be validator %d. Got %X", 0, prop.Address)
	}
```

During the second round, another validator (correct one) becomes a proposer and successfully commits a new block.

Will try to replicate this using p2p/docker tests.

**Comment by melekes** [comment] 2017-01-24 13:34
@surajpayu full log would be very helpful! but I guess, you don't have it now.

**Comment by melekes** [comment] 2017-01-24 14:26
I modified fast_sync test to remove `dummy.db`:

```
docker stop local_testnet_$ID
docker start local_testnet_$ID
docker exec local_testnet_$ID ls -lR "./test/p2p/data/mach$ID/core/data/"
echo "==> Purging data dir"
docker exec local_testnet_$ID rm -rf "./test/p2p/data/mach$ID/core/data/dummy.db"
```

There is an error in the log (different than above) `Error invalid proposal POL round`, but **the system is making progress**.

```
NOTE[01-24|14:18:21] Replay: Done                             module=consensus
NOTE[01-24|14:18:21] enterNewRound(8/0). Current: 8/0/RoundStepNewHeight module=consensus
NOTE[01-24|14:18:22] enterPrecommit: No +2/3 prevotes during enterPrecommit. Precommitting nil. module=consensus
WARN[01-24|14:18:22] Attempt to finalize failed. We don't have the commit block. module=consensus
NOTE[01-24|14:18:22] Finalizing commit of block with 0 txs    module=consensus height=8 hash=D29A7B0945189D781336139F5E89B48DF0AD2357 root=
NOTE[01-24|14:18:22] Saving block                             module=dummy height=8 root=
WARN[01-24|14:18:22] Need to set a buffer and log.Warn() here for sanity. module=consensus startTime=2017-01-24T14:18:23+0000 now=2017-01-24T14:18:22+0000
NOTE[01-24|14:18:22] enterNewRound(9/0). Current: 9/0/RoundStepNewHeight module=consensus
NOTE[01-24|14:18:22] enterPrecommit: +2/3 prevoted for nil.   module=consensus
EROR[01-24|14:18:22] Error with msg                           module=consensus type=*consensus.ProposalMessage peer= error="Error invalid proposal POL round" msg="[Proposal Proposal{9/0 1:6B4D2A918D4C (0,:0:000000000000) /76E978DBCB6C.../}]"
WARN[01-24|14:18:22] Need to set a buffer and log.Warn() here for sanity. module=consensus startTime=2017-01-24T14:18:23+0000 now=2017-01-24T14:18:22+0000
NOTE[01-24|14:18:22] enterNewRound(9/1). Current: 9/0/RoundStepPrecommit module=consensus
```

I also tried to corrupt some files from `dummy.db` directory (LOG, CURRENT, MANIFEST).

```
docker exec local_testnet_$ID shred "./test/p2p/data/mach$ID/core/data/dummy.db/MANIFEST-000000"
```

Can't reproduce this :(

**Comment by surajpayu** [comment] 2017-01-25 06:14
I don't have the logs right now. Can you please tell which all files is required? cswal or any other?
If i hit this issue again, i will share the logs on this thread.

**Comment by ebuchman** [comment] 2017-01-25 06:26
oh, @surajpayu, what version of tendermint are you using, and what app? Before 0.8.0, tendermint didn't handle app failures, but now it uses a handshake to make sure tendermint and app are synced.

@melekes thanks for the tests. presumably you're using 0.8.0?

**Comment by melekes** [comment] 2017-01-25 06:30
yes, I was using the latest develop

**Comment by ebuchman** [comment] 2017-02-21 05:29
I think the problem here might be we're trying to reproduce with an in-proc app. @melekes is it easy with kubernetes to test this kind of thing (stopping and restarting the tendermint and app containers of one validator)? if so can we get a little write up ?

definitely need more crash/recovery in network setting with out-of-process abci apps, and apps in various states of corruption.

**Comment by melekes** [comment] 2017-02-23 07:50
@ebuchman yes, for sure. It would still be manual testing, though. In the future, we may want to automate this (using https://github.com/tendermint/functional-tester on top of k8s or just plain docker containers). Will need to think about this.

**Comment by melekes** [comment] 2017-02-23 08:46
## Killing app

```
$ kubectl exec -c app tm-0 -it -- kill 1

$ kubectl logs tm-0 -c tm -f
WARN[02-23|08:36:29] Stopping abci.socketClient for error: EOF module=abcicli
WARN[02-23|08:36:29] Stopping abci.socketClient for error: EOF module=abcicli
WARN[02-23|08:36:29] Stopping abci.socketClient for error: EOF module=abcicli
NOTE[02-23|08:36:29] Finalizing commit of block with 0 txs    module=consensus height=159 hash=345FBA857EF88F60CC8A77AAC23F8C85C6F28455 root=
WARN[02-23|08:36:29] Error in proxyAppConn.BeginBlock         module=state error=EOF
EROR[02-23|08:36:29] Error on ApplyBlock. Did the application crash? Please restart tendermint module=consensus error="Exec failed for application: EOF"
```

Result: TM (`tm-0`) stuck and was not making any progress (even when the counter app was up and running again). Other TM (`tm-1,tm-2,tm-3`) continue to make blocks.

**Comment by melekes** [comment] 2017-02-23 14:17
## Wiping DB (persistent dummy)

```
$ kubectl exec -c app tm-0 -it -- kill 1
$ kubectl exec -c app tm-0 -it -- rm -rf /tendermint/app
$ kubectl exec -c tm tm-0 -it -- kill 1

$ kubectl logs tm-0 -c tm -f
NOTE[02-23|14:14:29] Loaded PrivValidator                     module=types file=/tendermint/priv_validator.json privValidator="PrivValidator{7A24D6E881A9158B3F73E6F327C4B59BFD6548CE LH:922, LR:0, LS:3}"
NOTE[02-23|14:14:29] ABCI Handshake                           module=consensus appHeight=0 appHash=
NOTE[02-23|14:14:29] ABCI Replay Blocks                       module=consensus appHeight=0 storeHeight=922 stateHeight=921
NOTE[02-23|14:14:30] ABCI Replay Blocks                       module=consensus appHeight=921 storeHeight=922 stateHeight=921
NOTE[02-23|14:14:30] Catchup by replaying consensus messages  module=consensus height=922
NOTE[02-23|14:14:30] Replay: New Step                         module=consensus height=922 round=0 step=RoundStepNewHeight
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=244D1C2A9A1E418C7BE77B01844067D311781A85DA9E745D85E5365CD2752A02
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=7B704E209389ABBCB8F537AD9125853263B96D0AD5AA88C65CC489400538ED0E
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=7B704E209389ABBCB8F537AD9125853263B96D0AD5AA88C65CC489400538ED0E
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=E73E8A42BD25EE312D241A229C460567A1527213AA9E8D81E480CFEC3C23EC46
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=244D1C2A9A1E418C7BE77B01844067D311781A85DA9E745D85E5365CD2752A02
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=244D1C2A9A1E418C7BE77B01844067D311781A85DA9E745D85E5365CD2752A02
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=244D1C2A9A1E418C7BE77B01844067D311781A85DA9E745D85E5365CD2752A02
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=244D1C2A9A1E418C7BE77B01844067D311781A85DA9E745D85E5365CD2752A02
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=244D1C2A9A1E418C7BE77B01844067D311781A85DA9E745D85E5365CD2752A02
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=E73E8A42BD25EE312D241A229C460567A1527213AA9E8D81E480CFEC3C23EC46
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=E73E8A42BD25EE312D241A229C460567A1527213AA9E8D81E480CFEC3C23EC46
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=E73E8A42BD25EE312D241A229C460567A1527213AA9E8D81E480CFEC3C23EC46
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=7B704E209389ABBCB8F537AD9125853263B96D0AD5AA88C65CC489400538ED0E
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=7B704E209389ABBCB8F537AD9125853263B96D0AD5AA88C65CC489400538ED0E
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=921 round=0 type=2 blockID=4D218407112D6D7B335BEC581E2C8F3309E32F9E:1:789FA745B1EB peer=7B704E209389ABBCB8F537AD9125853263B96D0AD5AA88C65CC489400538ED0E
NOTE[02-23|14:14:30] Replay: Timeout                          module=consensus height=922 round=0 step=RoundStepNewHeight dur=978.858973ms
WARN[02-23|14:14:30] Need to set a buffer and log.Warn() here for sanity. module=consensus startTime=2017-02-23T14:14:31+0000 now=2017-02-23T14:14:30+0000
NOTE[02-23|14:14:30] enterNewRound(922/0). Current: 922/0/RoundStepNewHeight module=consensus
NOTE[02-23|14:14:30] Replay: New Step                         module=consensus height=922 round=0 step=RoundStepPropose
NOTE[02-23|14:14:30] Replay: Proposal                         module=consensus height=922 round=0 header=1:E2CC02CE684D pol=-1 peer=local
EROR[02-23|14:14:30] Error with msg                           module=consensus type=*consensus.ProposalMessage peer= error="Error invalid proposal signature" msg="[ProposalProposal{922/0 1:E2CC02CE684D (-1,:0:000000000000) /0161E35C856E.../}]"
NOTE[02-23|14:14:30] Replay: BlockPart                        module=consensus height=922 round=0 peer=local
NOTE[02-23|14:14:30] Replay: New Step                         module=consensus height=922 round=0 step=RoundStepPrevote
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=1 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=local
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=1 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=7B704E209389ABBCB8F537AD9125853263B96D0AD5AA88C65CC489400538ED0E
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=1 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=244D1C2A9A1E418C7BE77B01844067D311781A85DA9E745D85E5365CD2752A02
NOTE[02-23|14:14:30] Replay: New Step                         module=consensus height=922 round=0 step=RoundStepPrecommit
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=2 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=local
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=1 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=E73E8A42BD25EE312D241A229C460567A1527213AA9E8D81E480CFEC3C23EC46
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=1 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=E73E8A42BD25EE312D241A229C460567A1527213AA9E8D81E480CFEC3C23EC46
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=1 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=E73E8A42BD25EE312D241A229C460567A1527213AA9E8D81E480CFEC3C23EC46
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=2 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=E73E8A42BD25EE312D241A229C460567A1527213AA9E8D81E480CFEC3C23EC46
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=1 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=244D1C2A9A1E418C7BE77B01844067D311781A85DA9E745D85E5365CD2752A02
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=2 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=244D1C2A9A1E418C7BE77B01844067D311781A85DA9E745D85E5365CD2752A02
WARN[02-23|14:14:30] Attempt to finalize failed. We don't have the commit block. module=consensus
NOTE[02-23|14:14:30] Replay: New Step                         module=consensus height=922 round=0 step=RoundStepCommit
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=1 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=7B704E209389ABBCB8F537AD9125853263B96D0AD5AA88C65CC489400538ED0E
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=1 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=7B704E209389ABBCB8F537AD9125853263B96D0AD5AA88C65CC489400538ED0E
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=2 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=7B704E209389ABBCB8F537AD9125853263B96D0AD5AA88C65CC489400538ED0E
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=2 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=7B704E209389ABBCB8F537AD9125853263B96D0AD5AA88C65CC489400538ED0E
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=2 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=E73E8A42BD25EE312D241A229C460567A1527213AA9E8D81E480CFEC3C23EC46
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=2 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=7B704E209389ABBCB8F537AD9125853263B96D0AD5AA88C65CC489400538ED0E
NOTE[02-23|14:14:30] Replay: Vote                             module=consensus height=922 round=0 type=2 blockID=ED7F58B4A0FA133615C488AD9205D6A39D4A7598:1:E2CC02CE684D peer=244D1C2A9A1E418C7BE77B01844067D311781A85DA9E745D85E5365CD2752A02
NOTE[02-23|14:14:30] Replay: Timeout                          module=consensus height=922 round=0 step=RoundStepPropose dur=3s
NOTE[02-23|14:14:30] Replay: New Step                         module=consensus height=922 round=0 step=RoundStepPropose
NOTE[02-23|14:14:30] Replay: New Step                         module=consensus height=922 round=0 step=RoundStepPrecommit
NOTE[02-23|14:14:30] Replay: New Step                         module=consensus height=922 round=0 step=RoundStepCommit
NOTE[02-23|14:14:30] Replay: Done                             module=consensus
```

**Result:** tm-0 is stuck and not making any blocks, other validators (tm-1,tm-2,tm-3) are working fine.

**Comment by melekes** [comment] 2017-02-23 14:18
TM: develop b8279d424ccecc84c38a0cdb593ddc52e2f4fd31

**Comment by srmo** [comment] 2017-02-23 18:00
Could the setup of the seed-node property somehow affect the outcome of those experiments?

**Comment by melekes** [comment] 2017-02-23 18:23
@srmo no, I don't think so.

**Comment by melekes** [comment] 2017-02-23 18:39
This is what happens when I corrupt levelDB files.

```
$ kubectl exec -c app tm-0 -it -- shred /tendermint/app/dummy.db/000004.ldb
+ dummy --addr=unix:///socks/app.sock --persist=/tendermint/app
panic: Paniced on a Crisis: leveldb/table: corruption on table-footer (pos=1238): badmagic number [file=000004.ldb]

goroutine 1 [running]:
panic(0x7f3440, 0xc420088500)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/tendermint/go-common.PanicCrisis(0x80da00, 0xc4201542e0)
        /go/src/github.com/tendermint/go-common/errors.go:33 +0xe0
github.com/tendermint/go-db.(*GoLevelDB).Get(0xc420024058, 0xa92500, 0x9, 0x9, 0x5, 0x7ffe26ab2d48, 0xf)
        /go/src/github.com/tendermint/go-db/go_level_db.go:42 +0xd1
github.com/tendermint/abci/example/dummy.LoadLastBlock(0xa9dac0, 0xc420024058, 0x89a01c, 0x7, 0x7ffe26ab2d48, 0xf)
        /go/src/github.com/tendermint/abci/example/dummy/persistent_dummy.go:132 +0xa6
github.com/tendermint/abci/example/dummy.NewPersistentDummyApplication(0x7ffe26ab2d48, 0xf, 0x0)
        /go/src/github.com/tendermint/abci/example/dummy/persistent_dummy.go:36 +0x99
main.main()
        /go/src/github.com/tendermint/abci/cmd/dummy/main.go:24 +0x250
```

**Comment by melekes** [comment] 2017-02-23 18:41
>  my app sent wrong root hash as my earlier db got wiped out

have no ideas how to reproduce this with persistent dummy so far :(

**Comment by ebuchman** [comment] 2017-02-23 19:57
> kubectl exec -c tm tm-0 -it -- kill 1

Does this restart the node or are you just leaving out the re start command?

The "Wiping DB" bit def looks like a bug. I'll have to experiment. Thanks for the dumps.

**Comment by melekes** [comment] 2017-02-23 19:58
> Does this restart the node or are you just leaving out the re start command?

it gets restarted automatically by k8s since it monitors everything

**Comment by ebuchman** [comment] 2017-02-23 20:12
Ok - so there is a race between clearing the app data and k8 restarting the node? I wonder if the issue is a result of that race or more fundamental

**Comment by melekes** [comment] 2017-02-23 20:29
Hmm... if I remove data dir first and only then kill the app, then TM restarts normally all the time.

**Comment by melekes** [comment] 2017-02-23 20:50
Can't reproduce it anymore. That's strange 😕

**Comment by adrianbrink** [comment] 2017-06-16 12:14
Since it cannot be reproduced anymore I'm closing this.

**Closed by adrianbrink** 2017-06-16 12:14 UTC
Labels: Type: Bug

**Comment by TUTUBIG** [comment] 2018-09-27 10:45
i have this problem too

**Comment by melekes** [comment] 2018-09-27 11:18
@TUTUBIG could you create a new issue with detailed logs & steps to reproduce & etc. and reference this? thank you

**Comment by KevinBaylor** [comment] 2019-05-26 07:39
> I have 4 nodes running. Each of them is mapped to tmsp app. In one of the tmsp app tree got corrupted and merkle root hash was different. All the other nodes started giving following warning
> 
> ```
> NOTE[01-03|09:31:42] enterNewRound(64429/20). Current: 64429/19/RoundStepPrecommit module=consensus
> WARN[01-03|09:31:43] enterPrevote: ProposalBlock is invalid   module=consensus error="Wrong Block.Header.AppHash.  Expected 7820B976E6E7FC55A9124B7D94B6F31E8FFE0179, got 87A01D3C30FAA6F239AC114F6D24840447106690"
> NOTE[01-03|09:31:54] enterNewRound(64429/21). Current: 64429/20/RoundStepPrecommit module=consensus
> ```
> 
> After this, we are not able to produce any new block. The system is never able to recover. We need to reset everything and start it from scratch.

So how to solve this problem? I'm using bigchaindb 2.0.0b9.

**Comment by dolphinsd** [comment] 2019-10-09 23:34
@KevinBaylor , since there are 4 nodes, the only solution for you it to rebuild this node. Reboot the machine or kill all ps. Then 
1. delete all data from data dir for tendermint. do not delete config files.
2. run bigchaindb drop to drop db
3. run bigchiandb init to init it
4. run monit and wait till the node will catchup.

**Comment by askucher** [comment] 2020-02-04 22:15
I have this problem too
