### ISSUE TITLE
Peer ProposalBlockPartsHeader mismatch

### ISSUE THREAD

**Issue by xuhuigithub** [tendermint/tendermint#1603] opened 2018-05-21 07:49 UTC
When I submitted 10000 requests to my proxy_app at once, one of my tendermint nodes started to make mistakes. The mistake is like the bottom. In what case will this be a mistake? I didn't do anything, but I submitted 10000 asynchronous requests concurrently.

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.19.2-64408a40

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
bigchaindb:2.0.6

**Environment**:
- **OS** (e.g. from /etc/os-release):
Centos 7.2.1511
- **Install tools**:
docker 1.12.6
- **Others**:
I start tendermint app in docker,and I use host network.

**What happened**:
“Peer ProposalBlockPartsHeader mismatch” always show in the log.

**How to reproduce it** (as minimally and precisely as possible):
restart mistaken tendermint node

**Logs (you can paste a part showing an error or attach the whole file)**:
Peer ProposalBlockPartsHeader mismatch

**Comment by xuhuigithub** [comment] 2018-05-21 07:52
I know that this issue may not be a new feature requirement or a bug, but I can't find the corresponding answer anywhere, so I started the issue.

**Comment by ebuchman** [comment] 2018-05-21 16:03
Are you sending requests to your app directly, or through the Tendermint RPC?

Does the consensus actually halt? Or you just see that error a bit in the log ? 

Can you paste more logs please ?

**Comment by ebuchman** [comment] 2018-05-21 18:03
Can you clarify how you're making the requests? Were you sending transactions through the Tendermint RPC or are you talking to your app directly somehow ? 

Any more information you can give, or especially a way to reproduce, would be helpful.

**Comment by xuhuigithub** [comment] 2018-05-22 09:16
I concurrently request my app, and my app is responsible for communicating with tendermint. In fact, my main meaning is what happens under such circumstances. How should I solve him?

**Comment by ebuchman** [comment] 2018-05-22 12:57
Oh - it is strictly forbidden to send anything to your app that could change the state EXCEPT through Tendermint.

You should only communicate with your app through Tendermint, otherwise you will have issues.

Sounds like we could do a better job of documenting this though ? 

I'll close this issue since it sounds like its a result of incorrect use. If not, please re-open or open a new one. But in any case, only Tendermint should be communicating with your app :)

**Closed by ebuchman** 2018-05-22 12:57 UTC
