### ISSUE TITLE
Sync stops after restart

### ISSUE THREAD

**Issue by NodeATeam** [tendermint/tendermint#3299] opened 2019-02-12 01:50 UTC
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.30.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
gaiad for GOS 6 (game_of_stakes_6)

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
- **Install tools**: make
- **Others**: x

**What happened**:
After gaiad restart, node failed to sync.
We started our node due to script implementation, but after restarting, Tendermint showed massive amount of connection error and failed to connect to peers immediately.

Had to restarted once more to connect to peers correctly.

**What you expected to happen**:
Immediate sync / peer connection after restart.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
1. gaiad start
2. stop
3. gaiad restart (and the error above happens)

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
![restart bug](https://user-images.githubusercontent.com/45612983/52605729-587b2580-2eb3-11e9-8ef1-27545b78fcef.png)

**Comment by hendrikhofstadt** [comment] 2019-02-12 10:34
Duplicate of #3295

**Closed** 2019-02-13 05:04 UTC
