### ISSUE TITLE
docs: writing your first application guide

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3016] opened 2018-12-14 09:44 UTC
```
you can use our ABCI server https://github.com/tendermint/tendermint/tree/master/abci/server
to run the app

example: https://github.com/tendermint/tendermint/blob/9c236ffd6c56add84f3c17930ae75c26c68d61ec/abci/tests/client_server_test.go#L14-L21
13:41
or you can bundle your application together with Tendermint
```

1. separate app using an ABCI server (ideally for every popular language out there)
2. Tendermint and app bundled together (Golang only)

**Comment by marbar3778** [comment] 2019-12-06 14:18
closing this as it seems to be a duplicate of #3808

**Closed by marbar3778** 2019-12-06 14:18 UTC
Labels: docs
