### ISSUE TITLE
Missing Data In Batch Without Error

### ISSUE THREAD

**Issue by pascaldekloe** [tendermint/tendermint#5339] opened 2020-09-07 17:58 UTC
Each BlockResult request in a batch after 20 will not have any Events. The height is set though.

**Comment by marbar3778** [comment] 2020-09-08 07:58
Could you provide the version of Tendermint you are using?

**Comment by pascaldekloe** [comment] 2020-09-08 08:47
`github.com/tendermint/tendermint v0.33.4`

**Comment by melekes** [comment] 2020-09-14 04:42
Could you provide more details? RPC output, logs, etc. Not sure I understand what the problem is. Is this about RPC `/block_results`?

**Comment by melekes** [comment] 2020-09-14 04:43
Please use Github issue template going forward. Thank you!

**Comment by pascaldekloe** [comment] 2020-09-14 11:50
Try to request more than 20 `BlockResults` with the "HTTP RPC batch" client in one goal. You'll find that only the first 20 have events, and the others are left empty, without an error or any warning. This is a serious bug @melekes & @marbar3778.

**Comment by melekes** [comment] 2020-09-15 07:06
There's nothing wrong with the batch RPC client. As far as I can see you're using the regular HTTP client for making requests - https://github.com/pascaldekloe/midgard/blob/205e8b5a61796601c154c6e33fee426aad0c6d9c/chain/chain.go#L150. 

`BlockchainInfo` (`/blockchain` endpoint) returns at most 20 entries. It's our mistake that it was missing in the docs. Fixed in: https://github.com/tendermint/tendermint/pull/5356/files

As for https://github.com/pascaldekloe/midgard/blob/205e8b5a61796601c154c6e33fee426aad0c6d9c/chain/chain.go#L178-L180

we're using a pointer receiver there because we also allow passing `nil` (e.g.`.Block(nil)` will return the latest block).

**Closed** 2020-09-28 15:13 UTC
Labels: C:rpc, T:bug
