### ISSUE TITLE
make get_vendor_deps

### ISSUE THREAD

**Issue by ying2025** [tendermint/tendermint#1656] opened 2018-05-31 03:54 UTC
When I run "make get_vendor_deps", It happened as following
--> Running dep
dep: WARNING: Unknown field in manifest: prune
The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export github.com/spf13/afero: unable to update repository: : command failed: [git fetch --tags --prune origin]: exit status 255
Makefile:51: recipe for target 'get_vendor_deps' failed
make: *** [get_vendor_deps] Error 1

**Comment by ValarDragon** [comment] 2018-05-31 04:38
This is probably an issue with dep. Have you used ssh keys with github before? If not, try to follow the steps here: `https://help.github.com/articles/about-ssh/`. In particular this section: `https://help.github.com/articles/testing-your-ssh-connection/`. It looks to me that dep is trying to use ssh, but you haven't used ssh with github before.

**Comment by zramsay** [comment] 2018-05-31 11:48
duplicate of #1660

**Closed by zramsay** 2018-05-31 11:48 UTC
