### ISSUE TITLE
privval: race condition in test

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3179] opened 2019-01-21 14:22 UTC
```
?   	github.com/tendermint/tendermint/p2p/dummy	[no test files]
==================
WARNING: DATA RACE
Write at 0x00c0001a3551 by goroutine 100:
  testing.(*common).FailNow()
      /usr/local/go/src/testing/testing.go:589 +0x4c
  testing.(*common).Fatal()
      /usr/local/go/src/testing/testing.go:628 +0x7c
  github.com/tendermint/tendermint/privval.TestListenerConnectDeadlines()
      /go/src/github.com/tendermint/tendermint/privval/socket_test.go:128 +0x268
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162

Previous write at 0x00c0001a3551 by goroutine 94:
  testing.(*common).FailNow()
      /usr/local/go/src/testing/testing.go:589 +0x4c
  testing.(*common).Fatal()
      /usr/local/go/src/testing/testing.go:628 +0x7c
  github.com/tendermint/tendermint/privval.TestListenerConnectDeadlines.func1()
      /go/src/github.com/tendermint/tendermint/privval/socket_test.go:108 +0xff

Goroutine 100 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:878 +0x659
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1119 +0xa8
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1117 +0x4ee
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1034 +0x2ee
  main.main()
      _testmain.go:156 +0x332

Goroutine 94 (finished) created at:
  github.com/tendermint/tendermint/privval.TestListenerConnectDeadlines()
      /go/src/github.com/tendermint/tendermint/privval/socket_test.go:103 +0x1e6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:827 +0x162
==================
--- FAIL: TestListenerConnectDeadlines (0.11s)
    socket_test.go:108: read tcp 127.0.0.1:37827->127.0.0.1:38846: i/o timeout
    socket_test.go:128: read tcp 127.0.0.1:38846->127.0.0.1:37827: i/o timeout
    testing.go:771: race detected during execution of test
FAIL
coverage: 87.6% of statements
FAIL	github.com/tendermint/tendermint/privval	1.787s
```

**Comment by thanethomson** [comment] 2019-01-21 16:13
How would one go about reproducing this? I can't reproduce with `go test` or `make test` on `develop` or `master` (even with the race detector on).

**Comment by ebuchman** [comment] 2019-01-21 17:39
`go test -race ./privval` should be able to surface it

**Comment by thanethomson** [comment] 2019-01-21 17:49
Very strange. Even with `GOCACHE=off go test -race ./privval` and two other terminals running `yes &> /dev/null`, all tests still pass:

```bash
> GOCACHE=off go test -race ./privval
ok  	github.com/tendermint/tendermint/privval	2.928s
```

I wonder if it's somehow platform-specific? I'm on a MacBook Pro. Can you replicate it locally on your machine?

**Comment by melekes** [comment] 2019-01-24 10:18
```
A test ends when its Test function returns or calls any of the methods FailNow, Fatal, Fatalf, SkipNow, Skip, or Skipf. Those methods, as well as the Parallel method, must be called only from the goroutine running the Test function.

The other reporting methods, such as the variations of Log and Error, may be called simultaneously from multiple goroutines.
```

**Comment by thanethomson** [comment] 2019-01-24 10:22
> ```
> A test ends when its Test function returns or calls any of the methods FailNow, Fatal, Fatalf, SkipNow, Skip, or Skipf. Those methods, as well as the Parallel method, must be called only from the goroutine running the Test function.
> 
> The other reporting methods, such as the variations of Log and Error, may be called simultaneously from multiple goroutines.
> ```

So it's because the `t.Fatal()`/`t.Fatalf()` functions are being called simultaneously from two separate goroutines? If so, that should be easy to fix. I'll tackle that now.

What I'm more concerned about is the reproducibility of these sorts of issues. But we can cross that bridge if they keep coming up.

**Comment by melekes** [comment] 2019-01-28 08:39
Merged to develop.

**Closed by melekes** 2019-01-28 08:39 UTC
Labels: bug, test, validator
