### ISSUE TITLE
RPC Endpoint to emit TrustOptions

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/tendermint#4357] opened 2020-01-29 20:54 UTC
Ideally there should be an endpoint where tendermint serves block headers needed for lite client initialization. The format could be as follows:
```json
[
  {
    "hash": "{{header}}",
    "trust-period": "2w",
    "height": 1200923,
  }
]
```

**Comment by melekes** [comment] 2020-01-30 11:44
what should be the source of `trust-period`? 

Maybe it should come from whomever calls Tendermint (and uses light client). Then Tendermint only will need to return `hash` and `height`? If so, these two are already available in https://docs.tendermint.com/master/rpc/#/Info/commit endpoint.

**Comment by melekes** [comment] 2020-02-18 13:00
Duplicate of https://github.com/tendermint/tendermint/issues/4393

**Closed by melekes** 2020-02-18 13:00 UTC
