### ISSUE TITLE
What should I do if I want to start at some non-zero height?

### ISSUE THREAD

**Issue by ying2025** [tendermint/tendermint#3892] opened 2019-08-12 03:21 UTC
I want to  start from non-zero height? what should I do? Is the following function ?
         

    `func Status(ctx *rpctypes.Context) (*ctypes.ResultStatus, error) {
	var latestHeight int64
	if consensusReactor.FastSync() {
		latestHeight = blockStore.Height()
		fmt.Println("--start height----", latestHeight)
	} else {
		latestHeight = consensusState.GetLastHeight()
		fmt.Println("--from last height----", latestHeight)
	}
	var (
		latestBlockMeta     *types.BlockMeta
		latestBlockHash     cmn.HexBytes
		latestAppHash       cmn.HexBytes
		latestBlockTimeNano int64
	)
	if latestHeight != 0 {
		latestBlockMeta = blockStore.LoadBlockMeta(latestHeight)
		latestBlockHash = latestBlockMeta.BlockID.Hash
		latestAppHash = latestBlockMeta.Header.AppHash
		latestBlockTimeNano = latestBlockMeta.Header.Time.UnixNano()
	}

	latestBlockTime := time.Unix(0, latestBlockTimeNano)

	var votingPower int64
	if val := validatorAtHeight(latestHeight); val != nil {
		votingPower = val.VotingPower
	}

	result := &ctypes.ResultStatus{
		NodeInfo: p2pTransport.NodeInfo().(p2p.DefaultNodeInfo),
		SyncInfo: ctypes.SyncInfo{
			LatestBlockHash:   latestBlockHash,
			LatestAppHash:     latestAppHash,
			LatestBlockHeight: latestHeight,
			LatestBlockTime:   latestBlockTime,
			CatchingUp:        consensusReactor.FastSync(),
		},
		ValidatorInfo: ctypes.ValidatorInfo{
			Address:     pubKey.Address(),
			PubKey:      pubKey,
			VotingPower: votingPower,
		},
	}

	return result, nil
}`

**Comment by melekes** [comment] 2019-08-12 06:34
Duplicate of https://github.com/tendermint/tendermint/issues/2543

**Closed** 2019-08-12 06:34 UTC
