### ISSUE TITLE
Update ADR-047 - Light Client Evidence Submission

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#5083] opened 2020-07-04 04:21 UTC
[ADR-047](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-047-handling-evidence-from-light-client.md) outlines what data light clients should submit and how that data should be handled and turned into evidence. However there are a few issues with it that have spawned some discussion in #5022, #5026. Here are some more related thoughts that summarize some of that discussion and suggest how we should update ADR-047.

## ConflictingHeadersEvidence

ADR-047 proposes submitting two conflicting headers for the same height. But from discussion we know this is insufficient. #5026 discusses options of sending full bisection traces or of searching for the first conflicting header with a common parent. Instead of either, I think we should submit just enough info to prove to a particular full node that we verified a fork block. That means we have to know which full node we're talking to (so we can send it a conflicting block), and we have to send different evidence to different full nodes. For a full node to verify that the light client was fooled it effectively needs to run the light client verification for one step, so it needs:

- light client's latest trusted state (which should match with what's on the full node's chain) 
- a light block that is not on the full node's chain that can be verified in one step from the trusted block using light client commit verification (ie. sequential or skipping)

So instead of ConflictingHeadersEvidence, the light client should submit (eg.) LightClientForkEvidence:

```
type LightClientForkEvidence struct {
  TrustedBlock   TrustedBlockInfo
  ConflictingBlock    LightBlock
}

// info about the LC's last trusted block
type TrustedBlockInfo struct {
  Height int
  BlockID BlockID
} 

// full light block (SignedHeader & ValidatorSet)
type LightBlock struct {}
```

Here, ev.TrustedBlock is for some height `tbh` and matches what's on the full node's chain, while ConflictingBlock is for some height `cbh` and conflicts with what's on the full node's chain. 

Note we don't need to submit the full trusted LightBlock, just the height and hash. The full node can load the validators from that height and run the relevant checks against the ConflictingBlock using those trusted validators to see if the light client would have been fooled.

Note also that we don't necessarily send a full bisection trace, just the first light block in this trace. This means we may not publish evidence about all possible byzantine behaviour, since other blocks in the trace may contain more evidence than the first block. However to keep things simple, I propose that just using the first block, which guarantees at least +1/3 get punished, is enough.

Another benefit of sending the TrustedBlockInfo is that the full node can let the light client know if its TrustedBlock is not in the chain. Since the light client is assumed to always have one correct full node, we expect any block it trusts to be correct and in the full node's chain. However if this assumption fails, we might not be able to publish evidence successfully, and it might not be clear why, so getting this information back from a full node can help alert a light client operator that there was an issue earlier (ie. at some point it didnt have a correct peer and thus trusted a fork block) and potentially to take further action.  

## Phantom Validators

Do we need to even care about phantom validators? I'm reasonably convinced that any phantom validator signature that's really meaningful is also a lunatic validator (ie. signing an invalid block). And phantom validators add a lot of complexity because we have to track the full set of validators that have been active within an unbonding period in order to detect that a signer who signed when they shouldn't have was recently a validator and can thus be punished.

In principle, I believe we could ignore phantom validators and just work with lunatic ones. This would eliminate the need to do the extra tracking and reduce the types of evidence we have to worry about. While it means we wouldn't be punishing any phantom validators, I believe that any case where there are phantom validators as part of a fork, we'll be punishing +1/3 lunatic validators anyways.

That said, we could easily support some phantom validator evidence by just checking against the validators from height `tbh` without any extra tracking - if a validator from height `tbh` signed the `ev.ConflictingBlock` even though they're not in the valset of the chain at height `cbh`, then full node's can easily confirm that they are Phantom and punish them accordingly.

## Sequential vs Skipping

Every light block a light client verifies is done either by sequential or skipping verification from the previous light block. If the trusted block is `tb` and the conflicting block is `c`, sequential means `c.height = tb.height + 1` and skipping means `c.height > tb.height +1`.

In the sequential case, for the light client to have been fooled, we must have `tb.nextvals = c.vals`.

In the skipping case, for the light client to have been fooled, we must have +1/3 of `tb.nextvals` sign the commit for `c`.

## Valid vs Invalid

Some fields in a block are derived deterministically from executing the previous block (eg. Validators, NextValidators, AppHash, etc.) - call these prev-block-dependent. Other fields are legitimate degrees of freedom (DataHash, ProposerAddress, LastCommit, etc.) - call these prev-block-independent. 

Blocks are *valid* if their prev-block-dependent fields are derived correctly. Multiple blocks for the same height may be valid since they can contain different prev-block-independent fields (ie. different txs includes by different proposers), but they should all contain the same prev-block-dependent fields (ie. the AppHash is a deterministic result of executing the previous block and can't be changed). Committing multiple valid blocks requires only +1/3 of validators for that block to be byzantine and implies equivocation/amensia.

Blocks are invalid if their prev-block-dependent fields can not be derived correctly. Committing an invalid block requires +2/3 of validators for that block to be byzantine and implies lunatics.

A block can be determined to be valid or invalid by comparing prev-block-dependent fields in the forked block with those in the correct block in the chain. In ADR-047 it's proposed that the LunaticEvidence object indicate which field is invalid, but we probably don't need to do that since full nodes can just check all relevant fields relatively quickly. Note we need to check all fields which are a deterministic result of the last committed block: LastBlockID, ValidatorsHash, NextValidatorsHash, ConsensusHash, AppHash, LastResultsHash. Anything else is technically a valid degree of freedom in a block that could be proposed and voted on by correct validators even if it didn't get committed.

## Evidence Verification

We thus have a 2x2 matrix of possibilities for a conflicting block `c` based on a trusted block `tb`: sequential-valid, sequential-invalid, skipping-valid, skipping-invalid.

sequential-valid and skipping-valid imply +1/3 of the `c.vals` did equivocation/amensia.

sequential-invalid implies +2/3 of the `c.vals` did lunatic. since `c.vals = tb.nextvals`, we can punish all +2/3.

skipping-invalid implies +1/3 of the `tb.vals` and +2/3 of the `c.vals` did lunatic. depending on how much of the `c.vals` are in `tb.vals` and in the correct val set at height `cbh` determines how many of them will get punished, but at least +1/3 of tb.vals will be.

## IBC Misbehaviour

Do we need to update ICS-07 so we can properly submit misbehaviour? Ie. we may need to specify what trusted state to start from when verifying a conflicting header. So instead of submitting two conflicting headers we may want to submit a trusted state and a conflicting header like outlined here ...

## Light Client Attacks on Full Nodes

Can light client equivocation/amnesia attacks be rebroadcast against full nodes to cause them to crash? I would think/hope not but haven't fully checked ...

## Full Node Forks

I believe we still have not addressed this and it's still out of scope though we need to get to it eventually. In the full node case we're only dealing with equivocation and amnesia but we need some way to run the amnesia fork accountability protocol out of band, eg. on a centralized server. See #4324. Other?

## Other Notes

We should update the original [fork accountability](https://github.com/tendermint/spec/blob/master/spec/consensus/light-client/accountability.md) spec with some of these clarifications. Like maybe we can get rid of Phantom Validators. Also I think there's confusion between flip-flopping and amnesia. As far as I can tell, there's really just 3 kinds of byzantine behaviour we need to worry about: equivocation, amnesia, lunatic. It would be good if we could align everything around this or clarify why it's not true.

**Comment by melekes** [comment] 2020-07-06 06:59
> LightClientForkEvidence

Why include `BlockID`? Can't this simply be a hash of the trusted block?

> Do we need to even care about phantom validators? I'm reasonably convinced that any phantom validator signature that's really meaningful is also a lunatic validator (ie. signing an invalid block). 

Right, but what about "second block attacks"? I know we're assuming one correct witness, but what if this witness does not respond for an hour, should we wait? (say we have 10 witnesses).

![second_block_attack](https://user-images.githubusercontent.com/1282182/86564517-684b4c00-bf77-11ea-90f8-eed9a18f6482.png)

Here if cabal 1/3+ group unbonds and performs phantom validator attack, it will fool the light client and all the later evidence will be invalid. I still think we should try to find a common ancestor.

**Comment by cmwaters** [comment] 2020-07-06 08:50
> However to keep things simple, I propose that just using the first block, which guarantees at least +1/3 get punished, is enough.

Are you implying here that one of the criteria for a full node to validate conflicting headers is that at least 1/3 of the validators in the conflicting header must be present in the trusted header?

> So instead of ConflictingHeadersEvidence, the light client should submit (eg.) LightClientForkEvidence:

Anton thought of something similar where we don't need to send both headers if we know that the full node already has one of them. This works fine for sending the evidence to the two providers who have provided the conflicting headers because we know which headers they trust, but a light client is supposed to be connected with many witnesses. I'd imagine we want to send evidence to them as well but how do we know which of the two headers they trust, hence we decided to send both headers to all providers.

> And phantom validators add a lot of complexity because we have to track the full set of validators

I completely agree with this - it's a lot of overhead to decentivise phantom validator attacks. As far as I can see to orchestrate a successful phantom attack (causing a light fork) you need a light client running bisection, +1/3 byzantine validators and the light client to be connected to only byzantine providers. If there is a single non byzantine provider then the attack will be found out. This is quite rare so maybe we don't need to look out for it but if we don't have the evidence there then there is nothing stopping a cabal from trying it out (they won't be punished just disconnected). If we want to avoid phantom attacks entirely then I believe we need to trace back to the common ancestor header (that way even the 1/3 won't be able to fool the light client)

> [full node fork] I believe we still have not addressed this and it's still out of scope though we need to get to it eventually

I find this a point of confusion, especially for anyone entering the space that we call this work fork accountability when (a) Tendermint doesn't force any accountability for evidence created that's up to the application to decide (b) the way which evidence is presented (on a validator by validator basis) doesn't necessarily indicate a fork. i.e. DuplicateVoteEvidence validated on chain can mean that there was a fork but also that there wasn't one.

**Comment by melekes** [comment] 2020-07-06 10:07
Previous discussions: https://github.com/tendermint/tendermint/issues/5026 and https://github.com/tendermint/tendermint/issues/4934

**Comment by ebuchman** [comment] 2020-07-06 13:48
> Are you implying here that one of the criteria for a full node to validate conflicting headers is that at least 1/3 of the validators in the conflicting header must be present in the trusted header?

Yes, since this is the logic the light client has to execute, the full node should be able to verify the same.

> I'd imagine we want to send evidence to them as well but how do we know which of the two headers they trust, hence we decided to send both headers to all providers.

What if we just send all LightClientForkEvidence to everyone? Some will be invalid for a given full node but no worries?

> If we want to avoid phantom attacks entirely then I believe we need to trace back to the common ancestor header (that way even the 1/3 won't be able to fool the light client)

Similar to what's being proposed here right?

> I find this a point of confusion, especially for anyone entering the space that we call this work fork accountability when (a) Tendermint doesn't force any accountability for evidence created that's up to the application to decide (b) the way which evidence is presented (on a validator by validator basis) doesn't necessarily indicate a fork. i.e. DuplicateVoteEvidence validated on chain can mean that there was a fork but also that there wasn't one.

Indeed we need better terminology across the board.

**Comment by josef-widder** [comment] 2020-07-22 13:18
I had a discussion with @milosevic today. It looks like there is no way around that LightClientForkEvidence actually contains a trace of lightblocks rather than a single one as suggested above. The issue is that the minimal requirement is that the light node needs to submit at least a lightblock that is in conflict with a lightblock of the full node. This is the intuition of the suggestion of "TrustedBlock + ConflictingBlock". This does not seem practical/achievable.

As the lightclient's lightstore is the result of bisection, the light node does not have complete knowledge of all the blocks the primary (or the secondary) knows. As a result, it appears that computing minimal evidence as suggested above (TrustedBlock + ConflictingBlock) might require the light node to do a challenge-response protocol with the primary (or secondary). However, as in this scenario, most likely the primary is faulty, it may not collaborate, and may not provide additional (intermediate) lightblocks. As the light node should still be able to submit evidence, the way around is to submit the trace (that was used to establish the fork) rather than a single block.

Pragmatically, if we decide to use the trace now, and later decide that a challenge/response makes sense to reduce the evidence size, we might still use the same data structure, but the traces will just have lengths 1. I will try to capture this in the detection spec in the tendermint-rs repo, and open a PR in the next days.

**Comment by tessr** [comment] 2020-09-22 09:41
Now that [ADR 59](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-059-evidence-composition-and-lifecycle.md) has been written and https://github.com/tendermint/tendermint/pull/5361 has been merged, I think we can close this issue.

**Closed by tessr** 2020-09-22 09:41 UTC
