### ISSUE TITLE
ensure windows compatibility

### ISSUE THREAD

**Issue by Pat555** [tendermint/tendermint#528] opened 2017-06-06 03:39 UTC
BUG REPORT
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.10 latest windows exe

**Environment**:
- **OS**: Windows 10

**What happened**: Downloaded Windows tendermint.exe, ran tendermint init, tendermint node for the first time

**What you expected to happen**: start creating blocks

**How to reproduce it** (as minimally and precisely as possible): run exe on windows

![tenderminterror](https://cloud.githubusercontent.com/assets/24992681/26812736/897238d8-4a47-11e7-9845-2881cfc69405.PNG)

**Comment by ebuchman** [comment] 2017-06-06 04:18
You need to run an ABCI app in separate window, or use the `--proxy_app=dummy` flag. See https://tendermint.com/intro/getting-started/first-app.

Please re-open if there's still an issue.

**Comment by Pat555** [comment] 2017-06-06 12:19
Hi Ethan, I ran tendermint.exe --proxy_app=dummy, got another error.

![tendermint_proxy](https://cloud.githubusercontent.com/assets/24992681/26828710/abd9c870-4a90-11e7-979b-823b7910d869.PNG)

**Comment by ebuchman** [comment] 2017-06-06 12:51
Looks like genuine windows bug. Thanks.

**Comment by Pat555** [comment] 2017-06-08 02:08
Downloaded tendermint source on windows machine. 3 problems:
1. makefile doesn't work, had to use go and glide directly
2. can't find cs.wal directory
3. changed permissions to .tendermint folder - gave Full Control to Users, however, after two committed states, got priv_validator.json - access is denied.
![tenderminterror3](https://user-images.githubusercontent.com/24992681/26909246-84d0fcce-4bcd-11e7-8cb4-f71e051b988c.PNG)

**Comment by srmo** [comment] 2017-06-30 15:57
Is there a follow up issue on this one?

**Comment by srmo** [comment] 2017-07-06 10:13
Is this a regression from https://github.com/tendermint/tendermint/issues/444 ?

**Comment by mhaeusler** [comment] 2017-07-06 14:09
I also have this priv_validator.json  access problem on a Windows system using tendermint 0.10.1
however this does not happen immediately, but usually within one minute.

**Comment by srmo** [comment] 2017-09-20 20:14
Any news on this?

**Comment by melekes** [comment] 2017-09-20 22:49
Zack fixed https://github.com/tendermint/tendermint/issues/595 just a few days ago. Other than that, no. How many people actually use Windows?

**Comment by srmo** [comment] 2017-09-21 06:19
Some of our devs do. Additionally we expect some of our customers to host our PoC on windows platforms. If this works out is another story :)

**Comment by zramsay** [comment] 2017-10-04 02:48
#698 will be bringing additional windows testing to our development pipeline

**Comment by zramsay** [comment] 2017-12-14 17:48
closing for now. Feel free to open new issues if more incompatibilities are discovered

**Closed by zramsay** 2017-12-14 17:48 UTC

**Comment by vieiralc** [comment] 2018-04-23 18:29
When I run tendermint node it gives me this error:

`ERROR: While parsing config: (30, 17): invalid escape sequence: \c`

This is my config.toml

![image](https://user-images.githubusercontent.com/19657718/39145787-2033df40-470b-11e8-8be7-7e549df57175.png)
