### ISSUE TITLE
Tendermint's rpc api docs

### ISSUE THREAD

**Issue by SaifRehman** [tendermint/tendermint#1416] opened 2018-04-04 17:41 UTC
Can I please get documentation of tendermint's rpc api, what each one does etc. 
@ebuchman

**Comment by melekes** [comment] 2018-04-05 08:04
Duplicate of #691

**Comment by melekes** [comment] 2018-04-05 08:04
@SaifRehman wanna help us out with #691 ?

**Closed by melekes** 2018-04-05 08:04 UTC

**Comment by SaifRehman** [comment] 2018-04-05 08:32
of course yes! how do i contribute with the docs?

**Comment by melekes** [comment] 2018-04-05 08:56
There is no docs, so you'll have to create them. You can find an example here https://github.com/hypothesis/h/tree/master/docs/_extra/api-reference ([how it looks](https://h.readthedocs.io/en/latest/api-reference/))

**Comment by SaifRehman** [comment] 2018-04-05 09:12
cool, ill take on this!

**Comment by zramsay** [comment] 2018-05-22 02:20
@SaifRehman track #691, we should have a well-documented RPC within a week
