### ISSUE TITLE
index service will lose data when node restart or start after being killed

### ISSUE THREAD

**Issue by guagualvcha** [tendermint/tendermint#3823] opened 2019-07-22 07:07 UTC
As index service is running asynchronously, if block have been applied but tx index haven't write into db, if node crash at this point, we will lose index data. Any idea or plan to resolve this?

**Comment by melekes** [comment] 2019-07-22 07:43
Yeah, we need to store last indexed height and request missing blocks (`latestSavedHeight <= LatestBlockHeight`) upon startup.

**Comment by guagualvcha** [comment] 2019-07-22 10:22
> latestSavedHeight

great news. we will follow up if it comes soon.

**Comment by ebuchman** [comment] 2019-11-19 19:33
Is this a duplicate of https://github.com/tendermint/tendermint/issues/3211 ?

**Comment by melekes** [comment] 2019-11-20 07:46
Yep. Closing this for #3211

**Closed by melekes** 2019-11-20 07:46 UTC
Labels: abci, bug
