### ISSUE TITLE
Bug: WS RPC connection not stable

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#553] opened 2017-06-23 13:07 UTC
BUG REPORT

**Tendermint version**:
0.9.0 and 0.10.0-'ca632c9

**ABCI app**: dummy implementation and production versions of different kinds

**Environment**:
- **OS**: Windows, Linux, OSX

JsonRPC seems instable on 0.9.x and current 0.10.release. Connecting to the RPC websocket works and the conneciton is fine. But once we send our ASYNC TX-Broadcasts using JsonRPC, the connection will die with a timeout when trying to write the next ping 30s after we've sent a message.
We can keep sending messages for as long as we want, but the connection will always die ~30 seconds after the last message is sent.

In 0.9.0 we can see a I/O timeout error "cannot write ping message". 
In 0.10.0 we don't see an error message, might be an ill-configured logging, currently `log_level = "consensus:error,*:debug"`

The connection is dropped with an "abnormal close".

**What you expected to happen**:
WS Conection should be stable even after sending data.

**How to reproduce it** (as minimally and precisely as possible):
* Connect to a Broadcast WS endpoint
* wait more than 30 seconds (that's the ticker, read and write timeouts)
** by the way, we don't see any option to configure them
* connection is stable
* now send a broadcast_async_tx RPC call over Websocket using JsonRPC
* the connection will close abnormally after ~30 after the last send

**Anything else do we need to know**:
This is from Slack:

> It never was stable. I remember Bucky saying it is fine and “you just reconnect”, but I did not fully understand the reason it’s dying

which isn't really helping :)
Reconnecting can be a solution, but not with an `abnormal close`. How are you now supposed to decide if something really wrong or not?

**Comment by ebuchman** [comment] 2017-06-25 02:10
Issue 1: We neglected to set the logger properly on the WS connection after the 0.10 logging overhaul. Fixed on develop, will be in 0.10.1 this week.

Issue 2: From the sound of it, you are not responding to the Ping message correctly. Can you clarify whether you are responding to the Ping message with a Pong? If not, that would explain the problem :)

**Comment by srmo** [comment] 2017-06-25 07:14
Nice too see that in 0.10.1.

Yes, we are writing Pongs. Actually, it's the implementation we use that does this for us. We can see it in Wireshark and it is backed by the fact, that the connection is stable until we send something. 
I'll double check that ping/pong also works after that. But as I've said, ~30 seconds after sending the last RPC call over Websocket the session dies. Usually with a "I/O timeout" when trying to write the Ping on the socket.

**Comment by srmo** [comment] 2017-06-25 07:16
I'll try and come up with a log/wireshark-log for this. Might take till monday.

**Comment by ethanfrey** [comment] 2017-06-25 17:15
@mappum I think you use websockets to make TX calls in the Basecoin ui, correct? Did you ever have reconnect issues? Could you link to the is client that does this? 

It would help us a lot to locate the problem, client or server.

**Comment by ethanfrey** [comment] 2017-06-25 19:07
Okay, I can reproduce this with a simple case that we can try to add to the integration tests....

@ebuchman maybe you can take a deeper look?  Here is a starting point so you can reproduce it and test any fixes. 

Server:
```
export TMHOME=~/.test_case
rm -rf $TMHOME
tendermint init
tendermint node --proxy_app=dummy
```

Client:
```
go get github.com/raphael/wsc
(sleep 40; echo '{"jsonrpc": "2.0", "id": "foo", "method": "status", "params": []}'; sleep 40; echo '{"jsonrpc": "2.0", "id": "foo", "method": "status", "params": []}'; sleep 5) | wsc ws://localhost:46657/websocket
```

Ideally the client would get two successive status answers.  In reality, I get this:

```
2017/06/25 21:03:07 connecting to ws://localhost:46657/websocket...
2017/06/25 21:03:07 ready, exit with CTRL+C.
>> {"jsonrpc": "2.0", "id": "foo", "method": "status", "params": []}
<< {
  "jsonrpc": "2.0",
  "id": "foo",
  "result": {
    "node_info": {
      "pub_key": "C87CF16D718E09055960BE893E62F9A3732F1E625BDC66B8D69A76F852CF91BB",
      "moniker": "anonymous",
      "network": "test-chain-V62G44",
      "remote_addr": "",
      "listen_addr": "192.168.178.20:46656",
      "version": "0.10.0-ca632c9e",
      "other": [
        "wire_version=0.6.2",
        "p2p_version=0.5.0",
        "consensus_version=v1/0.2.2",
        "rpc_version=0.7.0/3",
        "tx_index=on",
        "rpc_ad
<< dr=tcp://0.0.0.0:46657"
      ]
    },
    "pub_key": {
      "type": "ed25519",
      "data": "E8FC685550EBB3FA389A9DF34A9AEF298E6E17BD1B43D98ABA5A20CE8B0E50A9"
    },
    "latest_block_hash": "BA87D359DD35114506CABD30EA2FAC966395CCB0",
    "latest_app_hash": "",
    "latest_block_height": 335,
    "latest_block_time": 1498417427359000000
  },
  "error": ""
}
2017/06/25 21:04:17 EOF
```

Note the EOF is exactly 70 seconds after it opened the connection, which is 30 seconds after the status call.  In sync with the findings of @srmo

**Comment by mappum** [comment] 2017-06-26 18:52
It appears the server ends the connection if you don't make requests often enough. I made a JS script which is equivalent to @ethanfrey's bash script above, and it gets the same results. But if I poll status every few seconds, it seems to stay connected forever. (I have never run into the disconnect because I am constantly polling `status` and `net_info` to show some of that info in the UI).

If you want to reproduce with JS, here's my code:

`$ npm install tendermint watt`

First test, disconnects before making second request:
```js
let watt = require('watt')
let Tendermint = require('tendermint')
let client = Tendermint('ws://localhost:46657')
client.on('error', (err) => console.log(err))

function * main (next) {
  console.log('waiting 40s')
  yield setTimeout(next, 40e3)
  console.log(yield client.status(next))

  console.log('waiting 40s')
  yield setTimeout(next, 40e3)
  console.log(yield client.status(next))

  console.log('waiting 5s')
  yield setTimeout(next, 5e3)
}

watt(main)((err) => console.log(err))
```

Second test, stays connected:
```js
let Tendermint = require('tendermint')
let client = Tendermint('ws://localhost:46657')
client.on('error', (err) => console.log(err))

let start = Date.now()
setInterval(() => {
  elapsed = Math.round((Date.now() - start) / 1000) + 's'
  client.status((err, res) => console.log(`${err || 'got status response'} ${elapsed}`))
}, 2e3)
```

**Comment by ebuchman** [comment] 2017-06-26 21:23
Ok. I think this is fixed on develop: https://github.com/tendermint/tendermint/commit/e2ed15fa02e684ff07f094b7c325996a34929ccb#diff-692f910080346cdb0d29bfba93c21569R538

Problem was the ping ticker didnt have its own write deadline, so it was hitting the deadline from the last message write!

**Comment by srmo** [comment] 2017-06-26 22:04
Verified locally against v0.10.1 branch. Works as expected now. 
@mappum yeah, we didn't see this popping up in our first iterations too because of 1s intervals of asking for node-state.

**Closed** 2017-06-28 15:45 UTC
Labels: Area: RPC
