### ISSUE TITLE
Proposer description

### ISSUE THREAD

**Issue by okwme** [tendermint/tendermint#2306] opened 2018-08-31 08:56 UTC
Proposal: Improve the description of the proposer selection at https://github.com/tendermint/tendermint/blob/master/docs/spec/reactors/consensus/proposer-selection.md

I wanted to understand the proposer processes and began w the white paper at https://github.com/tendermint/tendermint/wiki/Byzantine-Consensus-Algorithm#proposals. This gave me a link to the "implementation" at https://github.com/tendermint/tendermint/blob/develop/types/validator_set.go#L49. I'm not sure if that link was correct but after reading through all i found was this:
```
func (vals *ValidatorSet) findProposer() *Validator {
	var proposer *Validator
	for _, val := range vals.Validators {
		if proposer == nil || !bytes.Equal(val.Address, proposer.Address) {
			proposer = proposer.CompareAccum(val)
		}
	}
	return proposer
}
```

A search in the repo for `proposer` gave me https://github.com/tendermint/tendermint/blob/master/docs/spec/reactors/consensus/proposer-selection.md. I updated the wiki to go to this link instead of the implementation but find this description difficult to follow and think it can be improved. It also seems like the proposer method shouldn't be hidden behind three links as it's so important.

**Comment by milosevic** [comment] 2018-08-31 10:53
Thanks a lot for bringing this up. We already have an open issue for this, https://github.com/tendermint/tendermint/issues/1558. Maybe we can close this issue for #1558.

**Comment by ebuchman** [comment] 2018-08-31 16:46
Yes, duplicate of https://github.com/tendermint/tendermint/issues/1558, but still needed !

**Closed by ebuchman** 2018-08-31 16:46 UTC

**Comment by okwme** [comment] 2018-08-31 17:58
👍
