### ISSUE TITLE
Capture v0.34 baseline metrics

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9123] opened 2022-07-28 14:36 UTC
The result of this issue should help to answer the question: "how do new releases, e.g. v0.37, compare to v0.34 in terms of performance and stability?"

Run a set of two testnets and collect the following on the v0.34.x kv store application for each:

1. All Prometheus metrics for the full duration of each execution so that we can do post-hoc analysis on the metrics. The kinds of metrics in which we're interested include, but are not limited to, the following:
   1. Consensus rounds per height
   2. Maximum connected peers, Minimum connected peers, Rate of change of peer connections
   3. Memory resident set size
   4. CPU utilization
   5. Blocks produced per minute
   6. Seconds for each step of consensus (Propose, Prevote, Precommit, Commit)
2. Transaction latency while varying the throughput of a client submitting transactions into a single node, with that client running on the same machine as that node. Throughput must be gradually increased until we reach saturation. In order to do this, we need the following:
   - [x] #9330 
   - [x] #9331
   - [x] Infrastructure/configuration to run the load generation tool, once the network has stabilized, with different transaction throughput rates.
3. _Stretch goal:_ capture the network topology for each testnet run. In order to do this, we need:
   - [ ] #9332

## 200 Node Testnet

Run a 200 node testnet with 5 seed nodes, 175 validators, and 20 non-validating full nodes. Run this for an hour and collect metrics. Next, restart the network but apply load to the network and collect the above metrics.

## Rotating Node Testnet

Real-world deployments of Tendermint frequently see new nodes arrive and old nodes exit the network. To test this, we will run a network with 10 validators and 3 seed nodes. A rolling set of 25 full nodes are started and each connects to the network by dialing one of the seed nodes. Once the node is able to sync to the head of the chain and begin producing blocks, it is stopped. Once stopped a new node takes its place.

## Dependencies:
- [x] https://github.com/tendermint/tendermint/issues/9165
- [x] https://github.com/tendermint/tendermint/issues/9166

**Comment by thanethomson** [comment] 2022-08-08 11:52
@williambanfield what's the intended output/artifact from capturing metrics here? Will it be a set of statistics for each of the metrics (min/max/average/std deviation), or a data dump from Prometheus, etc.?

Also, do you have an idea yet as to where we'll capture/store these artifacts?

**Comment by williambanfield** [comment] 2022-08-08 21:12
> Also, do you have an idea yet as to where we'll capture/store these artifacts?

I was considering storing them directly on this issue, although I'd be happy to store them instead as a document in a `baselines/` directory within the repo.

For each of the metrics, I would propose capturing both a screenshot of the graph of the prometheus query across the range as well as a set of concrete readings for each metric as follows:

* Consensus rounds per height
* Max, Min, Average 
* Connected peers
  * Minimum during the test, Maximum during the test, Average across the range, Standard deviation.
* Memory resident set size:
  * Average 50th, 75th, 90th, 95th, 99th percentile across the range. 
* CPU utilization
  * Average 50th, 75th, 90th, 95th, 99th percentile across the range. 
* Blocks produced per minute
  * Average across the range. 
* Seconds for each step of consensus (Propose, Prevote, Precommit, Commit)
  * Average 50th, 75th, 90th, 95th, 99th percentile across the range. 

I'm not exactly a statistician, so there may be better metrics possible. If anyone has suggestions for improvements that could be made to any of these, please let me know. For metrics where the "average across the range" is suggested, I mean to say that, for all time series points collected during the test or for all time series points created as the listed calculation, what is the average value. For example, if three observations were taken at 3 seconds, 6 seconds, and 9 seconds of 7, 5, and 3, then the average I am referring to would be 5.

**Comment by cason** [comment] 2022-08-10 07:01
It appears a lot of data to collect, and that this data should variate a lot in executions that matter, i.e., when we catch problems.

As a general approach, I would say to record data and periodically publish them. With the published data in hands (memory or disk), we can retrieve the specif metrics we want.

While this is not ideal for in production environments, this is the best solution for experimental environments.

**Comment by milosevic** [comment] 2022-08-15 13:44
I have a few clarifying questions: is an idea here to have baseline metrics for overall tendermint behaviour or we hope that capturing these metrics will help us understand subsystem behaviour (for example p2p or mempool). If we talk about general system behaviour, I think that it would be good to somehow capture time it takes for a tx to be included in a block. Also number of txs committed in a block and number of txs in the local mempools in time, so we can correlate the two. If we talk about p2p subsystem, we should probably have more control on the internal overlay structure. We should probably also try to understand how typical validator set ups look like and if there is relatively cheap way to understand how existing production overlays look like. I feel that 200 node set up is lacking more concrete information about the overlay structure we hope creating as that would affect results/metrics heavily. Ideally once we have a spec for p2p layer, we could potentially have better sense if there is a need to add more metrics and what are failure scenarios we would like to exercise.

**Comment by williambanfield** [comment] 2022-08-15 19:55
> internal overlay structure

I've seen this term a few times but I'm not sure I understand what is meant by it, could you provide some clarification?

> I have a few clarifying questions: is an idea here to have baseline metrics for overall tendermint behaviour or we hope that capturing these metrics will help us understand subsystem behaviour (for example p2p or mempool).

The goal with this specific issue was primarily to understand the p2p layer performance in v0.34.x so that we can determine what flaws may exist and attempt to address them as well as to understand if subsequent releases have caused any degradation. I think that if we want to gather additional metrics that help us capture a baseline for other components, that's reasonable and can continue to be tackled on other issues.

I also think that the [Releases](https://github.com/tendermint/tendermint/blob/main/RELEASES.md#minor-release-checklist) document captures a lot of this as well so it may be worth checking in that document for additional metrics that you think may be useful that are absent from the list in this issue.

> If we talk about general system behaviour, I think that it would be good to somehow capture time it takes for a tx to be included in a block. 

I think that it makes sense to capture this as well. I've opened https://github.com/tendermint/tendermint/issues/9258 to track capturing this in the proposed long-lived testnet.

**Comment by cason** [comment] 2022-08-16 12:12
Regarding this term, overlay network, a short definition is that it represents the network induced by the peer relationship. It is a graph, where two nodes are connected if they peers, i.e., if they are directly connected at p2p level. This terms only makes some sense if the peer relationship is not complete, namely, if there are nodes that are not peers. So, for a fully-connected network, the term overlay makes no sense, since the overlay network and the network are the same. The overlay network is, from this point of view, an instance of the network where only portion of the possible links are considered, as this is possible to transmit data from this potential link, since the nodes connected by this link are indeed connected at p2p level.

**Comment by cason** [comment] 2022-08-16 12:19
In terms of what we can measure, what metrics are of interest, regarding the network overlay produced by Tendermint, I suggest having a look on Section VII.A of our paper. It is very short, but we have two metrics present there: the distribution of the degree of nodes, and of the distance between nodes in the overlay. The degree is the number of peers of each node, while the distance is the minimum number of links between two nodes. For reference, if two nodes are peers, their distance is 1.

**Comment by williambanfield** [comment] 2022-08-16 22:34
>  the distribution of the degree of nodes, and of the distance between nodes in the overlay.

I think that we can pretty easily capture this metric. It is, I believe, the same as the listed metric of:
```
Maximum connected peers, Minimum connected peers, Rate of change of peer connections
```
In terms of distance, implementing that within the Tendermint stack is not simple within the current Tendermint stack. We don't have a centralized representation of that within any node, so we'd need to build some some special infrastructure to construct that from surveilling all of the nodes on the network. How useful is this metric to understand how well the Tendermint p2p stack is functioning in v0.34?

**Comment by cason** [comment] 2022-08-17 07:12
I both cases, distribution of degrees and distribution of distances, we need a snapshot of the network, which allows we to build a graph, from which we extract the metrics, There are other valuable metrics we can compute provided we have a graph representation, so I would suggest to collect data allowing us to produce this graph.

In the case of the experiments reported in the paper, we used the RPC endpoint of every node to collect their peers. We saved this data, that was parsed to produce a graph representation. Here we can possibly make it simple, having each node to periodically save its list of peers to, again, build a graph a posteriori and asynchronously. That would be my suggestion.

**Comment by cason** [comment] 2022-08-17 07:16
>  There are other valuable metrics we can compute provided we have a graph representation

It is possible to compute cut sets, that is, the number of nodes or links we need to remove to disconnect the graph. There are metrics we never explore that represent how "sparse" or "dense" a graph is, such as the the clustering factor.

In my opinion, the two distributions we used in the paper are a good start point, but we are aware that we could extract more interesting data from a graph representation, or the evolution of graph representations, of the produced network overlay.

**Comment by williambanfield** [comment] 2022-08-17 19:09
> I both cases, distribution of degrees and distribution of distances, we need a snapshot of the network, which allows we to build a graph, from which we extract the metrics

I'm not sure I understand the value of this metric. Would the goal be to survey this on real networks? It seems extremely random to me. This would vary highly with 1. who dialed which peers when and 2. how many free outgoing and incoming network slots each peer has configured. These are all so varied within publicly running networks that I'm not sure I see the value in even investigating. Similarly, any constructed network is so unlikely to match the variability of real world networks I don't see this as being a particularly meaningful exercise either.

> In the case of the experiments reported in the paper, we used the RPC endpoint of every node to collect their peers. We saved this data, that was parsed to produce a graph representation. 

Does the code to do this still exist? Writing a crawler to discover peers and dial them to learn about connected peers is somewhat non-trivial so if it is already done I'd prefer to reuse it.

**Comment by cason** [comment] 2022-08-18 09:27
>  It seems extremely random to me.

Well, the number of peers of an individual node should be random, like you described. But when we collect the random values for each individual, the big picture should be pretty similar in multiple networks. This big-picture, this distribution of individual behaviors, is what I consider to be a metric of the network. Ideally, while the same node will have a distinct number of peers in multiple executions of the network, we should have about the same number of peers with each degree in any two networks with the same size and setup. In other words, the random behavior of each individual is expected, but the overall behavior of the random networks should have some patterns. Those general patterns is what we want to detect, discover, because at the end this is the important information that we can provide to users: while we cannot (and don't want) to ensure a predictable behavior for each node, we could (or want to) ensure some predictable behavior for any collection of nodes, for a network.

**Comment by cason** [comment] 2022-08-18 09:30
> Does the code to do this still exist?

I think so, I will try to find it. I assume it is just a periodical call to this endpoint: https://docs.tendermint.com/master/rpc/#/Info/net_info

**Comment by williambanfield** [comment] 2022-08-18 14:12
> I think so, I will try to find it. I assume it is just a periodical call to this endpoint:

This can be done in networks we control, but not in public networks so I'm assuming this is just for internally run networks? 

> while we cannot (and don't want) to ensure a predictable behavior for each node, we could (or want to) ensure some predictable behavior for any collection of nodes, for a network.

I'm trying to understand what value this will provide to users. With this information, what could a user do? What would we do to change Tendermint with this information in a way to help users?  Our users mostly care that they are able to quickly join the network, maintain a stable list of peers with who they are able to successfully and quickly exchange messages. It seems that the distance between nodes on a network is only somewhat related to this.

**Comment by cason** [comment] 2022-08-18 14:28
> With this information, what could a user do? 

Change parameters. If users believe that the number of connections are excessive, nodes have too much peers "on average", they can reduce the number of connections a node attempts to establish (outbound) or accept (inbound). They will change this parameters based on the experimental evidence we provide to them of the actual impact of these changes not in a single node, but in the network as a whole. If they realize that less connections do not cause the distances to be larger, i.e., the diameter of the network is unlikely to be affected, they might adopt a different set of parameters.

**Comment by cason** [comment] 2022-08-18 14:31
> This can be done in networks we control, but not in public networks

This is true. We used RPC endpoints because we didn't want, and actually didn't have the ability, of instrumenting Tendermint instances for recording this information.

The main point here is not how to achieve this information, since as it is available via (possibly unsafe) RPC endpoint, so it is trivially provided as a metric. The point here is that this information cannot be achieved from a single node, as we need to build a graph representing the overlay network, from data only observable by individual nodes.

**Comment by williambanfield** [comment] 2022-08-18 16:53
> This is true. We used RPC endpoints because we didn't want, and actually didn't have the ability, of instrumenting Tendermint instances for recording this information.

We don't have access to the RPC endpoint of nodes running in public networks and we likely don't have access to their metrics either. We also don't gossip this information so it's very unclear to me how, in a public network, we can actually build this at all on non-internal networks.

> If they realize that less connections do not cause the distances to be larger, i.e., the diameter of the network is unlikely to be affected, they might adopt a different set of parameters.

It seems to me that this information will be incredibly network specific and that our modeling of this in internal networks will be very limited. Public networks run with highly variable values for incoming and outgoing connections. Nodes connect to some entry point node they found in a discord server, and then connect to whatever peers score highly among the peers of _that_ initial node. The network topology will be so variable across different network with different existing configurations that I really do not understand how we can provide meaningful data to users with what we can observe. additionally, even between two networks with identical configuration parameters the topology may be very different as a result of dialing order (who dialled who when).

**Comment by thanethomson** [comment] 2022-08-18 20:16
The scope of this issue is becoming unclear to me. Perhaps we should clarify what exactly the "definition of done" is for this particular issue within the context of the v0.37 release this quarter?

My understanding is that one major result of the P2P-related work this quarter is that we need an evaluation framework to determine whether a new release performs better/worse than the previous one. In our case, we want to specifically check whether v0.37 performs better or worse than v0.34.

In order to do that, we need to capture these baseline metrics for v0.34. Are the tests outlined in the issue description sufficient for establishing a reasonable answer to this question for this quarter? (Something that can always be improved on in subsequent releases)

Or @milosevic do you have a different understanding of the scope of this issue?

**Comment by cason** [comment] 2022-08-19 05:00
> We don't have access to the RPC endpoint of nodes running in public networks

The metrics are to be retrieved from testnets, aren't them? Well, my suggestions are outlined in previous comments, I don't think they require data that is particular hard to obtain in testnets, and I think it produces valuable information about Tendermint networks.

**Comment by thanethomson** [comment] 2022-08-19 10:12
> I think it produces valuable information about Tendermint networks

Are they really valuable though, given that our testnets are pretty artificial compared to mainnets?

**Comment by cason** [comment] 2022-08-23 06:39
> Are they really valuable though, given that our testnets are pretty artificial compared to mainnets?

I think they are. The main difference of testnest to mainnets is the fact that the validators in mainnets are hidden from the rest of the network (sentry architecture). I have the impression that the "public" part of a mainnet, essentially composed by sentry nodes, has essentially the same "shape" of a testnet. So, while validators have a very particular setup, that is concealed by design, their sentry nodes establishes connections with the sentry nodes of other validators in an essentially random way, using the mechanism for producing essentially random network overlays provided by the p2p layer.

**Comment by jsteenb2** [comment] 2022-09-20 00:19
One metric I don't see mention of is one to capture syncing (in all 3 forms consensus|fast|state syncs) an old node with the latest. I think this would be a good addition to our baseline metrics. This could be run at the end of the test run perhaps by starting (1-N) new nodes and putting them in different sync mechanisms, to see how long it takes to catch up. 

I've been looking at this a fair bit as of late for the narwhal work, and its not clear to me what rules of thumb/expectations we have set for syncing. Setting a baseline would be nice to see if we have regressed in any clear way. Additionally this metric could be used to inform users operating nodes of what our a 200 node cluster(as proposed). This is something any operator introducing a new node to an existing cluster will run into.

**Comment by sergio-mena** [comment] 2022-09-30 15:19
@jsteenb2 I share that concern. This is the first iteration of the QA process. Highly manual and time consuming, so we need to be realistic about what we can do for v0.37.x.

Having said that, one of the testsnets we have selected (and just finished running and collecting data for, thanks @williambanfield !) is the [rotating node](https://github.com/tendermint/tendermint/blob/main/RELEASES.md#rotating-node-testnet), which partially addresses your concerns (it's doing blocksync, but not statesync).

**Comment by thanethomson** [comment] 2022-09-30 16:47
> @jsteenb2 I share that concern. This is the first iteration of the QA process. Highly manual and time consuming, so we need to be realistic about what we can do for v0.37.x.

Agreed. We always knew that there were going to be _tons_ of different things we could test, but we needed to start somewhere. We could potentially plan in this kind of testing for v0.38 if we have capacity.

**Closed** 2022-10-17 20:08 UTC
