### ISSUE TITLE
Missing documentation: non-unique tag keys

### ISSUE THREAD

**Issue by feldgendler** [tendermint/tendermint#2905] opened 2018-11-24 15:59 UTC
**Tendermint version**: 0.22.8

Sorry for not following the bug template. This is a documentation bug, so most of that is irrelevant here.

`DeliverTx` can return, for a single transaction, several tags with the same key, since `Tags` is a list, not a map. The documentation is silent on whether it's allowed, and what will happen.

My current understanding from reading the code is that it works, and causes the transaction to be searchable using `TxSearch("key='value'", ...)` with either value. However, I'm not sure about ranges for numeric tags, and about whether subscriptions are going to work correctly.

I would like to use this if it's possible, but only if it's a documented feature rather than an unindended side effect.

On the other hand, if it _is_ an unintended side effect, then duplicate tags should better be prohibited. The best way to do that is to define the tag set as a map rather than a slice.

**Comment by melekes** [comment] 2018-11-26 11:50
We do not support duplicated keys right now. And you're right. We could've done a better job documenting this.

Refs #1859
Possible duplicate of #1385

**Comment by feldgendler** [comment] 2018-11-26 13:09
In this case, is there a reason why `Tags` in `ResponseDeliverTx` should be a list rather than a map?

**Comment by ebuchman** [comment] 2018-11-26 22:43
Primarily because maps are not ordered, and we need to use deterministic structures that can be hashed consistently on all nodes.

We have been considering changing the list to a list of lists. We can also consider a map, and use a deterministic ordering, eg. alphabetical sorting by key. 

This is still an open design question. Obviously things can be improved here, so we'd love more input. See https://github.com/tendermint/tendermint/issues/1859 and [ADR-021](https://github.com/tendermint/tendermint/blob/develop/docs/architecture/adr-021-abci-events.md) for an initial write-up of the list-of-list idea.

**Comment by ValarDragon** [comment] 2018-11-26 23:07
> Primarily because maps are not ordered, and we need to use deterministic structures that can be hashed consistently on all nodes.

hashmaps aren't ordered, tree maps are. We could use a tree map.

**Comment by feldgendler** [comment] 2018-11-27 09:30
Unless a single transaction has thousands of tags, the differences in efficiency between different kinds of map-like structures shouldn't matter.

**Comment by melekes** [comment] 2019-06-12 12:57
Done in https://github.com/tendermint/tendermint/pull/3643

We now support non-unique key tags through something called `Events`. Please refer to 
https://github.com/alexanderbez/tendermint/blob/91aab82e1c1b2d3cb185a30127277606ed6a2d66/docs/spec/abci/abci.md#events for details (later will be available at https://tendermint.com/docs/spec/abci/abci.html#events)

**Closed by melekes** 2019-06-12 12:57 UTC
Labels: docs
