### ISSUE TITLE
BroadcastTxCommit hangs if CheckTx returns non-zero code

### ISSUE THREAD

**Issue by ant1g** [tendermint/tendermint#7678] opened 2022-01-23 20:47 UTC
**v0.35.0** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

https://github.com/ant1g/tendermint-built-in

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS BigSur 11.6
- **Install tools**: Golang v1.17.2
- **Others**:

**What happened**:
In the tendermint kvstore tutorial app, using the built-in deployment (ABCI app compiled with tendermint node), the BroadcastTxCommit function does not appear to behave properly.
First of, you can find in the repo url above an updated version of the kvstore tutorial app that works with the latest version of tendermint (v0.35.0), a PR is on the way to update the repo documentation.

If I submit a transaction that is rejected by the CheckTx function, the call will simply hang forever.
For example this will cause the hanging, as the validate function the ABCI app will expect a "=value" to be present and therefore the CheckTx will return non-zero code:
```
curl -s 'localhost:26657/broadcast_tx_commit?tx="tendermint"'
```

Where this works:
```
curl -s 'localhost:26657/broadcast_tx_commit?tx="tendermint=rocks"'
```

Additionally, re-running a previously successful transaction will also cause the BroadcastTxCommit to hang forever.
Run a second time:
```
curl -s 'localhost:26657/broadcast_tx_commit?tx="tendermint=rocks"'
```

**What you expected to happen**:

I expect the function call to return and to have the results of the CheckTx (check the non zero error code and the data field).
In the case of a replay of an old transaction, some special error code perhaps?

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Simply run the tutorial sample app with the latest version of tendermint, following the instructions in my repo (very simple).

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
I do see in the tendermint logs that the transaction is rejected, but nothing else:

```
2022-01-23T21:43:09+01:00 INFO rejected bad transaction code=1 module=mempool peer_id= post_check_err=null priority=0 tx=F6C3848FC2AB9188DD2C563828019BE7CEE4E269F5438C19F5173F79898E9EE6 version=v1
```

**Config (you can paste only the changes you've made)**:
The config is literally all defaults, apart from:
moniker = "node-0"
mode = "validator"

**node command runtime flags**:
N/A

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "round_state": {
      "height": "54",
      "round": 0,
      "step": 1,
      "start_time": "2022-01-23T20:44:45.14114Z",
      "commit_time": "2022-01-23T20:44:44.14114Z",
      "validators": {
        "validators": [
          {
            "address": "DB3788DC7D6EF8495ACF47B07BB34440CD4B0AC3",
            "pub_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "RUnvGtc5/xEs3g+4oDj8B57ZEWYyFB+OFKM1fiaC/dE="
            },
            "voting_power": "1",
            "proposer_priority": "0"
          }
        ],
        "proposer": {
          "address": "DB3788DC7D6EF8495ACF47B07BB34440CD4B0AC3",
          "pub_key": {
            "type": "tendermint/PubKeyEd25519",
            "value": "RUnvGtc5/xEs3g+4oDj8B57ZEWYyFB+OFKM1fiaC/dE="
          },
          "voting_power": "1",
          "proposer_priority": "0"
        }
      },
      "proposal": null,
      "proposal_block": null,
      "proposal_block_parts": null,
      "locked_round": -1,
      "locked_block": null,
      "locked_block_parts": null,
      "valid_round": -1,
      "valid_block": null,
      "valid_block_parts": null,
      "votes": [
        {
          "round": 0,
          "prevotes": [
            "nil-Vote"
          ],
          "prevotes_bit_array": "BA{1:_} 0/1 = 0.00",
          "precommits": [
            "nil-Vote"
          ],
          "precommits_bit_array": "BA{1:_} 0/1 = 0.00"
        }
      ],
      "commit_round": -1,
      "last_commit": {
        "votes": [
          "Vote{0:DB3788DC7D6E 53/00/SIGNED_MSG_TYPE_PRECOMMIT(Precommit) 2FF23F9A2697 97AC92893218 @ 2022-01-23T20:44:44.116922Z}"
        ],
        "votes_bit_array": "BA{1:x} 1/1 = 1.00",
        "peer_maj_23s": {}
      },
      "last_validators": {
        "validators": [
          {
            "address": "DB3788DC7D6EF8495ACF47B07BB34440CD4B0AC3",
            "pub_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "RUnvGtc5/xEs3g+4oDj8B57ZEWYyFB+OFKM1fiaC/dE="
            },
            "voting_power": "1",
            "proposer_priority": "0"
          }
        ],
        "proposer": {
          "address": "DB3788DC7D6EF8495ACF47B07BB34440CD4B0AC3",
          "pub_key": {
            "type": "tendermint/PubKeyEd25519",
            "value": "RUnvGtc5/xEs3g+4oDj8B57ZEWYyFB+OFKM1fiaC/dE="
          },
          "voting_power": "1",
          "proposer_priority": "0"
        }
      },
      "triggered_timeout_precommit": false
    },
    "peers": []
  }
}
```

**Anything else we need to know**:
N/A

**Comment by Halimao** [comment] 2022-01-25 06:32
`re-running a previously successful transaction will also cause the BroadcastTxCommit to hang forever`

the reason why re-running a previously successful transaction cause BroadcastTxCommit to hang forever, is duplcate transaction error will be ignored and return none error imediately, then the callback function `func(res *abci.Response) { resCh <- res }` has no chance to execute. And routine hangs forever by `r := (<-resCh).GetCheckTx()`

**Comment by ant1g** [comment] 2022-01-25 08:19
Thanks for the feedback. How would a client application developer (using broadcast_tx_commit) go about identifying duplicates then?

**Comment by Halimao** [comment] 2022-01-25 08:28
ah, in my opinion, this is a bug, and need to be fixed. we needn't care about it in client side

**Comment by Halimao** [comment] 2022-01-25 08:30
also, if duplicate tx shouldn't return an error, then callback function need to be handle before return

**Comment by ant1g** [comment] 2022-01-25 08:33
> ah, in my opinion, this is a bug, and need to be fixed. we needn't care about it in client side

All right thanks, I thought you were saying it was the expected behaviour!

**Comment by ant1g** [comment] 2022-01-25 20:30
Thanks, I'll test it.

**Comment by Halimao** [comment] 2022-01-26 01:16
Duplicate transaction still won't propagate error to caller, as following code still return none error

https://github.com/tendermint/tendermint/blob/master/internal/mempool/mempool.go#L261-L271

**Comment by ant1g** [comment] 2022-01-26 09:15
Same, I have tested the fix, it solves the invalid TX problem, but not the duplicate one.

**Comment by tychoish** [comment] 2022-01-26 15:05
> Duplicate transaction still won't propagate error to caller, as following code still return none error, and callback function isn't handled too
> 
> https://github.com/tendermint/tendermint/blob/master/internal/mempool/mempool.go#L261~L271
> 
> I have test this using the latest master commit, still causing hang problem by duplcate transaction

Looking at the code a bit more, it seems like the only case where we return a nil error is where the transaction exists in the cache (e.g. Push returns false) but then the Tx store doesn't have the transaction. I think can only happen if the transaction in question is committed (e.g. it's still in the cache, but not in the mempool because its in a block.) I'll look into this more later today.

One thing to note here, is that `broadcast_tx_commit` is not a great API. In previous versions, the method submitted a tx to the mempool and then subscribed to events for that transaction, which had the possibility of putting backpressure on consensus itself, because if the event subscription slows down in processing events the consensus process can't submit them, and things grind to a halt. 

Arguably this method shouldn't even exist: because the "commit" part happens (potentially) on a different node, the safe/correct thing to do is to submit a transaction (broadcast_tx_sync), and if it makes it into the mempool, callers can query for the tx in the blocks themsevles, and once the tx is in the block then you know that it's committed and you can move on. 

The current implementation mirrors this ideal implementation as a convenience method: we submit the tx (as in braodcast_tx_sync) and then if there's no error reported, we poll to see the tx committed. It's not perfect, but there's no possibility for broadcast_tx_commit to bring down the node, which seems like a good thing, but there may still be holes. 

I'll work on a test case, but if you have anything that reproduces this, I'd definitely be interested in seeing it. I suspect that there's some interleaving of events that causes either: a) the transactions to not be duplicates in some way, or b) causes one transaction to land and the other to get stuck in a different place. 

I'd also be interested to see if the same problem reproduces using broadcast_tx_sync, which I imagine it would.

**Comment by ant1g** [comment] 2022-01-26 21:52
Simply run a fresh node locally and call twice:

```curl -s 'localhost:26657/broadcast_tx_commit?tx="tendermint=rocks"'```

The first call will succeed, the second one will hang forever.

You are suggesting to do a `/broadcast_tx_sync` then poll the `/tx` endpoint for a matching hash, until it returns. Correct?
What if it fails at DeliverTx?

**Comment by jonasbostoen** [comment] 2022-01-27 18:35
Should the check not return a `types.ErrTxInCache` error as well instead of `nil` at `internal/mempool/mempool.go:270`? This is what causes the block as the code proceeds to a permanently blocking channel at `internal/rpc/core/mempool.go:48`. I've tested this and it works, but I might have missed any other side effects @tychoish.

```
$ curl -s 'localhost:26657/broadcast_tx_sync?tx="tendermint=cool"'
{"code":0,"data":"","log":"","codespace":"","mempool_error":"","hash":"2A5F107D1A0C44703C88736A6AC81E5A117B34EEA1CD50CEF09239999501B0F6"}%                              
$ curl -s 'localhost:26657/broadcast_tx_sync?tx="tendermint=cool"'
{"code":-32603,"message":"Internal error","data":"tx already exists in cache"}
```

**Comment by tychoish** [comment] 2022-01-27 21:02
Ok! We did some talking about this internally, and came to a few conclusions:

- `broadcast_tx_commit` remains a bit of a wart. Because of the async nature of the underlying checktx abci (vis a vis this call,) and the fact that transactions can pass checktx but then fail later on for various reasons, can lead to this method blocking for longer than it should because it doesn't have enough context to be smarter. For this reason, we should probably eventually figure out some other workflow for submitting transactions and confirming that they're in a block (client side) rather than using this method. 
- looking at previous implementations of the mempool and looking at this implementation a bit more, it seems reasonable to change `internal/mempool/mempool.go:270` to return an error, and my #7714 change should do this. The [legacy implementation](https://github.com/tendermint/tendermint/blob/v0.34.15/mempool/clist_mempool.go#L272-L286) may be useful here.

Hope this helps!

**Closed** 2022-01-27 21:44 UTC
