### ISSUE TITLE
defaultSetProposal will set cs.ProposalBlockParts, this may lead to interrupt the block receiving process of PoLC's BlockID

### ISSUE THREAD

**Issue by james-ray** [tendermint/tendermint#2567] opened 2018-10-07 04:52 UTC
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
I think there are 2 situations when a node needs to receive block parts,
1. it receives a proposal of the round, so it needs to receive the proposalBlock from the proposer
2. it receives a PoLc, so it has got a BlockID which contains a BlockPartsHeader. This situation will also set cs.ProposalBlockParts ,but it can go without receiving the proposal.

So how about the situation 2 when latter the proposal comes, it will override cs.ProposalBlockParts . It will lead to interrupt the block receiving of PoLC's BlockID.

**What you expected to happen**:
I suggest we can add a cs.LockedBlockID to indicate we are now receiving blockParts because we have a lockedBlockID.
Now in defaultSetProposal, we can judge 
if cs.LockedBlockID !=nil {
   return
}

so the cs.ProposalBlockParts won't be overwritten.

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by james-ray** [comment] 2018-10-08 03:49
Thanks for the reply. But I still have 2 questions:
1. cs.ProposalBlockParts = types.NewPartSetFromHeader(blockID.PartsHeader)
this code, I don't know how to make its peer know it needs this ProposalBlockParts , which means, notify its peer's prs.ProposalBlockPartsHeader be updated to that one. 

2. the codes below, consensus/reactor.go   line 490    ,  helps me to understand too.
	// If the peer is on a previous height, help catch up.
		if (0 < prs.Height) && (prs.Height < rs.Height) {
			heightLogger := logger.With("height", prs.Height)

			// if we never received the commit message from the peer, the block parts wont be initialized
			if prs.ProposalBlockParts == nil {
				blockMeta := conR.conS.blockStore.LoadBlockMeta(prs.Height)
				if blockMeta == nil {
					cmn.PanicCrisis(fmt.Sprintf("Failed to load block %d when blockStore is at %d",
						prs.Height, conR.conS.blockStore.Height()))
				}
				ps.InitProposalBlockParts(blockMeta.BlockID.PartsHeader)
				// continue the loop since prs is a copy and not effected by this initialization
				continue OUTER_LOOP
			}
			conR.gossipDataForCatchup(heightLogger, rs, prs, ps, peer)
			continue OUTER_LOOP
		}

this code , ps.InitProposalBlockParts(blockMeta.BlockID.PartsHeader)     will set the ps.ProposalBlockPartsHeader to ours, then we begin our block transferring.

But I wonder if the peer will definitely  accept the parts , the peer may receive 2/3+ precommits but not including a maj23, so it went to the next round, which will clears its proposalBlock related state,
in consensus/state.go  line 764
	if round == 0 {
		// We've already reset these upon new height,
		// and meanwhile we might have received a proposal
		// for round 0.
	} else {
		logger.Info("Resetting Proposal info")
		cs.Proposal = nil
		cs.ProposalBlock = nil
		cs.ProposalBlockParts = nil
	}
so, because 	cs.ProposalBlockParts = nil , the peer will refuse to accept the block parts .

**Comment by goolAdapter** [comment] 2018-10-08 04:54
It's hard to proof the consensus process, I can only mark some opinion.
a. Each round is start by a Proposer, once the Proposer decided an Proposal, it gossip to other validator,  in your first question, It's not validator to ask ProposalBlockParts, but other validator send it's own Proposal to it. at this time, something else must wrong，but maj23 is ok，so just change the ProposalBlockParts to the maj23， maj23 validators will continue send ProposalBlockParts.  and finally got the correct ProposalBlock. It may fail at this round，but terminate can guaranteed.
b. In your second question, it‘s catchup logic, not the normal consensus process.

**Comment by james-ray** [comment] 2018-10-08 08:02
Thanks for the clarification. Let's assume a situation:
Now we are in round 2, and round 2 proposer propose a block and the block has reached 2/3+precommit.
However, nodeA dosen't collect them, it has collected another 2/3+precommit which round 2 proposer's block doesn't get 2/3, so it enterPrecommitWait , and later timeout, it enterNewRound,  round 3.
In round 3, it has received the residual round 2 precommits, it realizes it has a maj23 in round 2. So it set its ProposalBlockParts ready to receive round 2 proposer's block. At the same time, as you said, the round 2 proposer are indeed sending out ProposalBlockParts.  But , the round 3 proposer happened to be just the same situation as nodeA, it has enter round 3 too, so it propose a new proposal. Now the NodeA's receiving process may be interrupted because of the arrival of round 3' proposal.

Maybe I am understanding wrong, thanks for telling me.

**Comment by goolAdapter** [comment] 2018-10-09 02:10
You are right，and I think this is why timeout value is important. #1745 looks ref to this issue.

**Comment by ebuchman** [comment] 2018-10-12 04:29
> So how about the situation 2 when latter the proposal comes, it will override cs.ProposalBlockParts . It will lead to interrupt the block receiving of PoLC's BlockID.

> In round 3, it has received the residual round 2 precommits, it realizes it has a maj23 in round 2. So it set its ProposalBlockParts ready to receive round 2 proposer's block. At the same time, as you said, the round 2 proposer are indeed sending out ProposalBlockParts. But , the round 3 proposer happened to be just the same situation as nodeA, it has enter round 3 too, so it propose a new proposal. Now the NodeA's receiving process may be interrupted because of the arrival of round 3' proposal.

Really good question. We should write a test for this case. But here's why I don't think there is a bug right now:

If we see a commit for Round 2 once we're already in Round 3, we'll do `enterCommit` for Round 2. We'll realize we don't have the blockparts, and set up the ProposalBlockParts to receive it. At the end of `enterCommit` (in the defer), we do:

```
cs.updateRoundStep(cs.Round, cstypes.RoundStepCommit)
```

so the round doesn't change (still Round==3), but we change step (Step==Commit). We also call `cs.newStep()`, which causes us to send CommitStepMessage to our peers, telling them what block parts we have so they can send us the rest.

At this point, we might receive a proposal for round 3. This will trigger defaultSetProposal, which contains this saviour:

```
	// We don't care about the proposal if we're already in cstypes.RoundStepCommit.
	if cstypes.RoundStepCommit <= cs.Step {
		return nil
	}
```

So in the situation you've described, where we already moved to the commit step, the proposal won't get overwritten.

Does that explain this?

**Comment by james-ray** [comment] 2018-10-12 09:38
Thanks for the explanation!  I miss the most crucial part! The saviour part :)

There is no bug.
Still I want to make a suggestion for performance. 

Now enterPrecommit may find we don't have the PoLc BlockID's block, so we set ProposalBlockParts to ready to receive it. But it can be interrupted by current round proposal, right?
How about 
1.we receive LockedBlockPart and ProposalBlockParts concurrently,  as my pr #2591 does
2.If a node both has LockedBlock and ProposalBlock, set cs.ProposalBlock=cs.LockedBlock and cs.ProposalBlockPart=cs.LockedBlockPart   to give cs.LockedBlockPart a higher priority to broadcast.

Maybe it will speed up the convergence process?

**Comment by ebuchman** [comment] 2018-10-12 21:09
> Now enterPrecommit may find we don't have the PoLc BlockID's block, so we set ProposalBlockParts to ready to receive it. But it can be interrupted by current round proposal, right?

We shouldn't get to `enterPrecommit` until we're past the proposal, so it should never happen that the proposal will overwrite something that happened in enterPrecommit in the same round.

Also, see the recent updates in #2540 

Ok to close this?

**Comment by james-ray** [comment] 2018-10-13 15:05
Let me assume a situation again.
Round 0 , 2/3+ nodes has prevote round 0 proposal. However, not all of them have received all the 2/3+ prevotes. Say one or two of them didn't collect them all, and the other less than 1/3 may have collected the PoLc, however they enterPrecommit and find they may not have the proposalBlock. They set proposalBlockPart to receive the block, but timeout and precommit nil. So very pitiful, round 0 finally didn't reach 2/3+ precommit .
In Round 1, one situation is the round 1 proposer has locked the block in round 0, then it would send the same proposalBlock in round 0. One bad situation is it is the node that didn't collect PoLc in round 0, so it will propose a new block. Then the new block and will compete with the LockedBlock in round 0. There are 2 possibilities: 
1 is the less than 1/3 in round 0 have received the proposalBlock in round 0,so they locked that block too, so the lockedBlock is likely to win. 
2 is the less than 1/3 in round 0 almost didn't receive complete the proposalBlock in round 0. This situation, the lockedBlock will fail definitely. 

So how about the lockedBlock validator continue to send out the lockedBlock, while they are receiving round 1 proposal at the same time. So when it is the time for round 1 node enterPrevote, it depends on the lockedBlock in round 0 has or not been completely received, if it is, it will vote for the LockedBlock, otherwise if will vote for the round 1 proposalBlock.    Basically the lockedBlock is more likely to win, because lots of nodes which are locked that block in round 0 are continuously sending out the block. And the round 1 proposer is only 1 node.

**Comment by james-ray** [comment] 2018-10-15 03:01
Now, we set to receive the lockedBlock in enterPrecommit, we can only enter current round's enterPrecommit. If the vote.Round<cs.Round, enterPrecommit will immediately return.  So enterPrecommit will only set to return current round's LockedBlock, it could only be the ProposalBlock. 
However, because setProposal will set cs.ProposalBlockParts=nil , it can still interrupt the receiving process to make it receive again if not having received the proposal before. The situation is rare, because normally the proposal is generated first, but it can still possibly happen, due to network package loss or something, the proposal may not reach some nodes but 2/3+ votes reach first, then the proposal has come.

**Comment by ebuchman** [comment] 2018-10-15 20:10
Thanks @james-ray - it's my understanding that this is not a bug, but a proposed optimization. Is that correct? If so, can we close this issue and open a new one documenting the proposed optimization? I'm afraid we don't have much time/bandwidth to optimize the consensus more before we launch Cosmos. The much more important thing for us now is to ensure the current code aligns with the formal spec in https://github.com/tendermint/spec. Any optimizations will have to come later, with an appropriate modification to or extension of the spec. 

Thanks!

**Closed** 2018-10-16 07:58 UTC
Labels: bug, consensus, user
