### ISSUE TITLE
Subscribing to unconfirmed transactions from mempool

### ISSUE THREAD

**Issue by feizerl** [tendermint/tendermint#7059] opened 2021-10-05 02:23 UTC
Hello,

Currently there is a method called `/unconfirmed_txs` which one can query to get the current set of unconfirmed transactions in the mempool. However, this is a pull based mechanism in which the end user has to keep making these requests. Doing it too fast means they have to handle duplicates, doing it too slow means they will potentially miss transactions. 

There is an option `subscribe` where one can provide a filter and subscribe to events via websocket. However, based on my understanding of the docs, this is after the events have been confirmed, and not the unconfirmed txns in mempool.

Is there a way one can subscribe to txns as they enter mempool? (e.g. on ethereum, there are services like https://www.blocknative.com/ which let you subscribe to contents of mempool).

Thanks.

**Comment by creachadair** [comment] 2021-10-06 19:03
Hello! Right now it is _not_ possible to subscribe to these events on the consensus node's event stream. The node only indexes events related to committed blocks. At the moment, that RPC endpoint may be your best workaround on the Tendermint side.

It is technically possible to add additional events to the stream the consensus node provides, though we don't currently have any plans to do so right now. It's not an unreasonable request. I have some implementation concerns, because the event-subscription system is already susceptible to some load-related performance issues, but those are probably fixable.

Although this isn't on our roadmap right now, I'd be interested to learn more about the use cases you have in mind for this feature, and any other insights you have about the benefit for the app ecosystem. Having more context is really helpful for our planning and prioritization.

On a related note: If you control the application, another possible approach would be to have the app itself record unconfirmed transactions, if that's an important data stream for your particular app.

**Comment by feizerl** [comment] 2021-10-14 01:28
@creachadair I was wondering how would one go about doing this?

I have some free cycles and can contribute towards this. (Please note that I have never developed on tendermint before and this is probably not a first time issue, but I have a feeling that I will learn a lot doing this). 

Thanks!

**Closed** 2021-12-11 04:21 UTC

**Comment by silvercondor** [comment] 2022-01-08 10:55
hi, was this implemented? if yes then what is the tm.event key i should use please. Thanks!

**Comment by Cryptome2** [comment] 2022-01-26 09:22
> This would be a very useful feature considering this is one of the only endpoints where you can miss data if you don't refresh fast enough. I have a local node and query it every 0.001 seconds, and yet I still miss some transactions because they go by so fast. Subscribing would completely alleviate this issue and wouldn't require us to query every milisecond.

I found there are accounts that can send tx never visible in the unconfirmedtx. No idea how they can do this.

**Comment by Imafe** [comment] 2022-01-26 19:42
> > This would be a very useful feature considering this is one of the only endpoints where you can miss data if you don't refresh fast enough. I have a local node and query it every 0.001 seconds, and yet I still miss some transactions because they go by so fast. Subscribing would completely alleviate this issue and wouldn't require us to query every milisecond.
> 
> I found there are accounts that can send tx never visible in the unconfirmedtx. No idea how they can do this.

That could also be a possibility, however it would be hard to know for sure whether those tx never showed up in unconfirmedtx, or whether you just didn't query fast enough and it got confirmed inbetween 2 of your queries. Hence why I think a websocket subscription for this would be a of great use.

**Comment by Cryptome2** [comment] 2022-01-27 09:01
I agree

**Comment by ice-cronus** [comment] 2022-10-27 08:51
@creachadair 

> On a related note: If you control the application, another possible approach would be to have the app itself record unconfirmed transactions, if that's an important data stream for your particular app.

Any idea where to inject logic in app to record unconfirmed TXs? For me the best option is to put it into broadcast tx endpoint, but it is handled by temdermint, not the app itself. Any idea how to stream all TXs from mempool without tendermint fork?

**Comment by JackG-eth** [comment] 2022-11-16 17:22
@feizerl did this ever get implemented?
