### ISSUE TITLE
unexpected *types.Response_Flush when response to *types.Request_Info expected

### ISSUE THREAD

**Issue by simbro** [tendermint/tendermint#6016] opened 2021-01-29 17:10 UTC
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.34.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

js-abci example app
rust-abci example app

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS Cataline 10.15.7 
- **Install tools**: installed from binary
- **Others**:

**What happened**:

ran `tendermint init`, then ran `tendermint node`

in another terminal window, tried running some of the example apps:

```
$ cd js-abci/examples
$ npm i
$ node counter.js
```

```
$ cd rust-abci
$ cargo run --example empty_app
```

**What you expected to happen**:

I expected the example counter app to run as documented, instead, in each case I received the following error:

> ERROR: failed to create node: error during handshake: error calling Info: unexpected *types.Response_Flush when response to *types.Request_Info expected

**Have you tried the latest version**: yes/no

yes, I've tried with 0.34.3

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

`$ tendermint node   `

> E[2021-01-29|16:59:14.343] Stopping abci.socketClient for error: unexpected *types.Response_Flush when response to *types.Request_Info expected module=abci-client connection=query
> E[2021-01-29|16:59:14.343] query connection terminated. Did the application crash? Please restart tendermint module=proxy err="unexpected *types.Response_Flush when response to *types.Request_Info expected"
> ERROR: failed to create node: error during handshake: error calling Info: unexpected *types.Response_Flush when response to *types.Request_Info expected

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by erikgrinaker** [comment] 2021-01-29 17:17
Hi! This is caused by the client not being compatible with the 0.34.0 protocol, rust-abci only supports 0.33.

**Comment by simbro** [comment] 2021-01-29 17:31
Thanks @erikgrinaker - I didn't realize that - I have to log my machine now but I'll try the process again tomorrow with 0.33 and let you know how I get on.

**Comment by erikgrinaker** [comment] 2021-01-29 17:36
Great, let us know if you have any issues -- will close this meanwhile.

**Closed by erikgrinaker** 2021-01-29 17:36 UTC

**Comment by simbro** [comment] 2021-02-01 09:41
FYI:  it worked when I installed version v0.33.0.  The js-abci example app (counter.js) worked as expected.  the rust-abci doesn't work, but for some other reason.  Thanks for your help @erikgrinaker .
