### ISSUE TITLE
Error: Could not create directory /tendermint/config. mkdir /tendermint/config: permission denied

### ISSUE THREAD

**Issue by gzuhlwang** [tendermint/tendermint#1538] opened 2018-05-07 07:40 UTC
**Tendermint image:0.19.2** 

**Environment**:
- **Mac** 

**you can type  "docker run --rm -v "/tmdata:/tendermint" tendermint/tendermint:0.19.2 init" reproduce that** 

**Logs**

**panic: Panicked on a Sanity Check: Could not create directory /tendermint/config. mkdir /tendermint/config: permission denied

goroutine 1 [running]:
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.PanicSanity(0xb42160, 0xc420966770)
	/home/jslave/workspace/02.Fetch.Binary/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/errors.go:243 +0xe4
github.com/tendermint/tendermint/config.EnsureRoot(0xc4202210e8, 0xb)
	/home/jslave/workspace/02.Fetch.Binary/go/src/github.com/tendermint/tendermint/config/toml.go:30 +0x312
github.com/tendermint/tendermint/cmd/tendermint/commands.ParseConfig(0x1278fa0, 0xc7c45c, 0x7)
	/home/jslave/workspace/02.Fetch.Binary/go/src/github.com/tendermint/tendermint/cmd/tendermint/commands/root.go:37 +0xf2
github.com/tendermint/tendermint/cmd/tendermint/commands.glob..func3(0x1277f00, 0x12a20a0, 0x0, 0x0, 0x0, 0x0)
	/home/jslave/workspace/02.Fetch.Binary/go/src/github.com/tendermint/tendermint/cmd/tendermint/commands/root.go:49 +0x6e
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/cli.concatCobraCmdFuncs.func1(0x1277f00, 0x12a20a0, 0x0, 0x0, 0x0, 0x0)
	/home/jslave/workspace/02.Fetch.Binary/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/cli/setup.go:115 +0x7d
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).execute(0x1277f00, 0x12a20a0, 0x0, 0x0, 0x1277f00, 0x12a20a0)
	/home/jslave/workspace/02.Fetch.Binary/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:735 +0x579
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1279200, 0xbb1140, 0xc420015e01, 0xc42010d760)
	/home/jslave/workspace/02.Fetch.Binary/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).Execute(0x1279200, 0xc42010d760, 0xc420015e98)
	/home/jslave/workspace/02.Fetch.Binary/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:794 +0x2b
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x1279200, 0xdd6b18, 0x2, 0xc420220f80)
	/home/jslave/workspace/02.Fetch.Binary/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/cli/setup.go:89 +0x4e
main.main()
	/home/jslave/workspace/02.Fetch.Binary/go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:45 +0x24d

**Comment by yunkunrao** [comment] 2018-05-09 05:27
There's workaround for this issue, you can set "USER root"  instead of "USER tmuser" in Dockerfile. And it works in my environment.

**Comment by greg-szabo** [comment] 2018-05-16 15:34
`chmod 777 /tmdata` (insecure) or 
`chown 100 /tmdata` (weird) should fix it.

The problem is that your /tmdata folder permissions do not allow user `tmuser` (uid 100) to write to the folder. Tendermint is run as `tmuser` within the Docker container.

The first workaround enabled everyone in the system to write to the folder, hence the dockerized tmuser will be able to write. The second solution reassigners the owner of the folder to the user id 100 which is unregistered on the mac (hence I didn't use the username) but docker will be able to write to it as userid 100.

**Closed by greg-szabo** 2018-05-16 15:34 UTC
Labels: bug
